//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AdsFeature.h"
#import "SPTFeature.h"

@class NSString, SPTAdCosmosSettingsController, SPTAdNowPlayingManager, SPTAdsActivityLogger, SPTAdsDriverDistractionManager, SPTAdsManager, SPTAdsViewModel, SPTAllocationContext;

@interface AdsFeatureImplementation : NSObject <SPTFeature, AdsFeature>
{
    id <BaseFeature> _base;
    id <CosmosFeature> _cosmos;
    id <SPTPlayerFeature> _player;
    id <SettingsFeature> _settings;
    id <SPTVideoFeature> _videoFeature;
    SPTAdsManager *_adsManager;
    SPTAdsViewModel *_adsViewModel;
    SPTAdNowPlayingManager *_adNowPlayingManager;
    SPTAdsActivityLogger *_adsActivityLogger;
    SPTAdsDriverDistractionManager *_adsDriverDistractionManager;
    id <SPTResolver> _adResolver;
    SPTAdCosmosSettingsController *_adCosmosSettingsController;
}

+ (id)featureDependencies;
+ (id)featureVersion;
+ (id)featureIdentifier;
@property(retain, nonatomic) SPTAdCosmosSettingsController *adCosmosSettingsController; // @synthesize adCosmosSettingsController=_adCosmosSettingsController;
@property(retain, nonatomic) id <SPTResolver> adResolver; // @synthesize adResolver=_adResolver;
@property(retain, nonatomic) SPTAdsDriverDistractionManager *adsDriverDistractionManager; // @synthesize adsDriverDistractionManager=_adsDriverDistractionManager;
@property(retain, nonatomic) SPTAdsActivityLogger *adsActivityLogger; // @synthesize adsActivityLogger=_adsActivityLogger;
@property(retain, nonatomic) SPTAdNowPlayingManager *adNowPlayingManager; // @synthesize adNowPlayingManager=_adNowPlayingManager;
@property(retain, nonatomic) SPTAdsViewModel *adsViewModel; // @synthesize adsViewModel=_adsViewModel;
@property(retain, nonatomic) SPTAdsManager *adsManager; // @synthesize adsManager=_adsManager;
@property(nonatomic) __weak id <SPTVideoFeature> videoFeature; // @synthesize videoFeature=_videoFeature;
@property(nonatomic) __weak id <SettingsFeature> settings; // @synthesize settings=_settings;
@property(nonatomic) __weak id <SPTPlayerFeature> player; // @synthesize player=_player;
@property(nonatomic) __weak id <CosmosFeature> cosmos; // @synthesize cosmos=_cosmos;
@property(nonatomic) __weak id <BaseFeature> base; // @synthesize base=_base;
- (void).cxx_destruct;
- (BOOL)isHLSVideoDisabled;
- (BOOL)isPrerollReRequestEnabled;
- (BOOL)isPrerollEnabled;
- (BOOL)isCosmosWatchNowEnabled;
- (BOOL)isAdsEnabledForProductState:(id)arg1;
- (id)provideAdsPlayer;
- (id)provideAdsManager;
- (id)createResolverForView:(id)arg1;
- (id)provideAdResolver;
- (id)provideAdNowPlayingManager;
- (id)provideAdsViewModel;
- (id)provideAdEventLogger;
- (id)provideAdsActivityLogger;
- (id)provideAdCosmosSettingsController;
- (BOOL)isWatchNowEnabled;
- (void)didRegisterAdResolver:(id)arg1;
- (void)unload;
- (void)load;
- (void)configureWithFeatures:(id)arg1;

// Remaining properties
@property(retain, nonatomic) SPTAllocationContext *allocationContext;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

