//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDateFormatter, NSString, UIColor, UINavigationController;

@interface BITHockeyBaseManager : NSObject
{
    UINavigationController *_navController;
    NSDateFormatter *_rfc3339Formatter;
    BOOL _isAppStoreEnvironment;
    NSString *_serverURL;
    int _barStyle;
    UIColor *_navigationBarTintColor;
    int _modalPresentationStyle;
    NSString *_appIdentifier;
}

@property(retain, nonatomic) NSString *appIdentifier; // @synthesize appIdentifier=_appIdentifier;
@property(nonatomic) int modalPresentationStyle; // @synthesize modalPresentationStyle=_modalPresentationStyle;
@property(retain, nonatomic) UIColor *navigationBarTintColor; // @synthesize navigationBarTintColor=_navigationBarTintColor;
@property(nonatomic) int barStyle; // @synthesize barStyle=_barStyle;
@property(copy, nonatomic) NSString *serverURL; // @synthesize serverURL=_serverURL;
- (void).cxx_destruct;
- (id)parseRFC3339Date:(id)arg1;
- (void)startManager;
- (BOOL)removeKeyFromKeychain:(id)arg1;
- (id)stringValueFromKeychainForKey:(id)arg1;
- (BOOL)addStringValueToKeychainForThisDeviceOnly:(id)arg1 forKey:(id)arg2;
- (BOOL)addStringValueToKeychain:(id)arg1 forKey:(id)arg2;
- (void)showView:(id)arg1;
- (id)customNavigationControllerWithRootViewController:(id)arg1 presentationStyle:(int)arg2;
- (id)findVisibleWindow;
- (id)executableUUID;
- (id)getDevicePlatform;
- (BOOL)isPreiOS7Environment;
- (id)encodedAppIdentifier;
- (BOOL)isAppStoreEnvironment;
- (void)reportError:(id)arg1;
- (id)initWithAppIdentifier:(id)arg1 isAppStoreEnvironment:(BOOL)arg2;
- (id)init;

@end

