//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIViewController;

@protocol FollowFeature <NSObject>
+ (NSString *)featureVersion;
- (void)presentFollowFromViewController:(UIViewController *)arg1;
- (UIViewController *)provideFollowFacebookVC;
- (UIViewController *)provideFollowRootVC;
@end

