//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface NSDate (SPTNewMusicTuesday)
+ (id)spt_dateInTimeZone:(id)arg1 year:(int)arg2 month:(int)arg3 day:(int)arg4 hour:(int)arg5 minute:(int)arg6 second:(int)arg7;
+ (id)spt_date:(id)arg1 inTimeZone:(id)arg2 hour:(int)arg3 minute:(int)arg4;
+ (id)spt_dateFromDateTimeString:(id)arg1;
+ (id)spt_dateFromDateString:(id)arg1;
+ (id)spt_timeFromTimeString:(id)arg1;
- (int)spt_secondForTimeZone:(id)arg1;
@property(readonly, nonatomic) int spt_second;
- (int)spt_minuteForTimeZone:(id)arg1;
@property(readonly, nonatomic) int spt_minute;
- (int)spt_hourForTimeZone:(id)arg1;
@property(readonly, nonatomic) int spt_hour;
- (int)spt_dayForTimeZone:(id)arg1;
@property(readonly, nonatomic) int spt_day;
- (int)spt_monthForTimeZone:(id)arg1;
@property(readonly, nonatomic) int spt_month;
- (int)spt_yearForTimeZone:(id)arg1;
@property(readonly, nonatomic) int spt_year;
@property(readonly, nonatomic) int spt_weekday;
- (BOOL)spt_isTimeEqualToTime:(id)arg1;
@end

