//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableAttributedString.h"

@interface NSMutableAttributedString (Utility)
- (void)sp_setLinkForRange:(struct _NSRange)arg1;
- (void)sp_setTextAlignment:(unsigned char)arg1 range:(struct _NSRange)arg2;
- (void)sp_setTextAlignment:(unsigned char)arg1;
- (void)sp_setTextColor:(id)arg1 range:(struct _NSRange)arg2;
- (void)sp_setTextColor:(id)arg1;
- (void)sp_setFontTrait:(unsigned int)arg1 enabled:(BOOL)arg2 range:(struct _NSRange)arg3;
- (void)sp_setItalic:(BOOL)arg1 range:(struct _NSRange)arg2;
- (void)sp_setBold:(BOOL)arg1 range:(struct _NSRange)arg2;
- (void)sp_setFont:(id)arg1 size:(float)arg2 range:(struct _NSRange)arg3;
- (void)sp_setFont:(id)arg1 size:(float)arg2;
- (void)sp_setFont:(id)arg1 range:(struct _NSRange)arg2;
- (void)sp_setFont:(id)arg1;
@end

