//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURL.h"

@interface NSURL (Video)
+ (id)spt_videoDebugImmediacyViewURL;
+ (id)spt_videoDebugListViewURL;
+ (id)spt_videoDebugMainViewURL;
@property(readonly, nonatomic, getter=spt_isVideoDebugImmediacyViewURL) BOOL isVideoDebugImmediacyViewURL;
@property(readonly, nonatomic, getter=spt_isVideoDebugListViewURL) BOOL isVideoDebugListViewURL;
@property(readonly, nonatomic, getter=spt_isVideoDebugMainViewURL) BOOL isVideoDebugMainViewURL;
@end

