//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@interface ProfileLoadTimeLabel : UILabel
{
    double _loadTime;
    double _goodLoadTime;
    double _highLoadTime;
}

@property(nonatomic) double highLoadTime; // @synthesize highLoadTime=_highLoadTime;
@property(nonatomic) double goodLoadTime; // @synthesize goodLoadTime=_goodLoadTime;
@property(nonatomic) double loadTime; // @synthesize loadTime=_loadTime;
- (void)updateLabelColor;
- (id)initWithFrame:(struct CGRect)arg1 goodLoadTime:(double)arg2 highLoadTime:(double)arg3;

@end

