//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTBaseViewModel.h"

#import "SPTPlayerObserver.h"

@class NSString, NSURL, ProfileViewAllViewModelData, SPTClientEventLogger;

@interface ProfileViewAllViewModel : SPTBaseViewModel <SPTPlayerObserver>
{
    int _dataType;
    ProfileViewAllViewModelData *_data;
    NSURL *_uri;
    id <SPTAudioTouch> _audioTouch;
    id <SPTPlayer> _player;
    id <ProfileFeature> _feature;
    SPTClientEventLogger *_logger;
}

+ (id)entityWithDataType:(int)arg1 dictionary:(id)arg2;
+ (int)dataTypeForEntity:(id)arg1;
@property(retain, nonatomic) SPTClientEventLogger *logger; // @synthesize logger=_logger;
@property(nonatomic) __weak id <ProfileFeature> feature; // @synthesize feature=_feature;
@property(retain, nonatomic) id <SPTPlayer> player; // @synthesize player=_player;
@property(retain, nonatomic) id <SPTAudioTouch> audioTouch; // @synthesize audioTouch=_audioTouch;
@property(retain, nonatomic) NSURL *uri; // @synthesize uri=_uri;
@property(readonly, nonatomic) ProfileViewAllViewModelData *data; // @synthesize data=_data;
@property(nonatomic) int dataType; // @synthesize dataType=_dataType;
- (void).cxx_destruct;
- (id)entitiesListKey;
- (void)player:(id)arg1 stateDidChange:(id)arg2;
- (void)startPlayerObserving;
- (void)pushViewControllerForEntity:(id)arg1 rank:(unsigned int)arg2;
- (id)parseResponse:(id)arg1 requestKey:(id)arg2 error:(id *)arg3;
- (void)requestData;
- (id)initWithRequestURLDictionary:(id)arg1 player:(id)arg2 offlineModeState:(id)arg3 url:(id)arg4 feature:(id)arg5 logger:(id)arg6 dataType:(int)arg7 audioTouch:(id)arg8 apolloDataLoader:(id)arg9;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <ProfileViewAllViewModelDelegate> delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

