//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RAPIGroupPart : NSObject
{
    int _groupIndex;
    int _itemOffset;
    int _itemCount;
}

@property int itemCount; // @synthesize itemCount=_itemCount;
@property int itemOffset; // @synthesize itemOffset=_itemOffset;
@property int groupIndex; // @synthesize groupIndex=_groupIndex;

@end

