//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTAdsManager.h"
#import "SPTAdsViewControllerDelegate.h"
#import "SPTAdsViewModelInternalDelegate.h"

@class MetaViewController, NSString, SPTAdNowPlayingManager, SPTAdsBarViewController, SPTAdsVideoViewController, SPTAdsViewController, SPTAdsViewModel, UIViewController;

@interface SPTAdsManager : NSObject <SPTAdsViewModelInternalDelegate, SPTAdsViewControllerDelegate, SPTAdsManager>
{
    BOOL _wasStatusBarHidden;
    MetaViewController *_metaViewController;
    SPTAdNowPlayingManager *_adNowPlayingManager;
    SPTAdsViewModel *_adsViewModel;
    SPTAdsViewController *_adsViewController;
    SPTAdsVideoViewController *_adsVideoViewController;
    SPTAdsBarViewController *_adsBarViewController;
    UIViewController *_previousBottomAttachmentViewController;
    id <SPTNowPlayingNavigationBarProtocol> _nowPlayingNavigationBarModel;
}

@property(nonatomic) __weak id <SPTNowPlayingNavigationBarProtocol> nowPlayingNavigationBarModel; // @synthesize nowPlayingNavigationBarModel=_nowPlayingNavigationBarModel;
@property(retain, nonatomic) UIViewController *previousBottomAttachmentViewController; // @synthesize previousBottomAttachmentViewController=_previousBottomAttachmentViewController;
@property(nonatomic) BOOL wasStatusBarHidden; // @synthesize wasStatusBarHidden=_wasStatusBarHidden;
@property(retain, nonatomic) SPTAdsBarViewController *adsBarViewController; // @synthesize adsBarViewController=_adsBarViewController;
@property(retain, nonatomic) SPTAdsVideoViewController *adsVideoViewController; // @synthesize adsVideoViewController=_adsVideoViewController;
@property(retain, nonatomic) SPTAdsViewController *adsViewController; // @synthesize adsViewController=_adsViewController;
@property(nonatomic) __weak SPTAdsViewModel *adsViewModel; // @synthesize adsViewModel=_adsViewModel;
@property(nonatomic) __weak SPTAdNowPlayingManager *adNowPlayingManager; // @synthesize adNowPlayingManager=_adNowPlayingManager;
@property(retain, nonatomic) MetaViewController *metaViewController; // @synthesize metaViewController=_metaViewController;
- (void).cxx_destruct;
- (void)adsViewModel:(id)arg1 didFinishPlaying:(BOOL)arg2;
- (void)adsViewModel:(id)arg1 shouldPlayAds:(BOOL)arg2;
- (void)toggleAdViewModel:(id)arg1 toMinimize:(BOOL)arg2 navigateTo:(id)arg3;
- (void)setupBarAd;
- (void)displayAd;
- (void)updateDisableNavigationBarMinimizationState;
- (void)setNowPlayingManager:(id)arg1;
- (void)playPrerollAdIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (void)disablePrerollAdExperience:(BOOL)arg1 featureIdentifier:(id)arg2;
- (BOOL)handleAdTap:(id)arg1;
@property(readonly, nonatomic) BOOL presentAdUsingDissolveTransition;
@property(readonly, nonatomic) BOOL isVideoCompanionAd;
@property(readonly, nonatomic) BOOL isNowPlayingViewForcedOpen;
@property(readonly, copy, nonatomic) NSString *actionMessage;
@property(readonly, nonatomic) BOOL isEndOfWatchNow;
@property(readonly, nonatomic) BOOL isPrerollOffer;
@property(readonly, nonatomic) BOOL isMidrollOffer;
@property(readonly, nonatomic) BOOL adBreakInProgress;
- (void)addObservers;
- (id)initWithViewModel:(id)arg1 metaViewController:(id)arg2 adNowPlayingManager:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

