//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface SPTActivityData : NSObject
{
    BOOL _hasLoadedAllOlderEntities;
    NSString *_nextPagePath;
    NSMutableArray *_entities;
}

@property(retain, nonatomic) NSMutableArray *entities; // @synthesize entities=_entities;
@property(readonly, nonatomic) NSString *nextPagePath; // @synthesize nextPagePath=_nextPagePath;
@property(nonatomic) BOOL hasLoadedAllOlderEntities; // @synthesize hasLoadedAllOlderEntities=_hasLoadedAllOlderEntities;
- (void).cxx_destruct;
- (void)setNextPagePath:(id)arg1;
- (void)prependData:(id)arg1;
- (void)appendData:(id)arg1;
- (id)objectAtIndexedSubscript:(unsigned int)arg1;
- (id)objectAtIndex:(int)arg1;
- (int)count;
- (id)initWithDictionary:(id)arg1 currentUser:(id)arg2;

@end

