//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SPTAdConfig : NSObject
{
    NSString *_endpointTemplate;
    double _streamTimeIntervalInMilliseconds;
}

@property(retain, nonatomic) NSString *endpointTemplate; // @synthesize endpointTemplate=_endpointTemplate;
@property(nonatomic) double streamTimeIntervalInMilliseconds; // @synthesize streamTimeIntervalInMilliseconds=_streamTimeIntervalInMilliseconds;
- (void).cxx_destruct;

@end

