//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CLLocation, MKMapView, NSString, SPTTheme, UILabel;

@interface SPTConcertLocationView : UIView
{
    CLLocation *_location;
    SPTTheme *_theme;
    MKMapView *_mapView;
    UIView *_rectangleContainerView;
    UILabel *_venueNameLabel;
    UILabel *_venueCityLabel;
}

@property(retain, nonatomic) UILabel *venueCityLabel; // @synthesize venueCityLabel=_venueCityLabel;
@property(retain, nonatomic) UILabel *venueNameLabel; // @synthesize venueNameLabel=_venueNameLabel;
@property(retain, nonatomic) UIView *rectangleContainerView; // @synthesize rectangleContainerView=_rectangleContainerView;
@property(retain, nonatomic) MKMapView *mapView; // @synthesize mapView=_mapView;
@property(retain, nonatomic) SPTTheme *theme; // @synthesize theme=_theme;
@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *subtitle;
@property(copy, nonatomic) NSString *title;
- (void)setupMapView;
- (void)setupMapSubtitle;
- (void)setupMapTitle;
- (void)setupContainerRectangleView;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

