//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSIndexPath.h"

@interface SPTCeramicIndexPath : NSIndexPath
{
}

+ (id)indexPathWithBlockIndex:(int)arg1 collectionIndexPath:(id)arg2;
- (BOOL)isEqual:(id)arg1;
@property(readonly, nonatomic) int item;
@property(readonly, nonatomic) int section;
@property(readonly, nonatomic) int blockIndex;
- (id)initWithBlockIndex:(int)arg1 collectionIndexPath:(id)arg2;

@end

