//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, SPTFindFriendsViewModel;

@protocol SPTFindFriendsViewModelDelegate <NSObject>
- (void)findFriendsViewModel:(SPTFindFriendsViewModel *)arg1 hasDisconnectedFromNetworkType:(int)arg2;
- (void)findFriendsViewModel:(SPTFindFriendsViewModel *)arg1 hasConnectedToNetworkType:(int)arg2;
- (void)findFriendsViewModel:(SPTFindFriendsViewModel *)arg1 didFindMatches:(BOOL)arg2;
- (void)findFriendsViewModel:(SPTFindFriendsViewModel *)arg1 hasLoadedFriendsWithSuccess:(BOOL)arg2 error:(NSError *)arg3;

@optional
- (void)findFriendsViewModel:(SPTFindFriendsViewModel *)arg1 didFailToUpdateFollowStateWithError:(NSError *)arg2;
- (void)findFriendsViewModel:(SPTFindFriendsViewModel *)arg1 didUpdateFollowStateForUserAtIndex:(unsigned int)arg2;
- (void)findFriendsViewModel:(SPTFindFriendsViewModel *)arg1 isOffline:(BOOL)arg2;
- (void)findFriendsViewModel:(SPTFindFriendsViewModel *)arg1 isLoading:(BOOL)arg2;
@end

