//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol SPTHLSResourceLoaderFactory <NSObject>
- (id <SPTHLSResourceLoader>)createHLSResourceLoaderWithVideoSourceID:(NSString *)arg1 playbackID:(NSString *)arg2;
@end

