//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTImageLoaderRequest.h"

@class AVAsset, NSDate, NSString, NSURL, SPTDataLoader;

@interface SPTImageLoaderRequest : NSObject <SPTImageLoaderRequest>
{
    BOOL _cancelCalled;
    NSURL *_URL;
    id _context;
    NSString *_persistenceKey;
    NSDate *_creationDate;
    SPTDataLoader *_dataLoader;
    id <SPTCancellationToken> _cancelToken;
    id <SPTLocalFileImageLoadingDelegate> _delegate;
    AVAsset *_asset;
    struct CGSize _size;
}

+ (id)imageLoaderRequestWithURL:(id)arg1 size:(struct CGSize)arg2 context:(id)arg3 dataLoader:(id)arg4 delegate:(id)arg5;
@property(retain) AVAsset *asset; // @synthesize asset=_asset;
@property(nonatomic) __weak id <SPTLocalFileImageLoadingDelegate> delegate; // @synthesize delegate=_delegate;
@property BOOL cancelCalled; // @synthesize cancelCalled=_cancelCalled;
@property(retain) id <SPTCancellationToken> cancelToken; // @synthesize cancelToken=_cancelToken;
@property(retain, nonatomic) SPTDataLoader *dataLoader; // @synthesize dataLoader=_dataLoader;
@property(readonly, nonatomic) NSDate *creationDate; // @synthesize creationDate=_creationDate;
@property(retain, nonatomic) NSString *persistenceKey; // @synthesize persistenceKey=_persistenceKey;
@property(readonly, nonatomic) id context; // @synthesize context=_context;
@property(readonly, nonatomic) struct CGSize size; // @synthesize size=_size;
@property(readonly, nonatomic) NSURL *URL; // @synthesize URL=_URL;
- (void).cxx_destruct;
- (id)optimalImageForResizingTo:(struct CGSize)arg1 fromImages:(id)arg2;
- (id)sortImagesBySize:(id)arg1;
- (id)imagesDataFromAVMetadataItems:(id)arg1;
- (void)dispatchError:(id)arg1;
- (void)disaptchSuccess:(id)arg1;
- (void)loadRemoteImageWithURL:(id)arg1;
- (void)loadLocalFileImage;
- (BOOL)cancelled;
- (void)cancel;
- (void)load;
- (id)initWithURL:(id)arg1 size:(struct CGSize)arg2 context:(id)arg3 dataLoader:(id)arg4 delegate:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

