//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTPlayerObserver.h"
#import "SPTPlayerQueueObserver.h"

@class NSHashTable, NSString, SPTPlayerQueueSnapshot, SPTPlayerState;

@interface SPTNowPlayingQueueMetadataModel : NSObject <SPTPlayerObserver, SPTPlayerQueueObserver>
{
    NSHashTable *_observers;
    id <SPTPlayer> _player;
    id <SPTPlayerQueue> _playerQueue;
    SPTPlayerState *_lastUpdateState;
    SPTPlayerQueueSnapshot *_lastQueueSnapshot;
    id <SPTRunningTestManager> _runningTestManager;
}

@property(retain, nonatomic) id <SPTRunningTestManager> runningTestManager; // @synthesize runningTestManager=_runningTestManager;
@property(retain, nonatomic) SPTPlayerQueueSnapshot *lastQueueSnapshot; // @synthesize lastQueueSnapshot=_lastQueueSnapshot;
@property(retain, nonatomic) SPTPlayerState *lastUpdateState; // @synthesize lastUpdateState=_lastUpdateState;
@property(retain, nonatomic) id <SPTPlayerQueue> playerQueue; // @synthesize playerQueue=_playerQueue;
@property(retain, nonatomic) id <SPTPlayer> player; // @synthesize player=_player;
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
- (void).cxx_destruct;
- (void)playerQueue:(id)arg1 wasUpdated:(id)arg2;
- (void)player:(id)arg1 stateDidChange:(id)arg2 fromState:(id)arg3;
@property(readonly, nonatomic) int numberOfUserQueuedTracks;
@property(readonly, nonatomic) BOOL disallowOpeningQueue;
@property(readonly, nonatomic) BOOL disallowViewingQueue;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)dealloc;
- (id)initWithPlayer:(id)arg1 playerQueue:(id)arg2 runningTestManager:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

