//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTNowPlayingBaseHeadUnitViewController.h"

#import "SPTNowPlayingModelDelegate.h"

@class NSString, SPTLogCenter, SPTNowPlayingBaseHeadUnitController, SPTNowPlayingModel, SPTNowPlayingPodcastHeadUnitView;

@interface SPTNowPlayingPodcastHeadUnitViewController : SPTNowPlayingBaseHeadUnitViewController <SPTNowPlayingModelDelegate>
{
    SPTNowPlayingModel *_model;
    SPTNowPlayingBaseHeadUnitController *_headUnitController;
    SPTLogCenter *_logCenter;
    id <SPTUpsellPopupManager> _upsellPopupManager;
}

@property(nonatomic) __weak id <SPTUpsellPopupManager> upsellPopupManager; // @synthesize upsellPopupManager=_upsellPopupManager;
@property(nonatomic) __weak SPTLogCenter *logCenter; // @synthesize logCenter=_logCenter;
@property(retain, nonatomic) SPTNowPlayingBaseHeadUnitController *headUnitController; // @synthesize headUnitController=_headUnitController;
@property(retain, nonatomic) SPTNowPlayingModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)nowPlayingModel:(id)arg1 didMoveToRelativeTrack:(id)arg2;
- (void)nowPlayingModelDidUpdateMetadata:(id)arg1;
- (void)needUpdateUI;
- (void)skip15SecForwardButtonTouchedUpInside:(id)arg1;
- (void)skip15SecBackwardButtonTouchedUpInside:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)initWithModel:(id)arg1 theme:(id)arg2 logCenter:(id)arg3 upsellPopupManager:(id)arg4;
- (id)initWithTheme:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) SPTNowPlayingPodcastHeadUnitView *view;

@end

