//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTPlayerObserver.h"

@class NSString;

@interface SPTNowPlayingViewShowFirstTime : NSObject <SPTPlayerObserver>
{
    id <SPTTinkerbellManager> _tinkerbellManager;
    id <SPTTinkerbellStoryRegistry> _tinkerbellStoryRegistry;
    id <SPTNowPlayingManager> _nowPlayingManager;
    id <SPTPlayer> _player;
}

+ (void)setShownForTheFirstTime;
+ (BOOL)isShownForTheFirstTime;
@property(readonly, nonatomic) id <SPTPlayer> player; // @synthesize player=_player;
@property(readonly, nonatomic) id <SPTNowPlayingManager> nowPlayingManager; // @synthesize nowPlayingManager=_nowPlayingManager;
@property(retain, nonatomic) id <SPTTinkerbellStoryRegistry> tinkerbellStoryRegistry; // @synthesize tinkerbellStoryRegistry=_tinkerbellStoryRegistry;
@property(retain, nonatomic) id <SPTTinkerbellManager> tinkerbellManager; // @synthesize tinkerbellManager=_tinkerbellManager;
- (void).cxx_destruct;
- (BOOL)willTinkerbellBePresented;
- (void)player:(id)arg1 stateDidChange:(id)arg2;
- (id)initWithNowPlayingManager:(id)arg1 player:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

