//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTFeature.h"

@protocol SPTOfflinePlaylistFeature <SPTFeature>
@property(readonly, nonatomic, getter=isOfflinePlaylistAvailable) BOOL offlinePlaylistAvailable;
- (id <SPTOfflineInfoViewFactory>)provideInfoViewFactory;
@end

