//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTOfflineModeStateObserver.h"
#import "SPTPartyGenresLoaderDelegate.h"
#import "SPTPartyPlaybackManagerDelegate.h"
#import "SPTPartyTracksLoaderDelegate.h"
#import "SPTPlayerObserver.h"
#import "SPTProductStateObserver.h"

@class NSArray, NSString, SPTPartyGenre, SPTPartyGenreTree, SPTPartyGenresLoader, SPTPartyParameters, SPTPartyPlaybackManager, SPTPartyTracksLoader;

@interface SPTPartyViewModel : NSObject <SPTPlayerObserver, SPTOfflineModeStateObserver, SPTProductStateObserver, SPTPartyGenresLoaderDelegate, SPTPartyTracksLoaderDelegate, SPTPartyPlaybackManagerDelegate>
{
    id <SPTPartyViewModelDelegate> _delegate;
    id <SPTProductState> _productState;
    SPTPartyGenreTree *_genreTree;
    SPTPartyGenre *_currentSubGenre;
    SPTPartyGenre *_currentParentGenre;
    int _currentEnergyLevel;
    SPTPartyGenresLoader *_genresLoader;
    SPTPartyTracksLoader *_tracksLoader;
    SPTPartyPlaybackManager *_playbackManager;
    id <SPTOfflineModeState> _offlineModeState;
    SPTPartyParameters *_currentPartyParameters;
}

@property(retain, nonatomic) SPTPartyParameters *currentPartyParameters; // @synthesize currentPartyParameters=_currentPartyParameters;
@property(retain, nonatomic) id <SPTOfflineModeState> offlineModeState; // @synthesize offlineModeState=_offlineModeState;
@property(retain, nonatomic) SPTPartyPlaybackManager *playbackManager; // @synthesize playbackManager=_playbackManager;
@property(retain, nonatomic) SPTPartyTracksLoader *tracksLoader; // @synthesize tracksLoader=_tracksLoader;
@property(retain, nonatomic) SPTPartyGenresLoader *genresLoader; // @synthesize genresLoader=_genresLoader;
@property(nonatomic) int currentEnergyLevel; // @synthesize currentEnergyLevel=_currentEnergyLevel;
@property(nonatomic) __weak SPTPartyGenre *currentParentGenre; // @synthesize currentParentGenre=_currentParentGenre;
@property(retain, nonatomic) SPTPartyGenre *currentSubGenre; // @synthesize currentSubGenre=_currentSubGenre;
@property(retain, nonatomic) SPTPartyGenreTree *genreTree; // @synthesize genreTree=_genreTree;
@property(retain, nonatomic) id <SPTProductState> productState; // @synthesize productState=_productState;
@property(nonatomic) __weak id <SPTPartyViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)productState:(id)arg1 stateDidChange:(id)arg2;
- (void)offlineModeState:(id)arg1 updated:(BOOL)arg2;
- (BOOL)playbackManagerAllowsOnDemandPlayback:(id)arg1;
- (void)playbackManager:(id)arg1 playerStateDidChange:(id)arg2;
- (void)tracksLoader:(id)arg1 didFailToLoadTracksWithError:(id)arg2;
- (void)tracksLoader:(id)arg1 didLoadTracks:(id)arg2;
- (void)genresLoader:(id)arg1 didFailToLoadGenresWithError:(id)arg2;
- (void)genresLoader:(id)arg1 didLoadGenreTree:(id)arg2;
- (void)updateBasedOnNewParameters;
- (BOOL)allowsOnDemandPlayback;
@property(readonly, nonatomic) NSArray *playerTracks;
- (void)startShufflingIfPossible;
- (void)playTrackAtIndex:(unsigned int)arg1;
- (void)setCurrentParentGenreIndex:(unsigned int)arg1 childGenreIndex:(unsigned int)arg2;
- (void)setCurrentParentGenreIndex:(unsigned int)arg1;
- (int)indexForCurrentParentGenre;
- (void)loadGenres;
- (id)initWithGenresLoader:(id)arg1 tracksLoader:(id)arg2 playbackManager:(id)arg3 offlineModeState:(id)arg4 productState:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

