//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTPlayerIndex.h"

@interface SPTPlayerNumericIndex : SPTPlayerIndex
{
    unsigned int _track;
    unsigned int _page;
}

+ (id)forTrack:(unsigned int)arg1 inPage:(unsigned int)arg2;
+ (id)forTrack:(unsigned int)arg1;
@property(readonly, nonatomic) unsigned int page; // @synthesize page=_page;
@property(readonly, nonatomic) unsigned int track; // @synthesize track=_track;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)serializedDictionary;
- (id)initWithDictionary:(id)arg1;
- (id)initWithTrack:(unsigned int)arg1 inPage:(unsigned int)arg2;

@end

