//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSURL;

@protocol SPTPodcastCollectionModel
- (void)removeURL:(NSURL *)arg1 callback:(void (^)(BOOL, NSError *))arg2;
- (void)addURL:(NSURL *)arg1 callback:(void (^)(BOOL, NSError *))arg2;
@end

