//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "SPTSwipeableTableViewCellGestureHandler.h"

@class NSString, UIView;

@interface SPTSwipeableTableViewCell : UITableViewCell <SPTSwipeableTableViewCellGestureHandler>
{
    BOOL _gestureActivated;
    id <SPTSwipeableTableViewCellDelegate> _swipeDelegate;
    UIView *_shelvesView;
    UIView *_containerView;
    unsigned int _initialGesture;
    struct CGPoint _initialTranslation;
    struct CGPoint _currentTranslation;
    double _initialTime;
    double _currentTime;
}

+ (unsigned int)gestureFromTranslation:(float)arg1;
+ (unsigned int)gestureFromPercentage:(float)arg1;
@property(nonatomic) double currentTime; // @synthesize currentTime=_currentTime;
@property(nonatomic) double initialTime; // @synthesize initialTime=_initialTime;
@property(nonatomic) struct CGPoint currentTranslation; // @synthesize currentTranslation=_currentTranslation;
@property(nonatomic) struct CGPoint initialTranslation; // @synthesize initialTranslation=_initialTranslation;
@property(nonatomic, getter=isGestureActivated) BOOL gestureActivated; // @synthesize gestureActivated=_gestureActivated;
@property(nonatomic) unsigned int initialGesture; // @synthesize initialGesture=_initialGesture;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIView *shelvesView; // @synthesize shelvesView=_shelvesView;
@property(nonatomic) __weak id <SPTSwipeableTableViewCellDelegate> swipeDelegate; // @synthesize swipeDelegate=_swipeDelegate;
- (void).cxx_destruct;
- (BOOL)supportsSwiping;
- (void)handlePanGestureRecognizer:(id)arg1;
- (void)resetContainerFromPoint:(struct CGPoint)arg1 subjectToInertia:(BOOL)arg2 horizontalVelocity:(float)arg3 withCompletionBlock:(CDUnknownBlockType)arg4;
- (void)moveContainerWithHorizontalTranslation:(float)arg1 horizontalVelocity:(float)arg2;
- (float)percentageFromOffset:(float)arg1;
- (void)removeShelfForGesture:(unsigned int)arg1;
- (void)setShelf:(id)arg1 forGesture:(unsigned int)arg2;
- (id)shelfForOffset:(float)arg1;
- (id)oppositeShelfForGesture:(unsigned int)arg1;
- (id)shelfForGesture:(unsigned int)arg1;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setBackgroundView:(id)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

