//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL, SPTStartPageCurrentlyPlayingMomentContext, SPTStartPagePlayerObserver;

@protocol SPTStartPagePlayerObserverDelegate <NSObject>
- (void)playerObserver:(SPTStartPagePlayerObserver *)arg1 persistPosition:(double)arg2 trackURI:(NSURL *)arg3 forURI:(NSURL *)arg4;
- (void)playerObserver:(SPTStartPagePlayerObserver *)arg1 playerDidPause:(BOOL)arg2;
- (void)playerObserver:(SPTStartPagePlayerObserver *)arg1 startedPlayingNewContext:(SPTStartPageCurrentlyPlayingMomentContext *)arg2;
@end

