//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, SPSession;

@interface SPTStartPagePrefetchManager : NSObject
{
    BOOL _prefetchEnabled;
    SPSession *_session;
    id <SPTPlayer> _player;
    NSMutableDictionary *_prefetchedPlayObjects;
}

@property(retain, nonatomic) NSMutableDictionary *prefetchedPlayObjects; // @synthesize prefetchedPlayObjects=_prefetchedPlayObjects;
@property(retain, nonatomic) id <SPTPlayer> player; // @synthesize player=_player;
@property(readonly, nonatomic) __weak SPSession *session; // @synthesize session=_session;
@property(nonatomic) BOOL prefetchEnabled; // @synthesize prefetchEnabled=_prefetchEnabled;
- (void).cxx_destruct;
- (void)removePlayObjectForEntityURL:(id)arg1;
- (id)playObjectForEntityURL:(id)arg1;
- (void)prefetchContext:(id)arg1 playOptions:(id)arg2;
- (id)initWithSession:(id)arg1 player:(id)arg2;

@end

