//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableDictionary, NSString, NSURL, SPTSocialChartAlbumData, SPTSocialChartArtistData;

@interface SPTSocialChartTrackData : NSObject
{
    BOOL _unavailableForPlayback;
    BOOL _listenedToByCurrentUser;
    NSURL *_imageURL;
    NSString *_name;
    NSURL *_uri;
    SPTSocialChartAlbumData *_album;
    SPTSocialChartArtistData *_artist;
    NSArray *_influencers;
    unsigned int _position;
    NSString *_formattedDuration;
    NSArray *_artists;
    unsigned int _positionsMoved;
    NSString *_direction;
    unsigned int _playsCount;
    unsigned int _influencersCount;
    NSMutableDictionary *_influencerToPlayCountMap;
}

@property(nonatomic) BOOL listenedToByCurrentUser; // @synthesize listenedToByCurrentUser=_listenedToByCurrentUser;
@property(retain, nonatomic) NSMutableDictionary *influencerToPlayCountMap; // @synthesize influencerToPlayCountMap=_influencerToPlayCountMap;
@property(nonatomic) unsigned int influencersCount; // @synthesize influencersCount=_influencersCount;
@property(nonatomic) unsigned int playsCount; // @synthesize playsCount=_playsCount;
@property(retain, nonatomic) NSString *direction; // @synthesize direction=_direction;
@property(nonatomic) unsigned int positionsMoved; // @synthesize positionsMoved=_positionsMoved;
@property(retain, nonatomic) NSArray *artists; // @synthesize artists=_artists;
@property(retain, nonatomic) NSString *formattedDuration; // @synthesize formattedDuration=_formattedDuration;
@property(nonatomic) BOOL unavailableForPlayback; // @synthesize unavailableForPlayback=_unavailableForPlayback;
@property(readonly, nonatomic) unsigned int position; // @synthesize position=_position;
@property(readonly, nonatomic) NSArray *influencers; // @synthesize influencers=_influencers;
@property(readonly, nonatomic) SPTSocialChartArtistData *artist; // @synthesize artist=_artist;
@property(readonly, nonatomic) SPTSocialChartAlbumData *album; // @synthesize album=_album;
@property(readonly, nonatomic) NSURL *uri; // @synthesize uri=_uri;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
- (void).cxx_destruct;
- (int)getPlayCountForUser:(id)arg1;
- (id)initWithDictionary:(id)arg1 allInfluencersDict:(id)arg2;

@end

