//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UpsellStandardViewController.h"

@class DeferredTrialController, NSString, UIButton;

@interface UpsellShuffleTrialMessageViewController : UpsellStandardViewController
{
    NSString *_secondaryButtonTitle;
    UIButton *_secondaryButton;
    DeferredTrialController *_deferredTrialController;
}

@property(retain, nonatomic) DeferredTrialController *deferredTrialController; // @synthesize deferredTrialController=_deferredTrialController;
@property(retain, nonatomic) UIButton *secondaryButton; // @synthesize secondaryButton=_secondaryButton;
@property(readonly, nonatomic) NSString *secondaryButtonTitle; // @synthesize secondaryButtonTitle=_secondaryButtonTitle;
- (void).cxx_destruct;
- (id)loadImageContainerViewBelowView:(id)arg1;
- (id)loadButtonContainerView;
- (id)initWithTitle:(id)arg1 withMessage:(id)arg2 withPrimaryButtonTitle:(id)arg3 withViewEventURI:(id)arg4 withLogCenter:(id)arg5;
- (id)initWithTitle:(id)arg1 withMessage:(id)arg2 withPrimaryButtonTitle:(id)arg3 withSecondaryButtonTitle:(id)arg4 withViewEventURI:(id)arg5 withLogCenter:(id)arg6 withDeferredTrialController:(id)arg7;

@end

