//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class Bouncer_UserList, NSString;

@interface Bouncer_SocialReaction : PBGeneratedMessage
{
    unsigned int hasId_:1;
    unsigned int hasLikes_:1;
    unsigned int hasStreams_:1;
    unsigned int hasReshares_:1;
    NSString *id;
    Bouncer_UserList *likes;
    Bouncer_UserList *streams;
    Bouncer_UserList *reshares;
}

+ (id)builderWithPrototype:(id)arg1;
+ (id)builder;
+ (id)parseFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
+ (id)parseFromCodedInputStream:(id)arg1;
+ (id)parseFromInputStream:(id)arg1 extensionRegistry:(id)arg2;
+ (id)parseFromInputStream:(id)arg1;
+ (id)parseFromData:(id)arg1 extensionRegistry:(id)arg2;
+ (id)parseFromData:(id)arg1;
+ (id)defaultInstance;
+ (void)initialize;
@property(retain) Bouncer_UserList *reshares; // @synthesize reshares;
@property(retain) Bouncer_UserList *streams; // @synthesize streams;
@property(retain) Bouncer_UserList *likes; // @synthesize likes;
@property(retain) NSString *id; // @synthesize id;
- (id)builder;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (_Bool)isInitialized;
- (id)defaultInstance;
- (id)init;
- (void)dealloc;
- (void)setHasReshares:(_Bool)arg1;
- (_Bool)hasReshares;
- (void)setHasStreams:(_Bool)arg1;
- (_Bool)hasStreams;
- (void)setHasLikes:(_Bool)arg1;
- (_Bool)hasLikes;
- (void)setHasId:(_Bool)arg1;
- (_Bool)hasId;

@end

