//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, NSURL;

@interface BrowsePlaylistItem : NSObject
{
    NSURL *_link;
    NSString *_imageId;
    NSString *_title;
    NSString *_playlistDescription;
    NSArray *_previews;
}

+ (id)dataFromItemDictionary:(id)arg1;
@property(retain, nonatomic) NSArray *previews; // @synthesize previews=_previews;
@property(retain, nonatomic) NSString *playlistDescription; // @synthesize playlistDescription=_playlistDescription;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *imageId; // @synthesize imageId=_imageId;
@property(retain, nonatomic) NSURL *link; // @synthesize link=_link;
- (void).cxx_destruct;

@end

