//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@interface BrowsePreviewItem : NSObject
{
    NSURL *_trackURL;
    NSString *_imageFileId;
    NSString *_previewFileId;
}

@property(readonly, nonatomic) NSString *previewFileId; // @synthesize previewFileId=_previewFileId;
@property(readonly, nonatomic) NSString *imageFileId; // @synthesize imageFileId=_imageFileId;
@property(readonly, nonatomic) NSURL *trackURL; // @synthesize trackURL=_trackURL;
- (void).cxx_destruct;
- (id)initWithTrackURL:(id)arg1 imageFileId:(id)arg2 previewFileId:(id)arg3;

@end

