//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ENAPI : NSObject
{
}

+ (id)signString:(id)arg1 andEncodeWithSecret:(id)arg2;
+ (id)calculateMD5DigestFromData:(id)arg1;
+ (id)encodeDictionaryAsQueryString:(id)arg1;
+ (id)parseJSONDataToDictionary:(id)arg1;
+ (id)encodeArrayAsJSON:(id)arg1;
+ (id)encodeDataAsJSON:(id)arg1;
+ (id)encodeObjectAsJSON:(id)arg1;

@end

