//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SettingsSection.h"

#import "SPSessionObserver.h"

@class NSString, SPKVObservation, SettingsButtonTableViewCell, SettingsSwitchTableViewCell, UIActivityIndicatorView;

@interface FacebookSettingsSection : SettingsSection <SPSessionObserver>
{
    SettingsSwitchTableViewCell *_facebookScrobblingCell;
    SettingsButtonTableViewCell *_enableFacebookCell;
    UIActivityIndicatorView *_facebookConnectingActivityIndicator;
    SPKVObservation *_facebookStateObservation;
}

@property(retain, nonatomic) SPKVObservation *facebookStateObservation; // @synthesize facebookStateObservation=_facebookStateObservation;
@property(retain, nonatomic) UIActivityIndicatorView *facebookConnectingActivityIndicator; // @synthesize facebookConnectingActivityIndicator=_facebookConnectingActivityIndicator;
@property(retain, nonatomic) SettingsButtonTableViewCell *enableFacebookCell; // @synthesize enableFacebookCell=_enableFacebookCell;
@property(retain, nonatomic) SettingsSwitchTableViewCell *facebookScrobblingCell; // @synthesize facebookScrobblingCell=_facebookScrobblingCell;
- (void).cxx_destruct;
- (void)session:(id)arg1 incognitoModeChangedByTimeout:(_Bool)arg2;
- (void)facebookStateChanged;
- (void)adjustActivityForIncognitoMode;
- (void)showActivityChanged:(id)arg1;
- (void)didSelectRow:(long long)arg1;
- (id)footerText;
- (id)headerText;
- (id)cellForRow:(long long)arg1;
- (long long)numberOfRows;
- (void)dealloc;
- (id)initWithSettingsViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

