//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IDEtchSession.h"

@interface IDEtchSession (Audio)
- (void)handlePlayerStateChanged:(long long)arg1 audioConnectionType:(int)arg2 audioPlayerState:(int)arg3;
- (void)handleMultimediaButtonEvent:(long long)arg1 audioButtonEvent:(int)arg2;
- (void)handleConnectionDenied:(long long)arg1 connectionType:(int)arg2;
- (void)handleConnectionDeactivated:(long long)arg1 connectionType:(int)arg2;
- (void)handleConnectionGranted:(long long)arg1 connectionType:(int)arg2;
- (_Bool)isValidPlayerState:(int)arg1;
- (_Bool)isValidConnectionType:(int)arg1;
- (SmartPointer_ae5953d7)avPlayerStateWithIDAudioPlayerState:(int)arg1;
- (SmartPointer_3c0c000b)avConnectionTypeWithIDAudioConnectionType:(int)arg1;
- (_Bool)audioService:(long long)arg1 confirmPlayerState:(int)arg2 forConnectionOfType:(int)arg3 error:(id *)arg4;
- (void)audioService:(long long)arg1 confirmPlayerState:(int)arg2 forConnectionOfType:(int)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)audioService:(long long)arg1 closeConnectionOfType:(int)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)audioService:(long long)arg1 requestConnectionOfType:(int)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (long long)registerAudioServiceWithApplicationIdentifier:(id)arg1 auxiliaryInput:(unsigned short)arg2 error:(id *)arg3;
@end

