//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface IDResourceData : NSObject
{
    int _type;
    NSData *_data;
}

+ (id)resourceDataWithType:(int)arg1 data:(id)arg2;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(nonatomic) int type; // @synthesize type=_type;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (id)typeName;
- (id)initWithType:(int)arg1 data:(id)arg2;

@end

