//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IDFlushProtocol.h"

@class IDApplication, IDModel, NSString;

@interface IDStatusBar : NSObject <IDFlushProtocol>
{
    _Bool _textDirty;
    _Bool _textIdDirty;
    NSString *_text;
    long long _textId;
    IDApplication *_application;
    IDModel *_textModel;
    long long _updateEvent;
}

@property _Bool textIdDirty; // @synthesize textIdDirty=_textIdDirty;
@property _Bool textDirty; // @synthesize textDirty=_textDirty;
@property long long updateEvent; // @synthesize updateEvent=_updateEvent;
@property(readonly) IDModel *textModel; // @synthesize textModel=_textModel;
@property IDApplication *application; // @synthesize application=_application;
@property(nonatomic) long long textId; // @synthesize textId=_textId;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (void)flush:(int)arg1;
- (int)priority;
- (void)setNeedsFlush;
- (id)initWithTextModel:(id)arg1 updateEvent:(long long)arg2;

@end

