//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UILabel;

@interface MessageBarView : UIView
{
    UILabel *_messageLabel;
    UIView *_backgroundView;
    long long _style;
}

@property(nonatomic) long long style; // @synthesize style=_style;
- (void).cxx_destruct;
- (void)setMessage:(id)arg1 animationDirection:(long long)arg2;
@property(retain, nonatomic) NSString *message;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

