//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SPTNowPlayingBarView.h"
#import "SPTThemableView.h"

@class CALayer, NSString, SPStepScrollView, SPTNowPlayingBackgroundView, SPTNowPlayingFadeMaskView, UIButton, UIButton<SPTNowPlayingBarPlayButton>;

@interface NowPlayingBarViewIPhone : UIView <SPTThemableView, SPTNowPlayingBarView>
{
    _Bool _enabled;
    _Bool _animating;
    id <SPTThemableViewLayoutDelegate> _layoutDelegate;
    UIView *_accessoryView;
    UIButton *_accessoryButton;
    SPTNowPlayingBackgroundView *_backgroundView;
    CALayer *_highlightLayer;
    SPTNowPlayingFadeMaskView *_fadeContentView;
    SPStepScrollView *_stepScrollView;
    UIButton<SPTNowPlayingBarPlayButton> *_playPauseButton;
    UIView *_enabledView;
}

@property(nonatomic) _Bool animating; // @synthesize animating=_animating;
@property(retain, nonatomic) UIView *enabledView; // @synthesize enabledView=_enabledView;
@property(retain, nonatomic) UIButton<SPTNowPlayingBarPlayButton> *playPauseButton; // @synthesize playPauseButton=_playPauseButton;
@property(retain, nonatomic) SPStepScrollView *stepScrollView; // @synthesize stepScrollView=_stepScrollView;
@property(retain, nonatomic) SPTNowPlayingFadeMaskView *fadeContentView; // @synthesize fadeContentView=_fadeContentView;
@property(retain, nonatomic) CALayer *highlightLayer; // @synthesize highlightLayer=_highlightLayer;
@property(retain, nonatomic) SPTNowPlayingBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIButton *accessoryButton; // @synthesize accessoryButton=_accessoryButton;
@property(retain, nonatomic) UIView *accessoryView; // @synthesize accessoryView=_accessoryView;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) __weak id <SPTThemableViewLayoutDelegate> layoutDelegate; // @synthesize layoutDelegate=_layoutDelegate;
- (void).cxx_destruct;
- (void)applyThemeLayout;
- (void)setAccessoryView:(id)arg1 animated:(_Bool)arg2;
- (void)replaceAccessoryView:(id)arg1 forceLayout:(_Bool)arg2;
- (id)currentTrackPageView;
- (void)setEnabled:(_Bool)arg1 animated:(_Bool)arg2;
- (void)forceLayout;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

