//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (Etch)
+ (id)dataWithEtchNativeByteArray:(SmartPointer_4c5e170f)arg1;
- (SmartPointer_65720f25)etchObject;
- (SmartPointer_4c5e170f)etchNativeByteArray;
- (id)MD5;
- (id)initWithEtchNativeByteArray:(SmartPointer_4c5e170f)arg1;
@end

