//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURL.h"

@interface NSURL (Podcast)
@property(readonly, nonatomic) _Bool spt_isVideoShowsHubViewURI;
@property(readonly, nonatomic) _Bool spt_isAudioShowsHubViewURI;
@property(readonly, nonatomic) _Bool spt_isShowsHubRootViewURI;
@property(readonly, nonatomic, getter=spt_isEpisodesCollectionURL) _Bool spt_episodesCollectionURL;
- (_Bool)isPodcastUnplayedEpisodesCollectionURL;
- (_Bool)isPodcastOfflineEpisodesCollectionURL;
- (_Bool)isPodcastCollectionURL;
- (_Bool)isPodcastURLComponents;
- (_Bool)isLegacyPodcastURLComponents;
- (_Bool)isPodcastEpisodeURLComponents;
- (_Bool)isLegacyPodcastEpisodeURLComponents;
- (id)podcastEpisodeID;
- (id)podcastID;
- (_Bool)isPodcastEpisodeURL;
- (_Bool)isPodcastURL;
@end

