//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTBaseViewModelDelegate.h"

@class FollowData, NSError, NSNumber, ProfileViewModel, SPTPlayerState;

@protocol ProfileViewModelDelegate <SPTBaseViewModelDelegate>
- (void)viewModel:(ProfileViewModel *)arg1 didUpdateFollowData:(FollowData *)arg2;

@optional
- (void)viewModel:(ProfileViewModel *)arg1 updateInviteCountDidFailWithError:(NSError *)arg2;
- (void)viewModel:(ProfileViewModel *)arg1 didUpdateInviteCount:(NSNumber *)arg2;
- (void)viewModel:(ProfileViewModel *)arg1 playerStateDidChange:(SPTPlayerState *)arg2;
- (void)viewModel:(ProfileViewModel *)arg1 followUpdateDidFailWithError:(NSError *)arg2;
@end

