//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RecommendationsFeature.h"
#import "SPTFeature.h"

@class NSString, SPTAllocationContext, SPTDiscoverABBAFeatureFlagManager, SPTDiscoverFeatureManager, SPTDiscoverViewController;

@interface RecommendationsFeatureImplementation : NSObject <SPTFeature, RecommendationsFeature>
{
    id <BaseFeature> _base;
    id <SettingsFeature> _settings;
    id <SPTPlayerFeature> _player;
    id <SPTAudioTouchFeature> _audioTouch;
    id <SPTAbbaFeature> _abba;
    id <SPTLocalSettings> _localSettings;
    SPTDiscoverABBAFeatureFlagManager *_featureFlagManager;
    SPTDiscoverFeatureManager *_featureManager;
    SPTDiscoverViewController *_groupedDiscoverVC;
}

+ (id)featureDependencies;
+ (id)featureVersion;
+ (id)featureIdentifier;
@property(retain, nonatomic) SPTDiscoverViewController *groupedDiscoverVC; // @synthesize groupedDiscoverVC=_groupedDiscoverVC;
@property(retain, nonatomic) SPTDiscoverFeatureManager *featureManager; // @synthesize featureManager=_featureManager;
@property(retain, nonatomic) SPTDiscoverABBAFeatureFlagManager *featureFlagManager; // @synthesize featureFlagManager=_featureFlagManager;
@property(retain, nonatomic) id <SPTLocalSettings> localSettings; // @synthesize localSettings=_localSettings;
@property(nonatomic) __weak id <SPTAbbaFeature> abba; // @synthesize abba=_abba;
@property(nonatomic) __weak id <SPTAudioTouchFeature> audioTouch; // @synthesize audioTouch=_audioTouch;
@property(nonatomic) __weak id <SPTPlayerFeature> player; // @synthesize player=_player;
@property(nonatomic) __weak id <SettingsFeature> settings; // @synthesize settings=_settings;
@property(nonatomic) __weak id <BaseFeature> base; // @synthesize base=_base;
- (void).cxx_destruct;
- (id)createViewLogger:(id)arg1;
- (id)provideFeatureManager;
- (id)provideDiscoverVC:(id)arg1;
- (id)provideDiscoverMenuItemVC:(id)arg1;
- (void)setupFeatureManager;
- (void)unload;
- (void)load;
- (void)configureWithFeatures:(id)arg1;

// Remaining properties
@property(retain, nonatomic) SPTAllocationContext *allocationContext;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

