//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSIndexPath, NSString, SPTCollectionViewCell, SPTSearchEntity, SearchViewModel, UICollectionView, UIView;

@protocol SearchViewModelDelegate <NSObject>
- (NSString *)provideCurrentCatalogForSearchViewModel:(SearchViewModel *)arg1;
- (NSIndexPath *)searchViewModel:(SearchViewModel *)arg1 indexPathForCell:(UIView *)arg2;
- (void)searchViewModel:(SearchViewModel *)arg1 didUpdateWithError:(NSError *)arg2;

@optional
- (void)searchViewModel:(SearchViewModel *)arg1 contextMenuButtonTappedInCellAtIndexPath:(NSIndexPath *)arg2;
- (void)searchViewModel:(id)arg1 didPrepareCell:(SPTCollectionViewCell *)arg2 forCollectionView:(UICollectionView *)arg3 model:(SPTSearchEntity *)arg4 atIndexPath:(NSIndexPath *)arg5;
@end

