//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProfileBaseVC.h"

#import "SPObjectRepresentation.h"
#import "SPTImageLoaderDelegate.h"
#import "SPTThemableViewLayoutDelegate.h"
#import "SocialRelationsViewModelDelegate.h"

@class NSString;

@interface SocialRelationsVC : ProfileBaseVC <SocialRelationsViewModelDelegate, SPTImageLoaderDelegate, SPObjectRepresentation, SPTThemableViewLayoutDelegate>
{
    id <SPTImageLoader> _imageLoader;
}

@property(retain, nonatomic) id <SPTImageLoader> imageLoader; // @synthesize imageLoader=_imageLoader;
- (void).cxx_destruct;
- (void)themableViewWillUpdateLayout:(id)arg1;
- (void)configureCell:(id)arg1 socialRelation:(id)arg2 atIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewModel:(id)arg1 didUpdateSocialRelationsEntity:(id)arg2 index:(long long)arg3;
- (void)viewModelDidFinishAllRequests:(id)arg1;
- (void)imageLoader:(id)arg1 didFailToLoadImageForURL:(id)arg2 error:(id)arg3 context:(id)arg4;
- (void)imageLoader:(id)arg1 didLoadImage:(id)arg2 forURL:(id)arg3 loadTime:(double)arg4 context:(id)arg5;
- (id)URI;
- (void)followButtonTapped:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setupTableView;
- (void)viewDidLoad;
- (id)initWithViewModel:(id)arg1 viewLogger:(id)arg2 logger:(id)arg3 style:(long long)arg4 feature:(id)arg5 share:(id)arg6 followFeature:(id)arg7 metaViewController:(id)arg8 imageLoaderFactory:(id)arg9;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

