//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface SPPictureGroup : NSObject
{
    NSArray *_pictures;
}

@property(retain, nonatomic) NSArray *pictures; // @synthesize pictures=_pictures;
- (void).cxx_destruct;
- (id)pictureForPictureSize:(BOOL)arg1;
- (id)initWithPictureGroup:(struct PictureGroup)arg1;

@end

