//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SPPlaylist;

@interface SPPlaylistCallbacksHolder : NSObject
{
    struct SPPlaylistCallbacks *_callbacks;
    SPPlaylist *_playlist;
}

@property(nonatomic) SPPlaylist *playlist; // @synthesize playlist=_playlist;
@property(readonly, nonatomic) struct SPPlaylistCallbacks *callbacks; // @synthesize callbacks=_callbacks;
- (void)dealloc;
- (id)initWithObjc:(id)arg1;

@end

