//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, SPTGestureSynchronizer, UIPanGestureRecognizer, UITapGestureRecognizer;

@interface SPSidebarContainerView : UIView <UIGestureRecognizerDelegate>
{
    double _touchOffset;
    UIView *_containerView;
    int _state;
    int _animationType;
    UIView *_backgroundView;
    UIView *_foregroundView;
    double _backgroundViewExtraHeight;
    UIPanGestureRecognizer *_panGestureRecognizer;
    id <SPSidebarContainerViewDelegate> _delegate;
    UITapGestureRecognizer *_tapGestureRecognizer;
    SPTGestureSynchronizer *_gestureSynchronizer;
}

@property(retain, nonatomic) SPTGestureSynchronizer *gestureSynchronizer; // @synthesize gestureSynchronizer=_gestureSynchronizer;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(nonatomic) __weak id <SPSidebarContainerViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIPanGestureRecognizer *panGestureRecognizer; // @synthesize panGestureRecognizer=_panGestureRecognizer;
@property(nonatomic) int animationType; // @synthesize animationType=_animationType;
@property(nonatomic) double backgroundViewExtraHeight; // @synthesize backgroundViewExtraHeight=_backgroundViewExtraHeight;
@property(retain, nonatomic) UIView *foregroundView; // @synthesize foregroundView=_foregroundView;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) int state; // @synthesize state=_state;
- (void).cxx_destruct;
- (int)stateForLocation:(struct CGPoint)arg1 velocity:(struct CGPoint)arg2;
- (void)tapWithGestureRecognizer:(id)arg1;
- (void)panWithGestureRecognizer:(id)arg1;
- (_Bool)shouldCaptureAngle:(double)arg1 velocity:(double)arg2 inCaptureAngle:(double)arg3;
- (double)captureAngleForPanGestureRecognizer:(id)arg1;
- (void)getVelocity:(double *)arg1 angle:(double *)arg2 forPanGestureRecognizer:(id)arg3;
- (_Bool)subviewForcingEdgeSwipeGestureWithGestureRecognizer:(id)arg1;
- (_Bool)subviewInterruptingSidebarRevealGestureWithGestureRecognizer:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (void)layoutSubviewsAtOffset:(double)arg1;
- (void)postDraggedToChangeStateNotification;
- (void)postTappedToChangeStateNotification;
- (void)setState:(int)arg1 velocity:(double)arg2;
- (void)setState:(int)arg1 animated:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

