//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer;

@interface SPTAdsPrerollRequestScheduler : NSObject
{
    id <SPTAdsPrerollRequestSchedulerDelegate> _delegate;
    NSTimer *_requestTimer;
    unsigned long long _retryCount;
}

@property(nonatomic) unsigned long long retryCount; // @synthesize retryCount=_retryCount;
@property(retain, nonatomic) NSTimer *requestTimer; // @synthesize requestTimer=_requestTimer;
@property(nonatomic) __weak id <SPTAdsPrerollRequestSchedulerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)advanceScheduler:(double)arg1;
- (void)scheduleFutureRequest:(double)arg1;
- (void)scheduleRetryRequest;
- (void)resetScheduler;
- (id)init;

@end

