//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTAccountViewModel.h"

#import "SPTAccountProductInformationObserver.h"
#import "SPTProductStateObserver.h"

@class NSString, SPKVObservation, SPTAccountABFlags, SPTAccountDeferredTrialController, SPTAccountFeatureLogging;

@interface SPTAccountSettingsViewModel : SPTAccountViewModel <SPTProductStateObserver, SPTAccountProductInformationObserver>
{
    _Bool _shouldShowSubscriptionStateLoadingIndicator;
    _Bool _shouldShowGetPremiumError;
    _Bool _trialAvailable;
    _Bool _inAppPurchaseAvailable;
    _Bool _inAppPurchaseInProgress;
    _Bool _requestingPremiumActivation;
    NSString *_title;
    NSString *_accessoryTitle;
    NSString *_subscriptionTypeTitle;
    NSString *_getPremiumErrorTitle;
    NSString *_getPremiumErrorMessage;
    NSString *_getPremiumErrorDimissButtonTitle;
    id <SPTAccountSettingsViewModelDelegate> _delegate;
    id <InAppPurchaseController> _inAppPurchaseController;
    SPTAccountDeferredTrialController *_deferredTrialController;
    id <SPTProductState> _productState;
    id <SPTAccountProductInformationController> _productInformationController;
    SPKVObservation *_trialAvailibilityObservation;
    SPKVObservation *_startTrialInProgressObservation;
    SPTAccountFeatureLogging *_accountFeatureLogging;
    SPTAccountABFlags *_abFlags;
}

+ (id)keyPathsForValuesAffectingShouldShowGetPremiumAction;
+ (id)keyPathsForValuesAffectingCanGetPremium;
@property(retain, nonatomic) SPTAccountABFlags *abFlags; // @synthesize abFlags=_abFlags;
@property(retain, nonatomic) SPTAccountFeatureLogging *accountFeatureLogging; // @synthesize accountFeatureLogging=_accountFeatureLogging;
@property(retain, nonatomic) SPKVObservation *startTrialInProgressObservation; // @synthesize startTrialInProgressObservation=_startTrialInProgressObservation;
@property(retain, nonatomic) SPKVObservation *trialAvailibilityObservation; // @synthesize trialAvailibilityObservation=_trialAvailibilityObservation;
@property(nonatomic, getter=isRequestingPremiumActivation) _Bool requestingPremiumActivation; // @synthesize requestingPremiumActivation=_requestingPremiumActivation;
@property(nonatomic, getter=isInAppPurchaseInProgress) _Bool inAppPurchaseInProgress; // @synthesize inAppPurchaseInProgress=_inAppPurchaseInProgress;
@property(nonatomic, getter=isInAppPurchaseAvailable) _Bool inAppPurchaseAvailable; // @synthesize inAppPurchaseAvailable=_inAppPurchaseAvailable;
@property(nonatomic, getter=isTrialAvailable) _Bool trialAvailable; // @synthesize trialAvailable=_trialAvailable;
@property(readonly, nonatomic) id <SPTAccountProductInformationController> productInformationController; // @synthesize productInformationController=_productInformationController;
@property(readonly, nonatomic) id <SPTProductState> productState; // @synthesize productState=_productState;
@property(readonly, nonatomic) SPTAccountDeferredTrialController *deferredTrialController; // @synthesize deferredTrialController=_deferredTrialController;
@property(readonly, nonatomic) id <InAppPurchaseController> inAppPurchaseController; // @synthesize inAppPurchaseController=_inAppPurchaseController;
@property(nonatomic) __weak id <SPTAccountSettingsViewModelDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *getPremiumErrorDimissButtonTitle; // @synthesize getPremiumErrorDimissButtonTitle=_getPremiumErrorDimissButtonTitle;
@property(copy, nonatomic) NSString *getPremiumErrorMessage; // @synthesize getPremiumErrorMessage=_getPremiumErrorMessage;
@property(copy, nonatomic) NSString *getPremiumErrorTitle; // @synthesize getPremiumErrorTitle=_getPremiumErrorTitle;
@property(nonatomic) _Bool shouldShowGetPremiumError; // @synthesize shouldShowGetPremiumError=_shouldShowGetPremiumError;
@property(nonatomic) _Bool shouldShowSubscriptionStateLoadingIndicator; // @synthesize shouldShowSubscriptionStateLoadingIndicator=_shouldShowSubscriptionStateLoadingIndicator;
@property(copy, nonatomic) NSString *subscriptionTypeTitle; // @synthesize subscriptionTypeTitle=_subscriptionTypeTitle;
@property(copy, nonatomic) NSString *accessoryTitle; // @synthesize accessoryTitle=_accessoryTitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)currentProductDidChangeForProductInformationController:(id)arg1;
- (void)productState:(id)arg1 stateDidChange:(id)arg2;
- (void)dismissGetPremiumError;
- (void)handleInAppPurchaseControllerError:(id)arg1;
- (void)handleStoreKitError:(id)arg1;
- (void)handleGetPremiumError:(id)arg1;
- (void)updateRequestingPremiumActivation;
- (void)buyPremiumViaInAppPurchase;
- (void)activateDeferredTrial;
- (void)getPremium;
- (void)showInterstitialView;
@property(readonly, nonatomic) _Bool shouldShowGetPremiumAction;
@property(readonly, nonatomic) _Bool canGetPremium;
- (long long)daysLeftOfProductWithExpiryDate:(id)arg1;
- (id)productExpiryDateForProductState:(id)arg1;
- (id)accessoryTitleForProduct:(long long)arg1 daysLeftOfProduct:(long long)arg2;
- (id)accessoryTitleForProduct:(long long)arg1 productState:(id)arg2;
- (id)titleForProduct:(long long)arg1;
- (void)updateFromProductState;
- (void)handleStartTrialInProgressChange;
- (void)triggerInAppPurchaseAvailabilityCheck;
- (void)viewModelDidBecomeInactive;
- (void)viewModelDidBecomeActive;
- (void)dealloc;
- (id)initWithProductState:(id)arg1 productInformationController:(id)arg2 inAppPurchaseController:(id)arg3 deferredTrialController:(id)arg4 accountFeatureLogging:(id)arg5 accountABFlags:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

