//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTBaseViewModel.h"

@class SPTActivityEntityData;

@interface SPTActivityEntityViewModel : SPTBaseViewModel
{
    SPTActivityEntityData *_data;
}

@property(readonly, nonatomic) SPTActivityEntityData *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (id)parseResponse:(id)arg1 requestKey:(id)arg2 error:(id *)arg3;
- (id)initWithEntityData:(id)arg1 offlineModeState:(id)arg2 dataLoader:(id)arg3;

@end

