//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SPTActivityEntityData, SPTActivityEntityFeedbackView, SPTActivityEntityHeadlineView, SPTTableViewCell, UIImage, UILabel, UITapGestureRecognizer;

@interface SPTActivityEntityView : UIView
{
    _Bool _usesContextMenuButton;
    _Bool _disabled;
    _Bool _hasFeedbackView;
    id <SPTActivityEntityViewDelegate> _delegate;
    SPTActivityEntityData *_entityData;
    SPTActivityEntityHeadlineView *_headlineView;
    UILabel *_summaryLabel;
    UIView *_aboveItemSeparatorView;
    SPTTableViewCell *_itemView;
    UIView *_itemPressedStateView;
    SPTActivityEntityFeedbackView *_feedbackView;
    UITapGestureRecognizer *_tap;
    UIImage *_backgroundImage;
    unsigned long long _itemType;
}

+ (double)heightForSummaryText:(id)arg1;
@property(nonatomic) unsigned long long itemType; // @synthesize itemType=_itemType;
@property(nonatomic) _Bool hasFeedbackView; // @synthesize hasFeedbackView=_hasFeedbackView;
@property(retain, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(retain, nonatomic) UITapGestureRecognizer *tap; // @synthesize tap=_tap;
@property(retain, nonatomic) SPTActivityEntityFeedbackView *feedbackView; // @synthesize feedbackView=_feedbackView;
@property(retain, nonatomic) UIView *itemPressedStateView; // @synthesize itemPressedStateView=_itemPressedStateView;
@property(retain, nonatomic) SPTTableViewCell *itemView; // @synthesize itemView=_itemView;
@property(retain, nonatomic) UIView *aboveItemSeparatorView; // @synthesize aboveItemSeparatorView=_aboveItemSeparatorView;
@property(retain, nonatomic) UILabel *summaryLabel; // @synthesize summaryLabel=_summaryLabel;
@property(retain, nonatomic) SPTActivityEntityHeadlineView *headlineView; // @synthesize headlineView=_headlineView;
@property(nonatomic, getter=isDisabled) _Bool disabled; // @synthesize disabled=_disabled;
@property(nonatomic) _Bool usesContextMenuButton; // @synthesize usesContextMenuButton=_usesContextMenuButton;
@property(nonatomic) __weak SPTActivityEntityData *entityData; // @synthesize entityData=_entityData;
@property(retain, nonatomic) id <SPTActivityEntityViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)tappedViewAt:(struct CGPoint)arg1;
- (void)didTap:(id)arg1;
- (_Bool)shouldIgnoreTouchEventOnView:(id)arg1;
- (void)didTapContextMenuButton;
- (void)setPlaying:(_Bool)arg1;
- (void)setNumberOfReplays:(long long)arg1;
- (void)setItemSubtitle:(id)arg1;
- (void)setItemTitle:(id)arg1;
- (void)setImage:(id)arg1 animated:(_Bool)arg2;
- (void)setSummary:(id)arg1;
- (void)setTimeString:(id)arg1;
- (void)setSharerName:(id)arg1;
- (void)setAvatarImage:(id)arg1;
- (id)replaysPopoverPresentationView;
- (id)audioTouchItemView;
- (struct CGSize)itemImageViewSize;
- (struct CGSize)avatarImageViewSize;
- (void)setupDisclosureIndicator;
- (void)setupContextMenuButton;
- (void)applyThemeLayout;
- (void)addStyles;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubviews;
- (void)reset;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

