//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPTAdCosmosSettingsController : NSObject
{
    id <SPTResolver> _resolver;
}

@property(nonatomic) __weak id <SPTResolver> resolver; // @synthesize resolver=_resolver;
- (void).cxx_destruct;
- (void)patch:(id)arg1 path:(id)arg2 value:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)setAdProductTargetingEnableMidroll:(_Bool)arg1 enableXapp:(_Bool)arg2;
- (void)setLimitAdTracking;
- (void)setAppleIDFATargeting;
- (id)initWithResolver:(id)arg1;

@end

