//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SPTBrowseABBAFeatureFlagManager;

@interface SPTBrowseABTestsManager : NSObject
{
    _Bool _startPageEnabled;
    id <SPTLocalSettings> _localSettings;
    id <SPTProductState> _productState;
    SPTBrowseABBAFeatureFlagManager *_ABBAFeatureFlagManager;
}

@property(retain, nonatomic) SPTBrowseABBAFeatureFlagManager *ABBAFeatureFlagManager; // @synthesize ABBAFeatureFlagManager=_ABBAFeatureFlagManager;
@property(nonatomic) _Bool startPageEnabled; // @synthesize startPageEnabled=_startPageEnabled;
@property(nonatomic) __weak id <SPTProductState> productState; // @synthesize productState=_productState;
@property(nonatomic) __weak id <SPTLocalSettings> localSettings; // @synthesize localSettings=_localSettings;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long highlightsUserPolicy;
@property(readonly, nonatomic) _Bool isFeaturedPlaylistVisible;
@property(readonly, nonatomic) _Bool isSpokenWordEnabled;
@property(readonly, nonatomic) _Bool isRunningGenreEnabled;
@property(readonly, nonatomic) _Bool isMarbleEnabled;
@property(readonly, nonatomic) _Bool isCeramicHomepageEnabled;
@property(readonly, nonatomic, getter=isChartsShortcutEnabled) _Bool chartsShortcutEnabled;
- (id)initWithLocalSettings:(id)arg1 productState:(id)arg2 ABBAFeatureFlagManager:(id)arg3 startPageEnabled:(_Bool)arg4;

@end

