//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AlertControllerDelegate.h"
#import "RAPIEntertainmentAppLinkDelegate.h"

@class NSString, RAPIEntertainmentAppLink, SPTBMWLoggedInSession;

@interface SPTBMWSession : NSObject <RAPIEntertainmentAppLinkDelegate, AlertControllerDelegate>
{
    _Bool _appLinkIsConnected;
    _Bool _userIsLoggedIn;
    RAPIEntertainmentAppLink *_bmwAppLink;
    id <ExternalContentProvider> _externalContentFeature;
    id <SPTExternalContentProvider> _externalContent;
    SPTBMWLoggedInSession *_loggedInSession;
    NSString *_modelNameForAnalytics;
    long long _connectedAccessoryId;
}

+ (id)sharedSession;
@property(nonatomic) long long connectedAccessoryId; // @synthesize connectedAccessoryId=_connectedAccessoryId;
@property(copy, nonatomic) NSString *modelNameForAnalytics; // @synthesize modelNameForAnalytics=_modelNameForAnalytics;
@property(nonatomic) _Bool userIsLoggedIn; // @synthesize userIsLoggedIn=_userIsLoggedIn;
@property(nonatomic) _Bool appLinkIsConnected; // @synthesize appLinkIsConnected=_appLinkIsConnected;
@property(retain, nonatomic) SPTBMWLoggedInSession *loggedInSession; // @synthesize loggedInSession=_loggedInSession;
@property(retain, nonatomic) id <SPTExternalContentProvider> externalContent; // @synthesize externalContent=_externalContent;
@property(retain, nonatomic) id <ExternalContentProvider> externalContentFeature; // @synthesize externalContentFeature=_externalContentFeature;
@property(retain, nonatomic) RAPIEntertainmentAppLink *bmwAppLink; // @synthesize bmwAppLink=_bmwAppLink;
- (void).cxx_destruct;
- (_Bool)alertControllerShouldDisplayAlert:(id)arg1;
- (void)onTextLog:(id)arg1 source:(long long)arg2;
- (void)onDisconnectedFromCar;
- (void)onConnectedToCar:(id)arg1;
- (void)onScreenChangedFrom:(long long)arg1 to:(long long)arg2 withClickedItemIndex:(long long)arg3 andGroupIndex:(long long)arg4;
- (id)getTitleForScreen:(long long)arg1;
- (id)getLoadingLabelForScreen:(long long)arg1;
- (void)onCarLanguageChanged:(id)arg1;
- (_Bool)isMasterOptionButtonCheckedForScreen:(long long)arg1;
- (id)getMoreLabelForGroup:(long long)arg1 forScreen:(long long)arg2;
- (void)onSearchStringChanged:(id)arg1 forSearchScreen:(long long)arg2;
- (long long)getTargetScreenForRow:(long long)arg1 forGroup:(long long)arg2 forScreen:(long long)arg3;
- (id)getImageForRow:(long long)arg1 forGroup:(long long)arg2 withPreferredSize:(struct CGSize)arg3 forScreen:(long long)arg4 hasAlphaChannel:(_Bool *)arg5;
- (id)getStringForLine:(long long)arg1 forRow:(long long)arg2 forGroup:(long long)arg3 forScreen:(long long)arg4;
- (long long)getItemCountForGroup:(long long)arg1 forScreen:(long long)arg2;
- (long long)getGroupCountForScreen:(long long)arg1;
- (id)getGroupLabelForGroup:(long long)arg1 forScreen:(long long)arg2;
- (_Bool)canProvideDataImmediately:(long long)arg1;
- (long long)getTotalTrackTime;
- (long long)getCurrentTrackTime;
- (float)getCurrentTrackProgress;
- (void)onEndSeek;
- (void)onBeginSeekForward;
- (void)onBeginSeekBackward;
- (void)onSkipPrev;
- (void)onSkipNext;
- (void)onPausePlayback;
- (void)onStartPlayback;
- (void)handleOnItemClicked:(id)arg1;
- (void)applyDisabledUI;
- (void)handleLogoutOrDisconnect;
- (void)fetchExternalContentAndSwitchToLoggedInSessionIfNeeded;
- (void)logout;
- (void)loginWithExternalContentFeature:(id)arg1;
- (void)handleBMWURLHandledNotification:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

