//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTBrowseStickyHeaderViewController.h"

#import "SPTBrowseHeaderActionProtocol.h"
#import "SPTScrollPageViewControllerDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSArray, NSString, SPTBrowseGenreRollupHeaderViewController, SPTScrollPageViewController;

@interface SPTBrowseGenreRollupViewController : SPTBrowseStickyHeaderViewController <SPTBrowseHeaderActionProtocol, SPTScrollPageViewControllerDelegate, UIScrollViewDelegate>
{
    NSArray *_spaces;
}

@property(retain, nonatomic) NSArray *spaces; // @synthesize spaces=_spaces;
- (void).cxx_destruct;
- (void)scrollPageViewController:(id)arg1 didUpdateContentOffset:(struct CGPoint)arg2;
- (void)scrollPageViewController:(id)arg1 didScrollHorizontallyToOffset:(struct CGPoint)arg2;
- (void)scrollPageViewController:(id)arg1 didTransitionToPageIndex:(long long)arg2;
- (void)headerViewControllerDidSelectHeader:(id)arg1;
- (void)headerViewController:(id)arg1 didSelectMainControl:(id)arg2 withValue:(long long)arg3;
- (id)URI;
- (void)setupHeader;
- (void)setupContentViewController;
- (void)initiateSpaces;
- (id)initWithGenreItem:(id)arg1 imageLoaderFactory:(id)arg2 productState:(id)arg3 session:(id)arg4 metaViewController:(id)arg5 theme:(id)arg6 audioDriverController:(id)arg7 options:(long long)arg8 offlineInfoViewFactory:(id)arg9;

// Remaining properties
@property(retain, nonatomic) SPTScrollPageViewController *contentViewController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) SPTBrowseGenreRollupHeaderViewController *headerViewController;
@property(readonly) Class superclass;

@end

