//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPTBuddyListEntityRankChange : NSObject
{
    unsigned long long _changeType;
    unsigned long long _fromIndex;
    unsigned long long _toIndex;
}

@property(readonly, nonatomic) unsigned long long toIndex; // @synthesize toIndex=_toIndex;
@property(readonly, nonatomic) unsigned long long fromIndex; // @synthesize fromIndex=_fromIndex;
@property(readonly, nonatomic) unsigned long long changeType; // @synthesize changeType=_changeType;
- (id)initWithMovedFromIndex:(unsigned long long)arg1 toIndex:(unsigned long long)arg2;
- (id)initWithRemovedFromIndex:(unsigned long long)arg1;
- (id)initWithAddedToIndex:(unsigned long long)arg1;
- (id)initWithChangeType:(unsigned long long)arg1;

@end

