//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SPTBrowseRunningSlider;

@protocol SPTBrowseRunningSliderDelegate <NSObject>
- (void)browseRunningSliderDidStopSliding:(SPTBrowseRunningSlider *)arg1;

@optional
- (void)browseRunningSliderDidStartSliding:(SPTBrowseRunningSlider *)arg1;
- (void)browseRunningSlider:(SPTBrowseRunningSlider *)arg1 didSelectValue:(double)arg2;
@end

