//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTClientEventLogger.h"

@interface SPTClientEventLogger (Activity)
+ (id)dictionaryForUser:(id)arg1 atIndex:(long long)arg2;
+ (id)dictionaryForActivity:(id)arg1 atIndex:(long long)arg2;
- (void)logViewedReplayer:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)logTappedReplayer:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)logTimeToGetInitialResponseAndRenderView:(double)arg1;
- (void)logTimeToRenderViewAfterInitialResponse:(double)arg1;
- (void)logActivityEntityEvent:(int)arg1 forActivity:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)logScrolledToLoadOlderEntities:(unsigned long long)arg1 totalEntities:(unsigned long long)arg2;
- (void)logLoadedNewerStories:(unsigned long long)arg1 totalEntities:(unsigned long long)arg2;
- (void)logPulledToRefresh;
- (void)logNavigateToPeopleSuggestionsViaNavBarButton:(_Bool)arg1;
- (id)activitiesViewed;
@end

