//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIView;

@protocol SPTCeramicCollectionViewHeader <NSObject>
@property(retain, nonatomic) NSString *title;

@optional
+ (double)heightForDescriptionLabelWithText:(NSString *)arg1 expanded:(_Bool)arg2 viewWidth:(double)arg3;
@property(retain, nonatomic) UIView *accessoryView;
@property(copy, nonatomic) NSString *descriptionText;
@end

