//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTClientEventLogger.h"

@interface SPTClientEventLogger (FindFriends)
- (void)logHitConnectToFacebookButton;
- (void)logViewedFeaturedTabWithTotalCount:(unsigned long long)arg1 notFollowedCount:(unsigned long long)arg2;
- (void)logViewedFriendsTabWithTotalCount:(unsigned long long)arg1 notFollowedCount:(unsigned long long)arg2 isConnectedToFacebook:(_Bool)arg3;
- (void)logViewedFindFriends;
@end

