//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTCeramicCollectionViewDynamicLayout.h"

@interface SPTCeramicCollectionViewDynamicLayout (Factory)
+ (id)textOnlyLayoutForCollectionViewFrame:(struct CGRect)arg1 theme:(id)arg2 hasHeaderView:(_Bool)arg3 hasFooterView:(_Bool)arg4;
+ (id)layoutForBlockRenderType:(long long)arg1 headerDescriptionHeight:(double)arg2 frame:(struct CGRect)arg3 theme:(id)arg4;
@end

