//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPTCollectionFilterBarFactory : NSObject
{
    _Bool _isCollectionFilterBarAvailable;
}

@property(nonatomic) _Bool isCollectionFilterBarAvailable; // @synthesize isCollectionFilterBarAvailable=_isCollectionFilterBarAvailable;
- (id)filterBarForTableView:(id)arg1 targetViewController:(id)arg2;
- (id)initWithProductState:(id)arg1;

@end

