//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTCollectionObserver.h"
#import "SPTPlayerObserver.h"

@class NSString, NSTimer, SPPlaylist, SPSession, SPTEntityCancelationToken, SPTEntityService, SPTExternalPlaybackStatus;

@interface SPTExternalPlaybackControl : NSObject <SPTPlayerObserver, SPTCollectionObserver>
{
    id <SPTPlayer> _player;
    id <SPTAudioSessionController> _audioSessionController;
    SPTExternalPlaybackStatus *_currentPlaybackStatus;
    id <SPRadioManager> _radio;
    id <CollectionFeature> _collectionFeature;
    SPPlaylist *_starredPlaylist;
    SPSession *_session;
    NSTimer *_seekTimer;
    unsigned long long _seekDirection;
    SPTEntityCancelationToken *_artistTask;
    SPTEntityCancelationToken *_albumTask;
    id <SPTImageLoaderFactory> _imageLoaderFactory;
    SPTEntityService *_entityService;
}

@property(retain, nonatomic) SPTEntityService *entityService; // @synthesize entityService=_entityService;
@property(retain, nonatomic) id <SPTImageLoaderFactory> imageLoaderFactory; // @synthesize imageLoaderFactory=_imageLoaderFactory;
@property(retain, nonatomic) SPTEntityCancelationToken *albumTask; // @synthesize albumTask=_albumTask;
@property(retain, nonatomic) SPTEntityCancelationToken *artistTask; // @synthesize artistTask=_artistTask;
@property(nonatomic) unsigned long long seekDirection; // @synthesize seekDirection=_seekDirection;
@property(retain, nonatomic) NSTimer *seekTimer; // @synthesize seekTimer=_seekTimer;
@property(nonatomic) __weak SPSession *session; // @synthesize session=_session;
@property(retain, nonatomic) SPPlaylist *starredPlaylist; // @synthesize starredPlaylist=_starredPlaylist;
@property(retain, nonatomic) id <CollectionFeature> collectionFeature; // @synthesize collectionFeature=_collectionFeature;
@property(retain, nonatomic) id <SPRadioManager> radio; // @synthesize radio=_radio;
@property(retain, nonatomic) SPTExternalPlaybackStatus *currentPlaybackStatus; // @synthesize currentPlaybackStatus=_currentPlaybackStatus;
@property(retain, nonatomic) id <SPTAudioSessionController> audioSessionController; // @synthesize audioSessionController=_audioSessionController;
@property(retain, nonatomic) id <SPTPlayer> player; // @synthesize player=_player;
- (void).cxx_destruct;
- (_Bool)stateEqualIgnoringPosition:(id)arg1 toState:(id)arg2;
- (void)player:(id)arg1 stateDidChange:(id)arg2 force:(_Bool)arg3;
- (void)player:(id)arg1 stateDidChange:(id)arg2;
@property(readonly, nonatomic, getter=isYourLibraryFeatureEnabled) _Bool yourLibraryFeatureEnabled;
- (void)setSaved:(_Bool)arg1;
- (void)setupAsCollectionObserver;
- (void)removeAsCollectionObserver;
- (void)collectionDidChange:(id)arg1;
- (void)applySeek:(id)arg1;
- (void)stopSeeking;
- (void)beginSeekingInDirection:(unsigned long long)arg1;
- (void)thumb:(_Bool)arg1;
- (void)thumbDown;
- (void)thumbUp;
- (void)setTrackRepeated:(_Bool)arg1;
- (void)setRepeated:(_Bool)arg1;
- (void)setShuffled:(_Bool)arg1;
- (void)setPaused:(_Bool)arg1 finally:(CDUnknownBlockType)arg2;
- (void)setPaused:(_Bool)arg1;
- (id)doResume;
- (id)doPause;
- (void)performSkipNextCommand;
- (void)performSkipPreviousCommand;
- (void)fetchRelatedAlbumsFromCurrentTrack:(CDUnknownBlockType)arg1;
- (void)startRadioFromCurrentTrack;
- (void)playIndex:(unsigned long long)arg1 ofPlayerContext:(id)arg2 shufflePlay:(_Bool)arg3 withMetadata:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)decorateContext:(id)arg1 withMetadata:(id)arg2;
- (void)playIndex:(unsigned long long)arg1 ofItemWithURI:(id)arg2 shufflePlay:(_Bool)arg3 withMetadata:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)playIndex:(unsigned long long)arg1 ofItem:(id)arg2 shufflePlay:(_Bool)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (id)metadataForContext:(id)arg1 withItem:(id)arg2 andPlayIndex:(int)arg3;
- (void)playItem:(id)arg1 withParent:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)initWithRadioFeature:(id)arg1 collectionFeature:(id)arg2 player:(id)arg3 session:(id)arg4 audioSessionController:(id)arg5 imageLoaderFactory:(id)arg6 entityService:(id)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

