//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SPCredentials;

@interface SPTEventInfo : NSObject
{
    long long _type;
    long long _status;
    SPCredentials *_credentials;
    NSString *_connectionError;
    long long _socialEvent;
    long long _socialError;
    NSString *_socialDescription;
}

+ (id)eventInfoWithInfo:(struct EventInfo *)arg1;
@property(retain, nonatomic) NSString *socialDescription; // @synthesize socialDescription=_socialDescription;
@property(nonatomic) long long socialError; // @synthesize socialError=_socialError;
@property(nonatomic) long long socialEvent; // @synthesize socialEvent=_socialEvent;
@property(retain, nonatomic) NSString *connectionError; // @synthesize connectionError=_connectionError;
@property(retain, nonatomic) SPCredentials *credentials; // @synthesize credentials=_credentials;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)initWithInfo:(struct EventInfo *)arg1;

@end

