//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, SPTFindFriendsFeaturedProfilesViewModel;

@protocol SPTFindFriendsFeaturedProfilesViewModelDelegate <NSObject>
- (void)findFriendsFeaturedProfilesViewModel:(SPTFindFriendsFeaturedProfilesViewModel *)arg1 hasLoadedFeaturedProfilesWithSuccess:(_Bool)arg2 error:(NSError *)arg3;

@optional
- (void)findFriendsFeaturedProfilesViewModel:(SPTFindFriendsFeaturedProfilesViewModel *)arg1 didFailToUpdateFollowStateWithError:(NSError *)arg2;
- (void)findFriendsFeaturedProfilesViewModel:(SPTFindFriendsFeaturedProfilesViewModel *)arg1 didUpdateFollowStateForUserAtIndex:(unsigned long long)arg2;
- (void)findFriendsFeaturedProfilesViewModel:(SPTFindFriendsFeaturedProfilesViewModel *)arg1 isOffline:(_Bool)arg2;
- (void)findFriendsFeaturedProfilesViewModel:(SPTFindFriendsFeaturedProfilesViewModel *)arg1 isLoading:(_Bool)arg2;
@end

