//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SPTHubBlockTinkerbellData;

@interface SPTHubTinkerbellHandlerPresentationToken : NSObject
{
    id <SPTTinkerbellItemPresentationController> _presentationController;
    SPTHubBlockTinkerbellData *_data;
    unsigned long long _blockIndex;
}

@property(readonly, nonatomic) unsigned long long blockIndex; // @synthesize blockIndex=_blockIndex;
@property(readonly, nonatomic) SPTHubBlockTinkerbellData *data; // @synthesize data=_data;
@property(readonly, nonatomic) id <SPTTinkerbellItemPresentationController> presentationController; // @synthesize presentationController=_presentationController;
- (void).cxx_destruct;
- (id)initWithPresentationController:(id)arg1 data:(id)arg2 blockIndex:(unsigned long long)arg3;

@end

