//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTFeature.h"
#import "SPTHubFeature.h"

@class NSString, SPTAllocationContext, SPTHubRegistry;

@interface SPTHubFeatureImplementation : NSObject <SPTFeature, SPTHubFeature>
{
    id <SPTHubRegistrationToken> _musicHubRegistrationToken;
    id <BaseFeature> _baseFeature;
    id <SettingsFeature> _settingsFeature;
    id <SPTAudioTouchFeature> _audioTouchFeature;
    id <SPTMomentsFeature> _momentsFeature;
    id <SPTPodcastFeature> _podcastFeature;
    id <RadioFeature> _radioFeature;
    id <SPTTinkerbellFeature> _tinkerbellFeature;
    id <SPTOfflineLibraryFeature> _offlineLibraryFeature;
    SPTHubRegistry *_hubRegistry;
}

+ (id)featureDependencies;
+ (id)featureIdentifier;
@property(retain, nonatomic) SPTHubRegistry *hubRegistry; // @synthesize hubRegistry=_hubRegistry;
@property(nonatomic) __weak id <SPTOfflineLibraryFeature> offlineLibraryFeature; // @synthesize offlineLibraryFeature=_offlineLibraryFeature;
@property(nonatomic) __weak id <SPTTinkerbellFeature> tinkerbellFeature; // @synthesize tinkerbellFeature=_tinkerbellFeature;
@property(nonatomic) __weak id <RadioFeature> radioFeature; // @synthesize radioFeature=_radioFeature;
@property(nonatomic) __weak id <SPTPodcastFeature> podcastFeature; // @synthesize podcastFeature=_podcastFeature;
@property(nonatomic) __weak id <SPTMomentsFeature> momentsFeature; // @synthesize momentsFeature=_momentsFeature;
@property(nonatomic) __weak id <SPTAudioTouchFeature> audioTouchFeature; // @synthesize audioTouchFeature=_audioTouchFeature;
@property(nonatomic) __weak id <SettingsFeature> settingsFeature; // @synthesize settingsFeature=_settingsFeature;
@property(nonatomic) __weak id <BaseFeature> baseFeature; // @synthesize baseFeature=_baseFeature;
@property(retain, nonatomic) id <SPTHubRegistrationToken> musicHubRegistrationToken; // @synthesize musicHubRegistrationToken=_musicHubRegistrationToken;
- (void).cxx_destruct;
- (_Bool)hubWithDefaultIdentifierIsPartOfMomentsExperience:(unsigned long long)arg1;
- (id)createTinkerbellHandler;
- (id)createCeramicViewControllerWithViewModel:(id)arg1 hubTitle:(id)arg2;
- (id)createHubViewControllerWithViewURI:(id)arg1 contentProvider:(id)arg2 viewHandler:(id)arg3 hubTitle:(id)arg4;
- (_Bool)shouldEnableMomentsExperienceHubs;
- (id)provideHubViewControllerForViewURI:(id)arg1;
- (id)provideExternalDataLoaderFactoryForHubWithRegistrationToken:(id)arg1;
- (id)registerHubWithViewURI:(id)arg1 title:(id)arg2 icon:(unsigned long long)arg3 contentProviderFactory:(id)arg4 viewHandler:(id)arg5 externalDataRootEndpointPath:(id)arg6;
- (id)registerDefaultHubWithIdentifier:(unsigned long long)arg1 title:(id)arg2 icon:(unsigned long long)arg3 localContentProvider:(id)arg4 viewHandler:(id)arg5;
@property(readonly, nonatomic) _Bool removesRadioFromNavigation;
@property(readonly, nonatomic) _Bool enablesGenreFeature;
@property(readonly, nonatomic) _Bool disablesBrowseFeature;
- (void)unload;
- (void)load;
- (void)configureWithFeatures:(id)arg1;

// Remaining properties
@property(retain, nonatomic) SPTAllocationContext *allocationContext;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

