//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL, UIView;

@protocol SPTHubViewHandler <NSObject>
- (_Bool)handleHubHeaderButtonPressWithTargetURL:(NSURL *)arg1;
- (struct UIEdgeInsets)insetsForHubBlockAtIndex:(unsigned long long)arg1;
- (UIView *)metaDataPrefixViewForHubItemAtIndexPath:(struct SPTHubIndexPath)arg1 viewURI:(NSURL *)arg2;
- (UIView *)prefixViewForHubItemAtIndexPath:(struct SPTHubIndexPath)arg1;
@end

