//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTLegacyShareSheet.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "MFMessageComposeViewControllerDelegate.h"
#import "SPTThemableViewLayoutDelegate.h"

@class MFMailComposeViewController, MFMessageComposeViewController, NSString, NSURL, SectionHelper;

@interface SPTInvitationCodesShareSheet : SPTLegacyShareSheet <SPTThemableViewLayoutDelegate, MFMailComposeViewControllerDelegate, MFMessageComposeViewControllerDelegate>
{
    int _selectedShareMedium;
    NSString *_shareText;
    NSString *_code;
    NSURL *_url;
    SectionHelper *_sections;
    MFMailComposeViewController *_mail;
    MFMessageComposeViewController *_sms;
}

@property(retain, nonatomic) MFMessageComposeViewController *sms; // @synthesize sms=_sms;
@property(retain, nonatomic) MFMailComposeViewController *mail; // @synthesize mail=_mail;
@property(nonatomic) int selectedShareMedium; // @synthesize selectedShareMedium=_selectedShareMedium;
@property(retain, nonatomic) SectionHelper *sections; // @synthesize sections=_sections;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *code; // @synthesize code=_code;
@property(copy, nonatomic) NSString *shareText; // @synthesize shareText=_shareText;
- (void).cxx_destruct;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2;
- (void)delayedTableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)updateDataSource;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

