//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTLogCenter.h"

@interface SPTLogCenter (NowPlayingVideo)
- (void)logNowPlayingVideoPlayButtonTouchedUpInside;
- (void)logNowPlayingVideoDurationSliderValueChanged;
- (void)logNowPlayingVideoMinimizeButtonTouchedUpInside;
- (void)logNowPlayingVideoMaximizeButtonTouchedUpInside;
- (void)logNowPlayingVideoDurationSliderTouchedUpInside;
- (void)logNowPlayingVideoNextButtonTouchedUpInsideWithBehavior:(int)arg1;
- (void)logNowPlayingVideoPreviousButtonTouchedUpInsideWithBehavior:(int)arg1;
- (void)logNowPlayingVideoTouchedUpInside:(_Bool)arg1;
- (void)logNowPlayingVideoSkip15Back;
- (void)logNowPlayingVideoSkip15Forward;
- (void)logNowPlayingVideoRotatedPortrait;
- (void)logNowPlayingVideoRotatedLandscape;
@end

