//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTLogMessage.h"

@class NSString;

@interface SPTLogMessageAppStartupTimer1 : SPTLogMessage
{
    _Bool _isFirstValue;
    NSString *_timerStepNameValue;
    long long _msSinceEpochValue;
}

+ (id)messageWithTimerStepName:(id)arg1 isFirst:(_Bool)arg2 msSinceEpoch:(long long)arg3;
@property(nonatomic) long long msSinceEpochValue; // @synthesize msSinceEpochValue=_msSinceEpochValue;
@property(nonatomic) _Bool isFirstValue; // @synthesize isFirstValue=_isFirstValue;
@property(retain, nonatomic) NSString *timerStepNameValue; // @synthesize timerStepNameValue=_timerStepNameValue;
- (void).cxx_destruct;

@end

