//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "MFMessageComposeViewControllerDelegate.h"
#import "SPTContextMenuContentViewController.h"
#import "SPTImageLoaderDelegate.h"
#import "SPTLegacyPeopleChooserDelegate.h"
#import "SPTShareSheetProtocol.h"
#import "SPTThemableViewLayoutDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextViewDelegate.h"
#import "UIWebViewDelegate.h"

@class MFMailComposeViewController, MFMessageComposeViewController, NSArray, NSString, NSURL, SPTImageBlurView, SPTPopoverController, SPTTableView, SPTViewLogger, SectionHelper, UIImage, UIImageView, UILabel, UIView;

@interface SPTLegacyShareSheet : UIViewController <MFMailComposeViewControllerDelegate, UIWebViewDelegate, UITableViewDelegate, SPTLegacyPeopleChooserDelegate, MFMessageComposeViewControllerDelegate, UITextViewDelegate, SPTThemableViewLayoutDelegate, SPTImageLoaderDelegate, SPTShareSheetProtocol, SPTContextMenuContentViewController, UITableViewDataSource>
{
    UIImageView *imageView;
    UIView *header;
    _Bool _shouldShowPostToFeed;
    int _selectedShareMedium;
    id <SPTContextMenuContentViewControllerDelegate> contextMenuDelegate;
    SPTPopoverController *popover;
    id <SPTShareVCDelegate> _delegate;
    SPTTableView *_tableView;
    NSURL *_url;
    MFMailComposeViewController *_mail;
    MFMessageComposeViewController *_sms;
    NSArray *_links;
    NSString *_type;
    UILabel *_descriptionLabel;
    SPTImageBlurView *_blurView;
    UIImage *_image;
    SectionHelper *_sections;
    NSString *_itemDescription;
    NSArray *_users;
    NSURL *_imageLink;
    id <SPTImageLoader> _imageLoader;
    id <SPTShareFeature> _shareFeature;
    id <SPTImageLoaderFactory> _imageLoaderFactory;
    SPTViewLogger *_viewLogger;
    id <UITableViewDataSource><UITableViewDelegate> _additionalData;
}

@property(nonatomic) __weak id <UITableViewDataSource><UITableViewDelegate> additionalData; // @synthesize additionalData=_additionalData;
@property(retain, nonatomic) SPTViewLogger *viewLogger; // @synthesize viewLogger=_viewLogger;
@property(retain, nonatomic) id <SPTImageLoaderFactory> imageLoaderFactory; // @synthesize imageLoaderFactory=_imageLoaderFactory;
@property(nonatomic) __weak id <SPTShareFeature> shareFeature; // @synthesize shareFeature=_shareFeature;
@property(nonatomic) int selectedShareMedium; // @synthesize selectedShareMedium=_selectedShareMedium;
@property(retain, nonatomic) id <SPTImageLoader> imageLoader; // @synthesize imageLoader=_imageLoader;
@property(retain, nonatomic) NSURL *imageLink; // @synthesize imageLink=_imageLink;
@property(retain, nonatomic) NSArray *users; // @synthesize users=_users;
@property(retain, nonatomic) NSString *itemDescription; // @synthesize itemDescription=_itemDescription;
@property(retain, nonatomic) SectionHelper *sections; // @synthesize sections=_sections;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) SPTImageBlurView *blurView; // @synthesize blurView=_blurView;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSArray *links; // @synthesize links=_links;
@property(retain, nonatomic) MFMessageComposeViewController *sms; // @synthesize sms=_sms;
@property(retain, nonatomic) MFMailComposeViewController *mail; // @synthesize mail=_mail;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) SPTTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool shouldShowPostToFeed; // @synthesize shouldShowPostToFeed=_shouldShowPostToFeed;
@property(nonatomic) id <SPTShareVCDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SPTPopoverController *popover; // @synthesize popover;
@property(nonatomic) __weak id <SPTContextMenuContentViewControllerDelegate> contextMenuDelegate; // @synthesize contextMenuDelegate;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView;
- (void).cxx_destruct;
- (void)close;
- (void)showOnIPadWithPresentingView:(id)arg1 rect:(struct CGRect)arg2 arrowDirections:(unsigned long long)arg3;
- (void)showOnIPhone;
- (void)imageLoader:(id)arg1 didLoadImage:(id)arg2 forURL:(id)arg3 loadTime:(double)arg4 context:(id)arg5;
- (void)themableViewDidUpdateLayout:(id)arg1;
- (void)peopleChooser:(id)arg1 selectedUserWithFacebookId:(id)arg2;
- (void)peopleChooser:(id)arg1 selectedUsers:(id)arg2;
- (void)showWebViewForURL:(id)arg1 title:(id)arg2;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (id)imageToShow;
- (void)alertControllerDidClickSuccess;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)delayedTableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)additionalIndexPath:(id)arg1;
- (void)applyTheme;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)updateDataSource;
- (void)dealloc;
- (id)initWithSpotifyURL:(id)arg1 description:(id)arg2 image:(id)arg3 type:(id)arg4 links:(id)arg5 moreControls:(id)arg6 shareFeature:(id)arg7 imageLoaderFactory:(id)arg8 viewLogger:(id)arg9;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

