//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTLogCenter.h"

@interface SPTLogCenter (Running)
- (void)logUserChangedRunningManualTempo:(unsigned long long)arg1 fromTempo:(unsigned long long)arg2 fromViewURL:(id)arg3;
- (void)logUserPressedSwitchToAutomatic;
- (void)logUserEnteredRunningSetupStep:(long long)arg1 fromViewURL:(id)arg2;
- (void)logUserPressedRunningStartRunningFromViewURL:(id)arg1;
- (void)logUserPressedRunningVideoOnboarding;
- (void)logUserPressedRunningSwitchToManualFromViewURL:(id)arg1;
- (void)logUserPressedRunningPreset:(id)arg1;
@end

