//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTLogCenter.h"

@interface SPTLogCenter (NowPlayingBar)
- (void)logNowPlayingSwipeToNPV;
- (void)logNowPlayingBarCollectionButtonTouchedUpInside;
- (void)logNowPlayingBarPreviousTrackSwiped;
- (void)logNowPlayingBarNextTrackSwiped;
- (void)logNowPlayingBarDurationSliderValueChanged;
- (void)logNowPlayingBarNextButtonTouchedUpInside;
- (void)logNowPlayingBarPlayButtonTouchedUpInside;
- (void)logNowPlayingBarPreviousButtonTouchedUpInside;
@end

