//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTMixpanelPeopleController.h"

@class Mixpanel, NSString;

@interface SPTMixpanelPeopleController : NSObject <SPTMixpanelPeopleController>
{
    Mixpanel *_mixpanel;
}

@property(retain, nonatomic) Mixpanel *mixpanel; // @synthesize mixpanel=_mixpanel;
- (void).cxx_destruct;
- (void)incrementProperties:(id)arg1;
- (void)incrementProperty:(id)arg1 byAmount:(id)arg2;
- (void)incrementProperty:(id)arg1;
- (void)setProperties:(id)arg1;
- (void)setPropertiesOnce:(id)arg1;
- (void)setProperty:(id)arg1 toValue:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

