//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSNumber, NSString;

@protocol SPTMixpanelPeopleController <NSObject>
- (void)incrementProperties:(NSDictionary *)arg1;
- (void)incrementProperty:(NSString *)arg1 byAmount:(NSNumber *)arg2;
- (void)incrementProperty:(NSString *)arg1;
- (void)setPropertiesOnce:(NSDictionary *)arg1;
- (void)setProperties:(NSDictionary *)arg1;
- (void)setProperty:(NSString *)arg1 toValue:(id)arg2;
@end

