//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SPTImageLoaderDelegate.h"
#import "SPTNowPlayingQueueModelDelegate.h"
#import "SPTTableViewContinuousSwipeDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, SPTNowPlayingQueueModel, SPTNowPlayingQueueView, UIBarButtonItem, UIImage;

@interface SPTNowPlayingQueueViewController : UIViewController <SPTNowPlayingQueueModelDelegate, SPTImageLoaderDelegate, UITableViewDataSource, UITableViewDelegate, SPTTableViewContinuousSwipeDelegate>
{
    _Bool _disableUpdates;
    _Bool _adIsPlaying;
    SPTNowPlayingQueueModel *_model;
    id <SPContextMenuFeature> _contextMenu;
    id <SPTPodcastFeature> _podcastFeature;
    id <SPTPodcastContextMenuProvider> _podcastContextMenuProvider;
    id <SPTAudioTouch> _audioTouch;
    id <SPTImageLoader> _imageLoader;
    SPTNowPlayingQueueView *_queueView;
    UIBarButtonItem *_editBarButtonItem;
    UIBarButtonItem *_doneBarButtonItem;
    UIImage *_editableCellPrefixImage;
    NSArray *_queue;
    CDUnknownBlockType _afterScrollingBlock;
}

+ (id)nowPlayingQueueViewControllerWithModel:(id)arg1 contextMenu:(id)arg2 podcastFeature:(id)arg3 audioTouch:(id)arg4 imageLoader:(id)arg5;
@property(copy, nonatomic) CDUnknownBlockType afterScrollingBlock; // @synthesize afterScrollingBlock=_afterScrollingBlock;
@property(copy, nonatomic) NSArray *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) UIImage *editableCellPrefixImage; // @synthesize editableCellPrefixImage=_editableCellPrefixImage;
@property(nonatomic) _Bool adIsPlaying; // @synthesize adIsPlaying=_adIsPlaying;
@property(nonatomic) _Bool disableUpdates; // @synthesize disableUpdates=_disableUpdates;
@property(retain, nonatomic) UIBarButtonItem *doneBarButtonItem; // @synthesize doneBarButtonItem=_doneBarButtonItem;
@property(retain, nonatomic) UIBarButtonItem *editBarButtonItem; // @synthesize editBarButtonItem=_editBarButtonItem;
@property(retain, nonatomic) SPTNowPlayingQueueView *queueView; // @synthesize queueView=_queueView;
@property(retain, nonatomic) id <SPTImageLoader> imageLoader; // @synthesize imageLoader=_imageLoader;
@property(retain, nonatomic) id <SPTAudioTouch> audioTouch; // @synthesize audioTouch=_audioTouch;
@property(retain, nonatomic) id <SPTPodcastContextMenuProvider> podcastContextMenuProvider; // @synthesize podcastContextMenuProvider=_podcastContextMenuProvider;
@property(retain, nonatomic) id <SPTPodcastFeature> podcastFeature; // @synthesize podcastFeature=_podcastFeature;
@property(nonatomic) __weak id <SPContextMenuFeature> contextMenu; // @synthesize contextMenu=_contextMenu;
@property(retain, nonatomic) SPTNowPlayingQueueModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (_Bool)continuousSwipeEnabledForTableView:(id)arg1;
- (void)dismissViewController;
- (void)queueViewEditButtonTouchedUpInside:(id)arg1;
- (void)presentContextMenuForSleepTimer;
- (void)sleepTimerButtonTouchedUpInside:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)setRow:(long long)arg1 inTableView:(id)arg2 active:(_Bool)arg3 animated:(_Bool)arg4;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)dismissWhenSelectVideoAtIndexPath:(id)arg1;
- (void)contextMenuAccessoryButtonTouchedUpInside:(id)arg1;
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayVideoCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayAudioCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 videoCellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 audioCellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)willMoveToParentViewController:(id)arg1;
- (void)loadView;
- (void)nowPlayingModelQueue:(id)arg1 willChangeQueue:(id)arg2;
- (void)nowPlayingModelQueueDidChange:(id)arg1;
- (void)imageLoader:(id)arg1 didLoadImage:(id)arg2 forURL:(id)arg3 loadTime:(double)arg4 context:(id)arg5;
- (void)scrollToRowIndex:(long long)arg1 and:(CDUnknownBlockType)arg2;
- (void)handleModelChange;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)scrollToFirstTrackAnimated:(_Bool)arg1;
- (void)reloadData;
- (void)reloadAndScrollToTop;
- (void)checkQueuedItemsForEditBarButtonItem;
- (void)setupSleepTimerButton;
- (void)dealloc;
- (id)initWithModel:(id)arg1 contextMenu:(id)arg2 podcastFeature:(id)arg3 audioTouch:(id)arg4 imageLoader:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

