//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SPTBarInteractiveTransitionParticipant.h"
#import "SPTNowPlayingBarViewController.h"
#import "SPTNowPlayingDurationViewFlexibleLayoutSource.h"
#import "SPTNowPlayingTrackPositionObserver.h"

@class NSString, SPTLayoutConstraintBuilder, SPTNowPlayingDurationDataSource, SPTNowPlayingDurationView, SPTNowPlayingTrackPosition, SPTTheme, UIView;

@interface SPTNowPlayingBarContainerViewController : UIViewController <SPTNowPlayingTrackPositionObserver, SPTNowPlayingDurationViewFlexibleLayoutSource, SPTBarInteractiveTransitionParticipant, SPTNowPlayingBarViewController>
{
    UIViewController *_contentViewController;
    SPTLayoutConstraintBuilder *_layout;
    SPTNowPlayingDurationView *_durationView;
    SPTNowPlayingDurationDataSource *_durationDataSource;
    SPTNowPlayingTrackPosition *_trackPositionModel;
    SPTTheme *_theme;
}

@property(readonly, nonatomic) SPTTheme *theme; // @synthesize theme=_theme;
@property(readonly, nonatomic) SPTNowPlayingTrackPosition *trackPositionModel; // @synthesize trackPositionModel=_trackPositionModel;
@property(readonly, nonatomic) SPTNowPlayingDurationDataSource *durationDataSource; // @synthesize durationDataSource=_durationDataSource;
@property(readonly, nonatomic) SPTNowPlayingDurationView *durationView; // @synthesize durationView=_durationView;
@property(retain, nonatomic) SPTLayoutConstraintBuilder *layout; // @synthesize layout=_layout;
@property(readonly, nonatomic) UIViewController *contentViewController; // @synthesize contentViewController=_contentViewController;
- (void).cxx_destruct;
@property(readonly, nonatomic) UIView *backgroundView;
@property(nonatomic, getter=isVideoDisabled) _Bool videoDisabled;
- (id)backgroundViewForBarTransition:(id)arg1;
- (id)constraintsForDurationSlider:(id)arg1 timeRemainingLabel:(id)arg2 timeTakenLabel:(id)arg3;
- (void)nowPlayingTrackPositionDidChange:(id)arg1;
- (void)updateViewConstraints;
- (void)setupSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithTheme:(id)arg1 trackPositionModel:(id)arg2 contentViewController:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

