//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SPTNowPlayingBarView.h"

@class NSLayoutConstraint, NSString, SPStepScrollView, SPTLayoutConstraintBuilder, SPTNowPlayingBackgroundView, SPTNowPlayingFadeMaskView, SPTTheme, UIButton, UIButton<SPTNowPlayingBarPlayButton>;

@interface SPTNowPlayingBarContentView : UIView <SPTNowPlayingBarView>
{
    _Bool _enabled;
    SPTNowPlayingBackgroundView *_backgroundView;
    UIButton<SPTNowPlayingBarPlayButton> *_playPauseButton;
    UIButton *_accessoryButton;
    UIView *_accessoryView;
    SPStepScrollView *_stepScrollView;
    UIButton *_leftButton;
    UIView *_contentView;
    SPTNowPlayingFadeMaskView *_fadeContentView;
    SPTTheme *_theme;
    SPTLayoutConstraintBuilder *_layout;
    NSLayoutConstraint *_leftButtonHorizontalConstraint;
}

@property(retain, nonatomic) NSLayoutConstraint *leftButtonHorizontalConstraint; // @synthesize leftButtonHorizontalConstraint=_leftButtonHorizontalConstraint;
@property(retain, nonatomic) SPTLayoutConstraintBuilder *layout; // @synthesize layout=_layout;
@property(readonly, nonatomic) SPTTheme *theme; // @synthesize theme=_theme;
@property(readonly, nonatomic) SPTNowPlayingFadeMaskView *fadeContentView; // @synthesize fadeContentView=_fadeContentView;
@property(readonly, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(readonly, nonatomic) UIButton *leftButton; // @synthesize leftButton=_leftButton;
@property(readonly, nonatomic) SPStepScrollView *stepScrollView; // @synthesize stepScrollView=_stepScrollView;
@property(retain, nonatomic) UIView *accessoryView; // @synthesize accessoryView=_accessoryView;
@property(retain, nonatomic) UIButton *accessoryButton; // @synthesize accessoryButton=_accessoryButton;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(readonly, nonatomic) UIButton<SPTNowPlayingBarPlayButton> *playPauseButton; // @synthesize playPauseButton=_playPauseButton;
@property(readonly, nonatomic) SPTNowPlayingBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void).cxx_destruct;
- (void)hideLeftButton:(_Bool)arg1;
- (void)setEnabled:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setAccessoryView:(id)arg1 animated:(_Bool)arg2;
- (void)forceLayout;
- (void)resetConstraints;
- (double)leftButtonLeftEdgeConstant:(_Bool)arg1;
- (void)updateConstraints;
- (void)setupSubviews;
- (id)initWithFrame:(struct CGRect)arg1 theme:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

