//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SPTBarOverlayAdditionalTransitionProvider.h"
#import "SPTBarOverlayViewController.h"
#import "SPTGaiaDeviceStateManagerObserver.h"
#import "SPTNowPlayingContainingViewController.h"
#import "SPTNowPlayingUnitProviderObserver.h"

@class MetaViewController, NSArray, NSDictionary, NSHashTable, NSString, SPTGaiaDevice, SPTLayoutConstraintBuilder, SPTLogCenter, SPTNowPlayingAdditionalTransition, SPTNowPlayingBackgroundCornersView, SPTNowPlayingBackgroundGradientView, SPTNowPlayingBackgroundView, SPTNowPlayingBlurControllerObject, SPTNowPlayingContentUnitProvider, SPTNowPlayingDurationUnitProvider, SPTNowPlayingModel, SPTStatusBarToken, SPTTheme, SPTTinkerbellItem, SPTTinkerbellStory;

@interface SPTNowPlayingContainerViewController : UIViewController <SPTNowPlayingUnitProviderObserver, SPTNowPlayingContainingViewController, SPTGaiaDeviceStateManagerObserver, SPTBarOverlayViewController, SPTBarOverlayAdditionalTransitionProvider>
{
    _Bool _isPresentingTinkerbell;
    SPTNowPlayingModel *_model;
    SPTTheme *_theme;
    SPTLogCenter *_logCenter;
    id <SPTNowPlayingManager> _nowPlayingManager;
    MetaViewController *_metaViewController;
    SPTNowPlayingAdditionalTransition *_additionalTransition;
    SPTLayoutConstraintBuilder *_layout;
    NSArray *_extraLayoutConstraints;
    NSHashTable *_viewControllers;
    NSDictionary *_staticViewControllers;
    NSArray *_providers;
    SPTNowPlayingBackgroundView *_backgroundView;
    SPTNowPlayingBlurControllerObject *_blurController;
    SPTNowPlayingContentUnitProvider *_contentUnitProvider;
    SPTNowPlayingBackgroundGradientView *_backgroundGradientView;
    SPTNowPlayingBackgroundCornersView *_backgroundCornersView;
    SPTNowPlayingDurationUnitProvider *_durationUnitProvider;
    SPTStatusBarToken *_statusBarToken;
    id <SPTTinkerbellManager> _tinkerbellManager;
    id <SPTTinkerbellItemPresentationController> _tinkerbellController;
    SPTTinkerbellStory *_onboardingTinkerbellStory;
    SPTTinkerbellItem *_onboardingTinkerbellItem;
    SPTGaiaDevice *_newlyDiscoveredDevice;
    id <GaiaFeature> _gaia;
}

@property(nonatomic) __weak id <GaiaFeature> gaia; // @synthesize gaia=_gaia;
@property(retain, nonatomic) SPTGaiaDevice *newlyDiscoveredDevice; // @synthesize newlyDiscoveredDevice=_newlyDiscoveredDevice;
@property(retain, nonatomic) SPTTinkerbellItem *onboardingTinkerbellItem; // @synthesize onboardingTinkerbellItem=_onboardingTinkerbellItem;
@property(retain, nonatomic) SPTTinkerbellStory *onboardingTinkerbellStory; // @synthesize onboardingTinkerbellStory=_onboardingTinkerbellStory;
@property(retain, nonatomic) id <SPTTinkerbellItemPresentationController> tinkerbellController; // @synthesize tinkerbellController=_tinkerbellController;
@property(retain, nonatomic) id <SPTTinkerbellManager> tinkerbellManager; // @synthesize tinkerbellManager=_tinkerbellManager;
@property(nonatomic) _Bool isPresentingTinkerbell; // @synthesize isPresentingTinkerbell=_isPresentingTinkerbell;
@property(retain, nonatomic) SPTStatusBarToken *statusBarToken; // @synthesize statusBarToken=_statusBarToken;
@property(retain, nonatomic) SPTNowPlayingDurationUnitProvider *durationUnitProvider; // @synthesize durationUnitProvider=_durationUnitProvider;
@property(retain, nonatomic) SPTNowPlayingBackgroundCornersView *backgroundCornersView; // @synthesize backgroundCornersView=_backgroundCornersView;
@property(retain, nonatomic) SPTNowPlayingBackgroundGradientView *backgroundGradientView; // @synthesize backgroundGradientView=_backgroundGradientView;
@property(retain, nonatomic) SPTNowPlayingContentUnitProvider *contentUnitProvider; // @synthesize contentUnitProvider=_contentUnitProvider;
@property(retain, nonatomic) SPTNowPlayingBlurControllerObject *blurController; // @synthesize blurController=_blurController;
@property(retain, nonatomic) SPTNowPlayingBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) NSArray *providers; // @synthesize providers=_providers;
@property(retain, nonatomic) NSDictionary *staticViewControllers; // @synthesize staticViewControllers=_staticViewControllers;
@property(retain, nonatomic) NSHashTable *viewControllers; // @synthesize viewControllers=_viewControllers;
@property(retain, nonatomic) NSArray *extraLayoutConstraints; // @synthesize extraLayoutConstraints=_extraLayoutConstraints;
@property(retain, nonatomic) SPTLayoutConstraintBuilder *layout; // @synthesize layout=_layout;
@property(retain, nonatomic) SPTNowPlayingAdditionalTransition *additionalTransition; // @synthesize additionalTransition=_additionalTransition;
@property(nonatomic) __weak MetaViewController *metaViewController; // @synthesize metaViewController=_metaViewController;
@property(nonatomic) __weak id <SPTNowPlayingManager> nowPlayingManager; // @synthesize nowPlayingManager=_nowPlayingManager;
@property(nonatomic) __weak SPTLogCenter *logCenter; // @synthesize logCenter=_logCenter;
@property(retain, nonatomic) SPTTheme *theme; // @synthesize theme=_theme;
@property(retain, nonatomic) SPTNowPlayingModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)deviceStateManager:(id)arg1 availableDevicesDidChange:(id)arg2;
- (void)presentNewDeviceTinkerbell:(id)arg1;
- (id)provideTinkerbellStory;
- (id)provideOnboardingTinkerbellItem:(id)arg1;
- (id)additionalDismissTransitionWithContext:(id)arg1;
- (id)additionalPresentTransitionWithContext:(id)arg1;
- (void)containedViewController:(id)arg1 didUpdatePreferredSizeTo:(struct CGSize)arg2;
- (_Bool)barViewControllerInteractiveTransitionEnabled:(id)arg1;
- (id)replacementViewsForBarTransition:(id)arg1;
- (void)provider:(id)arg1 willReplaceViewController:(id)arg2 with:(id)arg3;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)viewControllersForEdge:(unsigned long long)arg1;
- (void)updateViewConstraints;
- (void)updateBackgroundViewConstraintsOnLayout:(id)arg1;
- (void)setupViewControllers;
- (void)viewDidLoad;
- (_Bool)shouldAutorotate;
- (void)dealloc;
- (id)initWithModel:(id)arg1 navigationBarModel:(id)arg2 theme:(id)arg3 headUnitProvider:(id)arg4 contentUnitProvider:(id)arg5 trackPositionModel:(id)arg6 gaia:(id)arg7 logCenter:(id)arg8 nowPlayingManager:(id)arg9 contextMenuFeature:(id)arg10 localSettings:(id)arg11 metaViewController:(id)arg12 additionalTransition:(id)arg13 tinkerbellManager:(id)arg14 durationUnitProvider:(id)arg15;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

