//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SPTNowPlayingMarqueeLabel;

@interface SPTNowPlayingMetadataLabelsContainerView : UIView
{
    SPTNowPlayingMarqueeLabel *_titleLabel;
    SPTNowPlayingMarqueeLabel *_artistLabel;
}

@property(retain, nonatomic) SPTNowPlayingMarqueeLabel *artistLabel; // @synthesize artistLabel=_artistLabel;
@property(retain, nonatomic) SPTNowPlayingMarqueeLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (id)description;
- (id)initWithFrame:(struct CGRect)arg1;

@end

