//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SPSidebarScrollDisabler.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSArray, NSMutableArray, NSString, UIScrollView, UITapGestureRecognizer;

@interface SPTPartyPagingCarouselView : UIView <UIScrollViewDelegate, UIGestureRecognizerDelegate, SPSidebarScrollDisabler>
{
    _Bool _disabled;
    id <SPTPartyPagingCarouselViewPagingDelegate> _pagingDelegate;
    NSArray *_titles;
    unsigned long long _selectedIndex;
    UIScrollView *_scrollView;
    NSMutableArray *_pageViews;
    UITapGestureRecognizer *_tap;
}

@property(retain, nonatomic) UITapGestureRecognizer *tap; // @synthesize tap=_tap;
@property(retain, nonatomic) NSMutableArray *pageViews; // @synthesize pageViews=_pageViews;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(readonly, nonatomic) unsigned long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(retain, nonatomic) NSArray *titles; // @synthesize titles=_titles;
@property(nonatomic, getter=isDisabled) _Bool disabled; // @synthesize disabled=_disabled;
@property(nonatomic) __weak id <SPTPartyPagingCarouselViewPagingDelegate> pagingDelegate; // @synthesize pagingDelegate=_pagingDelegate;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)shouldInterruptSidebarRevealGesture:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)resetContentOffsetBasedOnNewAbsoluteIndex:(unsigned long long)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)tap:(id)arg1;
- (void)updateCentersOfVisiblePageViews;
- (id)pageViewAtAbsoluteIndex:(unsigned long long)arg1;
- (unsigned long long)relativeIndexForAbsoluteIndex:(unsigned long long)arg1;
- (unsigned long long)absoluteIndexForScrollOffsetX:(double)arg1;
- (double)offsetToCenterOfPageViewForAbsoluteIndex:(unsigned long long)arg1;
- (double)offsetForAbsoluteIndex:(unsigned long long)arg1;
- (double)offsetForRelativeIndex:(unsigned long long)arg1;
- (void)updatePageViewsSelectedState;
- (void)setupPageViewsWithTitles:(id)arg1;
- (void)moveLeft:(_Bool)arg1 animated:(_Bool)arg2;
- (void)invokeDelegateForDidStopAtIndex;
- (void)setSelectedIndex:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)setSelectedIndex:(unsigned long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1 titles:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

