//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class CAGradientLayer, CALayer, CAShapeLayer, NSString, UIButton, UIImage, UILabel, UIPanGestureRecognizer, UITapGestureRecognizer;

@interface SPTPartyDialView : UIView <UIGestureRecognizerDelegate>
{
    _Bool _disabled;
    _Bool _playing;
    id <SPTPartyDialViewDelegate> _delegate;
    long long _triangleDirection;
    CALayer *_containerLayer;
    CAShapeLayer *_innerCircle;
    CAGradientLayer *_outerCircle;
    CAShapeLayer *_bottomMask;
    CAShapeLayer *_leftTapLayer;
    CAShapeLayer *_topTapLayer;
    CAShapeLayer *_rightTapLayer;
    UIButton *_playButton;
    UIImage *_playIconImage;
    UIImage *_skipIconImage;
    long long _previousTriangleDirection;
    UILabel *_energyLabel;
    UILabel *_energyLevelLabel;
    UIPanGestureRecognizer *_pan;
    UITapGestureRecognizer *_tap;
    struct CATransform3D _triangleTransform;
    struct CATransform3D _trianglePanTransform;
}

@property(retain, nonatomic) UITapGestureRecognizer *tap; // @synthesize tap=_tap;
@property(retain, nonatomic) UIPanGestureRecognizer *pan; // @synthesize pan=_pan;
@property(retain, nonatomic) UILabel *energyLevelLabel; // @synthesize energyLevelLabel=_energyLevelLabel;
@property(retain, nonatomic) UILabel *energyLabel; // @synthesize energyLabel=_energyLabel;
@property(nonatomic) long long previousTriangleDirection; // @synthesize previousTriangleDirection=_previousTriangleDirection;
@property(nonatomic) struct CATransform3D trianglePanTransform; // @synthesize trianglePanTransform=_trianglePanTransform;
@property(nonatomic) struct CATransform3D triangleTransform; // @synthesize triangleTransform=_triangleTransform;
@property(retain, nonatomic) UIImage *skipIconImage; // @synthesize skipIconImage=_skipIconImage;
@property(retain, nonatomic) UIImage *playIconImage; // @synthesize playIconImage=_playIconImage;
@property(retain, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(retain, nonatomic) CAShapeLayer *rightTapLayer; // @synthesize rightTapLayer=_rightTapLayer;
@property(retain, nonatomic) CAShapeLayer *topTapLayer; // @synthesize topTapLayer=_topTapLayer;
@property(retain, nonatomic) CAShapeLayer *leftTapLayer; // @synthesize leftTapLayer=_leftTapLayer;
@property(retain, nonatomic) CAShapeLayer *bottomMask; // @synthesize bottomMask=_bottomMask;
@property(retain, nonatomic) CAGradientLayer *outerCircle; // @synthesize outerCircle=_outerCircle;
@property(retain, nonatomic) CAShapeLayer *innerCircle; // @synthesize innerCircle=_innerCircle;
@property(retain, nonatomic) CALayer *containerLayer; // @synthesize containerLayer=_containerLayer;
@property(nonatomic, getter=isPlaying) _Bool playing; // @synthesize playing=_playing;
@property(nonatomic) long long triangleDirection; // @synthesize triangleDirection=_triangleDirection;
@property(nonatomic, getter=isDisabled) _Bool disabled; // @synthesize disabled=_disabled;
@property(nonatomic) __weak id <SPTPartyDialViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (long long)triangleDirectionForRotationRadians:(double)arg1;
- (float)radiansForPanLocation:(struct CGPoint)arg1;
- (void)didTapPlayButton:(id)arg1;
- (void)tap:(id)arg1;
- (void)pan:(id)arg1;
- (void)setupTapLayersIfNeeded;
- (void)setupBottomMaskIfNeeded;
- (void)setupInnerCircleIfNeeded;
- (void)setupOuterCircleIfNeeded;
- (void)setupPlayButton;
- (void)setupLabels;
- (void)bouncePlayButton;
- (void)setEnergyLabelText:(id)arg1;
- (void)changeTriangleDirectionAnimated:(_Bool)arg1;
- (void)setTriangleDirection:(long long)arg1 animated:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

