//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SPTImageLoaderDelegate.h"
#import "SPTPostComposerViewModelDelegate.h"
#import "SPTShareMessageViewDelegate.h"
#import "SPTShareOAuthViewControllerDelegate.h"

@class NSString, SPTActionButton, SPTClientEventLogger, SPTPostComposerViewModel, SPTShareItemView, SPTShareMessageView, SPTShareNetworkToggle, SPTShareOAuthViewController, SPTViewLogger, UILabel;

@interface SPTPostComposerVC : UIViewController <SPTImageLoaderDelegate, SPTPostComposerViewModelDelegate, SPTShareMessageViewDelegate, SPTShareOAuthViewControllerDelegate>
{
    id <SPTShareSheetProtocol> _shareSheetVC;
    SPTPostComposerViewModel *_viewModel;
    id <SPTImageLoader> _imageLoader;
    SPTClientEventLogger *_logger;
    SPTViewLogger *_viewLogger;
    SPTShareItemView *_itemView;
    SPTShareMessageView *_messageView;
    UILabel *_postOnLabel;
    SPTShareNetworkToggle *_facebookToggle;
    SPTShareNetworkToggle *_twitterToggle;
    SPTShareNetworkToggle *_tumblrToggle;
    SPTActionButton *_moreActionsButton;
    id <SPTShareFeature> _shareFeature;
    SPTShareOAuthViewController *_oauthViewController;
}

@property(retain, nonatomic) SPTShareOAuthViewController *oauthViewController; // @synthesize oauthViewController=_oauthViewController;
@property(nonatomic) __weak id <SPTShareFeature> shareFeature; // @synthesize shareFeature=_shareFeature;
@property(retain, nonatomic) SPTActionButton *moreActionsButton; // @synthesize moreActionsButton=_moreActionsButton;
@property(retain, nonatomic) SPTShareNetworkToggle *tumblrToggle; // @synthesize tumblrToggle=_tumblrToggle;
@property(retain, nonatomic) SPTShareNetworkToggle *twitterToggle; // @synthesize twitterToggle=_twitterToggle;
@property(retain, nonatomic) SPTShareNetworkToggle *facebookToggle; // @synthesize facebookToggle=_facebookToggle;
@property(retain, nonatomic) UILabel *postOnLabel; // @synthesize postOnLabel=_postOnLabel;
@property(retain, nonatomic) SPTShareMessageView *messageView; // @synthesize messageView=_messageView;
@property(retain, nonatomic) SPTShareItemView *itemView; // @synthesize itemView=_itemView;
@property(retain, nonatomic) SPTViewLogger *viewLogger; // @synthesize viewLogger=_viewLogger;
@property(retain, nonatomic) SPTClientEventLogger *logger; // @synthesize logger=_logger;
@property(retain, nonatomic) id <SPTImageLoader> imageLoader; // @synthesize imageLoader=_imageLoader;
@property(retain, nonatomic) SPTPostComposerViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) __weak id <SPTShareSheetProtocol> shareSheetVC; // @synthesize shareSheetVC=_shareSheetVC;
- (void).cxx_destruct;
- (_Bool)messageView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)messageViewDidEndEditing:(id)arg1;
- (void)messageViewDidBeginEditing:(id)arg1;
- (void)shareOAuthViewController:(id)arg1 didReceiveCredentialsQueryString:(id)arg2;
- (void)viewModel:(id)arg1 cannotPostItemWithFailureType:(long long)arg2;
- (void)viewModel:(id)arg1 failedToPostToNetworks:(id)arg2;
- (void)viewModelPostedSuccessfully:(id)arg1;
- (void)viewModelFailedToToggleSharingEnabledStateBecauseWeLackNetworksInfo:(id)arg1;
- (void)viewModel:(id)arg1 hadFailedRequestWithNetwork:(long long)arg2 wasConnectionRequest:(_Bool)arg3 error:(id)arg4;
- (void)viewModel:(id)arg1 hadSuccessfulRequestWithNetworkData:(id)arg2 wasConnectionRequest:(_Bool)arg3;
- (void)viewModel:(id)arg1 didNotReceiveAuthorizeURLForNetwork:(long long)arg2;
- (void)viewModel:(id)arg1 didReceiveAuthorizeURL:(id)arg2 forNetwork:(long long)arg3;
- (void)viewModel:(id)arg1 failedToFetchInfoWithError:(id)arg2;
- (void)viewModel:(id)arg1 didFetchInfo:(id)arg2;
- (void)imageLoader:(id)arg1 didLoadImage:(id)arg2 forURL:(id)arg3 loadTime:(double)arg4 context:(id)arg5;
- (void)didTapMoreButton:(id)arg1;
- (void)didToggleTumblr:(id)arg1;
- (void)didToggleTwitter:(id)arg1;
- (void)didToggleFacebook:(id)arg1;
- (void)showAlertForFailedNetworkConnection;
- (void)finishedOrFailedPosting;
- (void)updateItemView;
- (void)backButtonTapped;
- (void)doPostShare;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithViewModel:(id)arg1 imageLoaderFactory:(id)arg2 logger:(id)arg3 viewLogger:(id)arg4 shareFeature:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

