//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSData, NSString, NSURL, SPAlbum, SPArtist;

@interface SPTrack : NSObject
{
    struct RefPtr<const spotify::metadata::TrackInfo> _cppObject;
}

+ (id)trackWithTrackInfo:(const struct TrackInfo *)arg1;
+ (id)localTrackWithMetadataInfo:(id)arg1;
+ (id)localTrackWithTitle:(id)arg1 artist:(id)arg2 album:(id)arg3 length:(int)arg4 createInstanceIfExistingAlreadyHasFile:(_Bool)arg5;
- (id).cxx_construct;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (struct TrackId)id;
- (const struct TrackInfo *)trackInfo;
- (unsigned long long)hash;
@property(readonly, nonatomic) NSData *previewFileId;
@property(readonly, nonatomic) NSString *adTargetUrl;
@property(readonly, nonatomic) NSString *adCaption;
@property(readonly, nonatomic) long long localState;
@property(readonly, nonatomic) long long offlineState;
@property(readonly, nonatomic) SPTrack *playableTrack;
@property(readonly, nonatomic) SPTrack *remappedTrack;
@property(readonly, nonatomic) SPTrack *localTrack;
@property(readonly, nonatomic) _Bool isExplicit;
@property(readonly, nonatomic) _Bool isAd;
@property(readonly, nonatomic) _Bool isNormalFile;
@property(readonly, nonatomic) _Bool isLocalTrack;
@property(readonly, nonatomic) _Bool isLocallyPlayable;
@property(readonly, nonatomic) _Bool isAvailable;
@property(readonly, nonatomic) _Bool isLoaded;
@property(readonly, nonatomic) NSArray *artists;
@property(readonly, nonatomic) SPArtist *artist;
@property(readonly, nonatomic) SPAlbum *album;
@property(readonly, nonatomic) unsigned long long disc;
@property(readonly, nonatomic) unsigned long long trackNumber;
@property(readonly, nonatomic) unsigned long long popularity;
@property(readonly, nonatomic) unsigned long long length;
@property(readonly, nonatomic) NSURL *placeholderContent;
@property(readonly, nonatomic) NSURL *link;
@property(readonly, nonatomic) NSString *name;

@end

