//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SPTThemableView.h"

@class CMMotionManager, NSOperationQueue, NSString, SPTActionButton, SPTImageBlurView, SPTRunningDetectionAnimationView, SPTTheme, UIControl<SPTRunningTempoStepper>, UIImageView, UILabel;

@interface SPTRunningSetupView : UIView <SPTThemableView>
{
    id <SPTThemableViewLayoutDelegate> _layoutDelegate;
    long long _step;
    long long _tempo;
    SPTActionButton *_manualButton;
    UIControl<SPTRunningTempoStepper> *_tempoStepper;
    SPTActionButton *_startButton;
    SPTImageBlurView *_backgroundImageView;
    SPTTheme *_theme;
    CMMotionManager *_motionManager;
    NSOperationQueue *_accelerometerQueue;
    UIImageView *_iconImageView;
    UILabel *_titleLabel;
    UILabel *_descriptionLabel;
    UILabel *_tempoTitleLabel;
    UILabel *_tempoLabel;
    SPTRunningDetectionAnimationView *_animationView;
    struct UIEdgeInsets _contentInsets;
}

@property(retain, nonatomic) SPTRunningDetectionAnimationView *animationView; // @synthesize animationView=_animationView;
@property(retain, nonatomic) UILabel *tempoLabel; // @synthesize tempoLabel=_tempoLabel;
@property(retain, nonatomic) UILabel *tempoTitleLabel; // @synthesize tempoTitleLabel=_tempoTitleLabel;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) NSOperationQueue *accelerometerQueue; // @synthesize accelerometerQueue=_accelerometerQueue;
@property(retain, nonatomic) CMMotionManager *motionManager; // @synthesize motionManager=_motionManager;
@property(retain, nonatomic) SPTTheme *theme; // @synthesize theme=_theme;
@property(readonly, nonatomic) SPTImageBlurView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(readonly, nonatomic) SPTActionButton *startButton; // @synthesize startButton=_startButton;
@property(readonly, nonatomic) UIControl<SPTRunningTempoStepper> *tempoStepper; // @synthesize tempoStepper=_tempoStepper;
@property(retain, nonatomic) SPTActionButton *manualButton; // @synthesize manualButton=_manualButton;
@property(nonatomic) long long tempo; // @synthesize tempo=_tempo;
@property(nonatomic) long long step; // @synthesize step=_step;
@property(nonatomic) struct UIEdgeInsets contentInsets; // @synthesize contentInsets=_contentInsets;
@property(nonatomic) __weak id <SPTThemableViewLayoutDelegate> layoutDelegate; // @synthesize layoutDelegate=_layoutDelegate;
- (void).cxx_destruct;
- (void)stopAccelerometerUpdates;
- (void)startAccelerometerUpdates;
- (void)setupAccelerometerQueue;
- (void)setupMotionManager;
- (void)layoutSubviews;
- (void)applyThemeLayout;
- (void)dealloc;
- (id)init;
- (void)syncTempoAndTempoLabelText;
- (void)setupAnimationView;
- (id)initWithFrame:(struct CGRect)arg1 theme:(id)arg2 userInterfaceFactory:(id)arg3 testManager:(id)arg4 imageCache:(id)arg5 cacheKey:(id)arg6 image:(id)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

