//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSDictionary, NSString, NSURL;

@interface SPTStartPageMomentContext : NSObject <NSCopying>
{
    NSString *_name;
    NSString *_tagline;
    NSString *_descriptionText;
    NSString *_detail;
    NSString *_consumptionOrder;
    NSString *_type;
    NSURL *_entityURI;
    NSURL *_imageURL;
    NSURL *_contextPageURL;
    NSDictionary *_playStateRepresentation;
}

@property(readonly, nonatomic) NSDictionary *playStateRepresentation; // @synthesize playStateRepresentation=_playStateRepresentation;
@property(retain, nonatomic) NSURL *contextPageURL; // @synthesize contextPageURL=_contextPageURL;
@property(retain, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property(retain, nonatomic) NSURL *entityURI; // @synthesize entityURI=_entityURI;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *consumptionOrder; // @synthesize consumptionOrder=_consumptionOrder;
@property(copy, nonatomic) NSString *detail; // @synthesize detail=_detail;
@property(copy, nonatomic) NSString *descriptionText; // @synthesize descriptionText=_descriptionText;
@property(copy, nonatomic) NSString *tagline; // @synthesize tagline=_tagline;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (unsigned long long)hash;
@property(readonly, nonatomic) _Bool shouldDisplayTagline;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToContextModel:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) NSDictionary *dictionaryRepresentation;
- (id)initWithName:(id)arg1 tagline:(id)arg2 descriptionText:(id)arg3 detail:(id)arg4 entityURI:(id)arg5 imageURL:(id)arg6 contextPageURL:(id)arg7 type:(id)arg8 playStateRepresentation:(id)arg9 consumptionOrder:(id)arg10;
- (id)initWithDictionaryRepresentation:(id)arg1;

@end

