//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTSwipeableTableViewCellShelf.h"

@interface SPTSwipeableTableViewCellShelf (Defaults)
+ (id)hideFromListShelf;
+ (id)removeFromCollectionShelf;
+ (id)saveToCollectionShelf;
+ (id)queueShelf;
+ (id)deleteShelf;
+ (id)destructiveShelfWithHintString:(id)arg1 actionString:(id)arg2 hintIcon:(unsigned long long)arg3 actionIcon:(unsigned long long)arg4;
+ (id)constructiveShelfWithHintString:(id)arg1 actionString:(id)arg2 hintIcon:(unsigned long long)arg3 actionIcon:(unsigned long long)arg4;
+ (id)shelfWithHintColor:(id)arg1 actionColor:(id)arg2 hintString:(id)arg3 actionString:(id)arg4 hintIcon:(unsigned long long)arg5 actionIcon:(unsigned long long)arg6;
+ (void)stylizeLabel:(id)arg1;
+ (void)stylizeLabels:(id)arg1;
+ (_Bool)showsLabels;
+ (id)whitelistedLanguages;
@end

