//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SyncManagerApiObserver.h"

@class NSMapTable;

@interface SPTSyncManager : NSObject <SyncManagerApiObserver>
{
    struct scoped_connection _core_event_connection;
    struct scoped_connection _syncManagerConnection;
    _Bool _syncing;
    float _progress;
    unsigned long long _copiedTracks;
    unsigned long long _totalTracks;
    struct SyncManagerApiObserver *_syncManagerApiObserver;
    struct SyncManagerApi *_syncManagerApi;
    NSMapTable *_observers;
}

+ (id)syncManagerWithSession:(id)arg1 core:(id)arg2;
@property(retain, nonatomic) NSMapTable *observers; // @synthesize observers=_observers;
@property(nonatomic) struct SyncManagerApi *syncManagerApi; // @synthesize syncManagerApi=_syncManagerApi;
@property(nonatomic) struct SyncManagerApiObserver *syncManagerApiObserver; // @synthesize syncManagerApiObserver=_syncManagerApiObserver;
@property(nonatomic) unsigned long long totalTracks; // @synthesize totalTracks=_totalTracks;
@property(nonatomic) unsigned long long copiedTracks; // @synthesize copiedTracks=_copiedTracks;
@property(nonatomic) float progress; // @synthesize progress=_progress;
@property(nonatomic, getter=isSyncing) _Bool syncing; // @synthesize syncing=_syncing;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)dealloc;
- (void)syncMangerApiObserverDidUpdate:(struct SyncManagerApiObserver *)arg1;
- (void)invalidate;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1 on:(id)arg2;
- (id)initWithSession:(id)arg1 core:(id)arg2;

@end

