//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SPTThemableView.h"
#import "UIScrollViewDelegate.h"

@class NSString, UIActivityIndicatorView, UIImageView, UILabel, UITableView;

@interface SPTStationEntityPullToRefreshView : UIView <SPTThemableView, UIScrollViewDelegate>
{
    id <SPTThemableViewLayoutDelegate> _layoutDelegate;
    id <SPTStationEntityPullToRefreshViewDelegate> _delegate;
    unsigned long long _state;
    UIImageView *_iconView;
    UILabel *_message;
    UITableView *_tableView;
    UIActivityIndicatorView *_activityIndicator;
}

+ (double)preferredHeight;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UILabel *message; // @synthesize message=_message;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(retain, nonatomic) id <SPTStationEntityPullToRefreshViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <SPTThemableViewLayoutDelegate> layoutDelegate; // @synthesize layoutDelegate=_layoutDelegate;
- (void).cxx_destruct;
- (void)applyThemeLayout;
- (void)scrollViewWillBeginDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (double)tableViewOffset;
- (id)arrowIcon;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithTableView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

