//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SPContentInsetViewController.h"
#import "SPTImageLoaderDelegate.h"
#import "SPTStartPageMomentCollectionViewVideoCellDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class NSString, SPTProgressView, SPTStartPageLogger, SPTStartPageMomentViewModel, SPTStartPageShadowGenerator, UICollectionView;

@interface SPTStartPageMomentViewController : UIViewController <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, SPTImageLoaderDelegate, SPContentInsetViewController, SPTStartPageMomentCollectionViewVideoCellDelegate>
{
    _Bool _scrolling;
    id <SPTStartPageMomentViewControllerDelegate> _delegate;
    SPTStartPageMomentViewModel *_viewModel;
    SPTStartPageLogger *_logger;
    id <SPTImageLoader> _imageLoader;
    UICollectionView *_collectionView;
    id <SPTVideoSurfaceManager> _videoSurfaceManager;
    SPTStartPageShadowGenerator *_shadowGenerator;
    id <StartPageFeature> _startPageFeature;
    SPTProgressView *_progressView;
}

@property(nonatomic, getter=isScrolling) _Bool scrolling; // @synthesize scrolling=_scrolling;
@property(retain, nonatomic) SPTProgressView *progressView; // @synthesize progressView=_progressView;
@property(nonatomic) __weak id <StartPageFeature> startPageFeature; // @synthesize startPageFeature=_startPageFeature;
@property(retain, nonatomic) SPTStartPageShadowGenerator *shadowGenerator; // @synthesize shadowGenerator=_shadowGenerator;
@property(retain, nonatomic) id <SPTVideoSurfaceManager> videoSurfaceManager; // @synthesize videoSurfaceManager=_videoSurfaceManager;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(readonly, nonatomic) id <SPTImageLoader> imageLoader; // @synthesize imageLoader=_imageLoader;
@property(retain, nonatomic) SPTStartPageLogger *logger; // @synthesize logger=_logger;
@property(readonly, nonatomic) SPTStartPageMomentViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) __weak id <SPTStartPageMomentViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)momentCollectionViewVideoCell:(id)arg1 shouldDisplayVideoForTrack:(id)arg2;
- (void)followButton:(id)arg1 tappedForCell:(id)arg2;
- (void)applyThemeLayout;
- (void)imageLoader:(id)arg1 didLoadImage:(id)arg2 forURL:(id)arg3 loadTime:(double)arg4 context:(id)arg5;
- (void)logContextSwipeChange;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)updateFollowButtonForContextWithIndex:(long long)arg1;
- (void)playCurrentContext:(_Bool)arg1;
- (id)collectionView:(id)arg1 cellForContextViewModel:(id)arg2 indexPath:(id)arg3;
- (struct CGSize)imageSizeForContextViewModel:(id)arg1 theme:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)sp_updateContentInsets;
- (id)currentlyDisplayedVideoSurfaceCollectionViewCell;
- (id)currentlyDisplayedVideoSurface;
- (void)reloadHideMetadataOnCells;
- (id)title;
- (void)snapshotCell:(id)arg1 intoContextViewModel:(id)arg2;
- (void)momentDidBecomeInactive;
- (void)momentDidBecomeActive:(_Bool)arg1;
- (_Bool)selectContextAtIndex:(unsigned long long)arg1;
- (_Bool)selectNextContext;
- (_Bool)selectPreviousContext;
- (void)navigateToCurrentContext;
- (void)viewDidLayoutSubviews;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)currentlyDisplayedVideoCollectionViewCell;
- (long long)currentCollectionViewIndex;
- (struct CGRect)collectionViewFrame;
- (void)dealloc;
- (id)initWithViewModel:(id)arg1 logger:(id)arg2 imageLoader:(id)arg3 videoSurfaceManager:(id)arg4 cellShadowGenerator:(id)arg5 startPageFeature:(id)arg6;

// Remaining properties
@property(nonatomic) _Bool automaticallyAdjustsScrollViewInsets;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

