//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTFeature.h"
#import "SPTTinkerbellFeature.h"

@class NSString, SPTAllocationContext, SPTTheme, SPTTinkerbellManagerImplementation, SPTTinkerbellManagerProxy, SPTTinkerbellStoryRegistryImplementation;

@interface SPTTinkerbellFeatureImplementation : NSObject <SPTTinkerbellFeature, SPTFeature>
{
    _Bool _tinkerbellAvailable;
    id <SPTAbbaFeature> _abbaFeature;
    id <BaseFeature> _baseFeature;
    id <SPTKeystoreFeature> _keystoreFeature;
    id <SettingsFeature> _settingsFeature;
    id <SPTFeatureEnabledStateReducer> _featureFlagReducer;
    SPTTinkerbellManagerImplementation *_tinkerbellManager;
    SPTTinkerbellManagerProxy *_tinkerbellManagerProxy;
    SPTTinkerbellStoryRegistryImplementation *_storyRegistry;
}

+ (id)featureDependencies;
+ (id)featureIdentifier;
@property(retain, nonatomic) SPTTinkerbellStoryRegistryImplementation *storyRegistry; // @synthesize storyRegistry=_storyRegistry;
@property(retain, nonatomic) SPTTinkerbellManagerProxy *tinkerbellManagerProxy; // @synthesize tinkerbellManagerProxy=_tinkerbellManagerProxy;
@property(retain, nonatomic) SPTTinkerbellManagerImplementation *tinkerbellManager; // @synthesize tinkerbellManager=_tinkerbellManager;
@property(retain, nonatomic) id <SPTFeatureEnabledStateReducer> featureFlagReducer; // @synthesize featureFlagReducer=_featureFlagReducer;
@property(nonatomic) __weak id <SettingsFeature> settingsFeature; // @synthesize settingsFeature=_settingsFeature;
@property(nonatomic) __weak id <SPTKeystoreFeature> keystoreFeature; // @synthesize keystoreFeature=_keystoreFeature;
@property(nonatomic) __weak id <BaseFeature> baseFeature; // @synthesize baseFeature=_baseFeature;
@property(nonatomic) __weak id <SPTAbbaFeature> abbaFeature; // @synthesize abbaFeature=_abbaFeature;
@property(nonatomic, getter=isTinkerbellAvailable) _Bool tinkerbellAvailable; // @synthesize tinkerbellAvailable=_tinkerbellAvailable;
- (void).cxx_destruct;
- (void)createAndRegisterGeneralOnboardingStory;
- (id)provideOnboardingDataSource;
- (id)provideLogger;
- (id)provideStoryRegistry;
- (id)provideTinkerbellManager;
@property(readonly, nonatomic) SPTTheme *currentTheme;
- (void)handleFeatureStateChange:(_Bool)arg1;
- (void)unload;
- (void)loadFeatureFlagReducer;
- (void)load;
- (void)configureWithFeatures:(id)arg1;

// Remaining properties
@property(retain, nonatomic) SPTAllocationContext *allocationContext;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

