//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CosmosFeature.h"

@class NSString, SPTRouter;

@interface SPTTinkerbellCosmosFeatureMock : NSObject <CosmosFeature>
{
    SPTRouter *_routerMock;
}

@property(retain, nonatomic) SPTRouter *routerMock; // @synthesize routerMock=_routerMock;
- (void).cxx_destruct;
- (id)provideRouterWithParameters:(id)arg1;
- (id)provideResolverWithParameters:(id)arg1;
- (id)provideResolverWithViewName:(id)arg1 viewSession:(id)arg2 viewVersion:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

