//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSHashTable, SPTTouchDownloadManager;

@interface SPTTouchAudioEngine : NSObject
{
    SPTTouchDownloadManager *_downloadManager;
    unsigned long long _preloadByteSize;
    id <SPTAudioDriverController> _audioDriverController;
    NSHashTable *_observers;
}

@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(nonatomic) __weak id <SPTAudioDriverController> audioDriverController; // @synthesize audioDriverController=_audioDriverController;
@property(readonly, nonatomic) unsigned long long preloadByteSize; // @synthesize preloadByteSize=_preloadByteSize;
@property(retain, nonatomic) SPTTouchDownloadManager *downloadManager; // @synthesize downloadManager=_downloadManager;
- (void).cxx_destruct;
- (void)notifyDelegatesWithBlock:(CDUnknownBlockType)arg1;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (id)createSampleWithURL:(id)arg1;
- (id)initWithDownloadManager:(id)arg1 preloadByteSize:(unsigned long long)arg2 audioDriverController:(id)arg3;

@end

