//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@interface SPTUpsellPaddedLabel : UILabel
{
    struct UIEdgeInsets _textPadding;
}

@property(nonatomic) struct UIEdgeInsets textPadding; // @synthesize textPadding=_textPadding;
- (struct CGSize)intrinsicContentSize;
- (void)drawTextInRect:(struct CGRect)arg1;

@end

