//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSUserActivityDelegate.h"

@class NSMapTable, NSString, NSURL;

@interface SPTUserActivityController : NSObject <NSUserActivityDelegate>
{
    NSMapTable *_activityURIs;
    NSURL *_restorationViewURI;
    CDUnknownBlockType _restorationHandler;
}

+ (void)registerFeatureSettingsWithRegistry:(id)arg1;
+ (_Bool)userActivitiesSupportedAndEnabled;
+ (_Bool)isUserActivitySupported;
+ (_Bool)isUserActivityEnabled;
@property(copy, nonatomic) CDUnknownBlockType restorationHandler; // @synthesize restorationHandler=_restorationHandler;
@property(retain, nonatomic) NSURL *restorationViewURI; // @synthesize restorationViewURI=_restorationViewURI;
@property(readonly, nonatomic) NSMapTable *activityURIs; // @synthesize activityURIs=_activityURIs;
- (void).cxx_destruct;
- (_Bool)restoreUserActivity:(id)arg1 restorationHandler:(CDUnknownBlockType)arg2;
- (void)updateUserActivity:(id)arg1;
- (void)registerUserActivityForResponder:(id)arg1 uri:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

