//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTProductStateObserver.h"

@class NSString, SPTProductState;

@interface SPTUserEventTrackerAdjustEnabledProvider : NSObject <SPTProductStateObserver>
{
    SPTProductState *_productState;
}

@property(nonatomic) __weak SPTProductState *productState; // @synthesize productState=_productState;
- (void).cxx_destruct;
- (void)productState:(id)arg1 stateDidChange:(id)arg2;
- (id)getAdjustValueFromUserDefaults;
- (void)setUserDefaultsValue:(id)arg1;
- (void)userDidLogOut;
- (void)userDidLogIn;
- (id)adjustInstance;
- (_Bool)isAdjustEnabledFromUserDefaults;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

