//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, SPTUpsell, SPTUpsellLogger;

@interface SPTUpsellPopupViewModel : NSObject
{
    NSArray *_buttonViewModels;
    SPTUpsell *_upsell;
    SPTUpsellLogger *_logger;
}

@property(readonly, nonatomic) SPTUpsellLogger *logger; // @synthesize logger=_logger;
@property(readonly, nonatomic) SPTUpsell *upsell; // @synthesize upsell=_upsell;
- (void).cxx_destruct;
- (long long)promotedOfferAsAvailableProduct;
- (void)closeButtonWasTapped;
- (void)getButtonWasTapped;
- (void)userInterfaceWasPresented;
- (id)createButtonViewModelFromButtons:(id)arg1 forButtonType:(long long)arg2 withAction:(CDUnknownBlockType)arg3;
- (id)createButtonViewModels;
@property(readonly, copy, nonatomic) NSArray *buttonViewModels; // @synthesize buttonViewModels=_buttonViewModels;
- (id)initWithUpsell:(id)arg1 logger:(id)arg2;

@end

