//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSError, SPTWidevineService;

@interface SPTVideoTransmuxJob : NSObject
{
    _Bool _isFinished;
    _Bool _isCancelled;
    NSData *_hlsData;
    NSError *_error;
    SPTWidevineService *_widevineService;
    NSData *_pssh;
    CDUnknownBlockType _completionBlock;
}

@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(retain, nonatomic) NSData *pssh; // @synthesize pssh=_pssh;
@property(retain, nonatomic) SPTWidevineService *widevineService; // @synthesize widevineService=_widevineService;
@property(readonly, nonatomic) _Bool isCancelled; // @synthesize isCancelled=_isCancelled;
@property(readonly, nonatomic) _Bool isFinished; // @synthesize isFinished=_isFinished;
@property(readonly, nonatomic) NSError *error; // @synthesize error=_error;
@property(readonly, nonatomic) NSData *hlsData; // @synthesize hlsData=_hlsData;
- (void).cxx_destruct;
- (void)executeCompletionBlock;
- (void)failWithStatus:(int)arg1 group:(unsigned long long)arg2 underlyingError:(id)arg3;
- (void)finishWithData:(id)arg1;
- (void)cancel;

@end

