//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTDataLoaderDelegate.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, SPTDataLoader, SPTVideoTransmuxer;

@interface SPTVideoSegmentProxySession : NSObject <SPTDataLoaderDelegate>
{
    NSString *_sessionID;
    id <SPTVideoSegmentProxySessionDelegate> _delegate;
    id <SPTVideoSegmentProxySessionDataSource> _dataSource;
    SPTVideoTransmuxer *_transmuxer;
    SPTDataLoader *_dataLoader;
    NSMutableDictionary *_dashInitSegmentTasks;
    NSObject<OS_dispatch_queue> *_workQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workQueue; // @synthesize workQueue=_workQueue;
@property(retain, nonatomic) NSMutableDictionary *dashInitSegmentTasks; // @synthesize dashInitSegmentTasks=_dashInitSegmentTasks;
@property(retain, nonatomic) SPTDataLoader *dataLoader; // @synthesize dataLoader=_dataLoader;
@property(retain, nonatomic) SPTVideoTransmuxer *transmuxer; // @synthesize transmuxer=_transmuxer;
@property(nonatomic) __weak id <SPTVideoSegmentProxySessionDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <SPTVideoSegmentProxySessionDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSString *sessionID; // @synthesize sessionID=_sessionID;
- (void).cxx_destruct;
- (_Bool)onWorkQueue;
- (void)dataLoader:(id)arg1 didCancelRequest:(id)arg2;
- (void)dataLoader:(id)arg1 didReceiveErrorResponse:(id)arg2;
- (void)dataLoader:(id)arg1 didReceiveSuccessfulResponse:(id)arg2;
- (id)dashInitSegmentTaskForProfileID:(unsigned long long)arg1;
- (id)transmuxDashMP4:(id)arg1 profileID:(unsigned long long)arg2 segmentIndex:(unsigned long long)arg3;
- (id)proxyURLForProfileID:(unsigned long long)arg1 segmentIndex:(unsigned long long)arg2;
- (void)dealloc;
- (id)init;
- (id)initWithSessionID:(id)arg1 dataLoader:(id)arg2 transmuxer:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

