//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSString;

@interface SWGDeferredAdCompleteCall : SWGObject
{
    NSString *_deferredResponseKey;
}

@property(retain, nonatomic) NSString *deferredResponseKey; // @synthesize deferredResponseKey=_deferredResponseKey;
- (void).cxx_destruct;
- (id)asDictionary;
- (id)initWithValues:(id)arg1;
- (id)deferredResponseKey:(id)arg1;

@end

