//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSNumber;

@interface SWGSpeechStartThreshold : SWGObject
{
    NSNumber *_defaultRoute;
    NSNumber *_MicrophoneBuiltIn;
    NSNumber *_MicrophoneWired;
}

@property(retain, nonatomic) NSNumber *MicrophoneWired; // @synthesize MicrophoneWired=_MicrophoneWired;
@property(retain, nonatomic) NSNumber *MicrophoneBuiltIn; // @synthesize MicrophoneBuiltIn=_MicrophoneBuiltIn;
@property(retain, nonatomic) NSNumber *defaultRoute; // @synthesize defaultRoute=_defaultRoute;
- (void).cxx_destruct;
- (id)asDictionary;
- (id)initWithValues:(id)arg1;
- (id)defaultRoute:(id)arg1 MicrophoneBuiltIn:(id)arg2 MicrophoneWired:(id)arg3;

@end

