//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSString;

@interface SWGTerminateCall : SWGObject
{
    NSString *_sessionKey;
}

@property(retain, nonatomic) NSString *sessionKey; // @synthesize sessionKey=_sessionKey;
- (void).cxx_destruct;
- (id)asDictionary;
- (id)initWithValues:(id)arg1;
- (id)sessionKey:(id)arg1;

@end

