//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TrialController, UIViewController;

@protocol TrialControllerDelegate <NSObject>

@optional
- (_Bool)trialControllerShouldShowTrialEnded:(TrialController *)arg1;
- (_Bool)trialControllerShouldShowTrialStarted:(TrialController *)arg1;
- (UIViewController *)trialControllerTrialEndedViewController;
@end

