//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class SPStackedNavigationController, UIViewController<SPNavigationLikeController>;

@interface UIViewController (SPStackedNavigationControllerItem)
- (_Bool)isActiveInStackedNavigation;
- (void)activateInStackedNavigationAnimated:(_Bool)arg1;
- (void)viewDidBecomeInactiveInStackedNavigation;
- (void)viewDidBecomeActiveInStackedNavigation;
@property(readonly, nonatomic) UIViewController<SPNavigationLikeController> *sp_navigationController;
@property(readonly, nonatomic) SPStackedNavigationController *stackedNavigationController;
@end

