//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString, NSURL, XAAdAudio;

@interface XAAction : NSObject <NSCopying>
{
    unsigned long long _actionType;
    NSString *_phrase;
    XAAdAudio *_trailingAudioForeground;
    XAAdAudio *_trailingAudioBackground;
    NSString *_notificationMessage;
    XAAdAudio *_audio;
    NSURL *_webURL;
    NSURL *_numberURL;
    NSURL *_downloadURL;
    NSString *_data;
}

+ (id)actionTypeAsString:(unsigned long long)arg1;
+ (unsigned long long)stringAsActionType:(id)arg1;
@property(retain, nonatomic) NSString *data; // @synthesize data=_data;
@property(retain, nonatomic) NSURL *downloadURL; // @synthesize downloadURL=_downloadURL;
@property(retain, nonatomic) NSURL *numberURL; // @synthesize numberURL=_numberURL;
@property(retain, nonatomic) NSURL *webURL; // @synthesize webURL=_webURL;
@property(retain, nonatomic) XAAdAudio *audio; // @synthesize audio=_audio;
@property(retain, nonatomic) NSString *notificationMessage; // @synthesize notificationMessage=_notificationMessage;
@property(retain, nonatomic) XAAdAudio *trailingAudioBackground; // @synthesize trailingAudioBackground=_trailingAudioBackground;
@property(retain, nonatomic) XAAdAudio *trailingAudioForeground; // @synthesize trailingAudioForeground=_trailingAudioForeground;
@property(retain, nonatomic) NSString *phrase; // @synthesize phrase=_phrase;
@property(readonly, nonatomic) unsigned long long actionType; // @synthesize actionType=_actionType;
- (void).cxx_destruct;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)setDownloadURLWithString:(id)arg1;
- (void)setWebURLWithString:(id)arg1;
- (void)setNumberURLWithString:(id)arg1;
- (id)actionTypeAsString;
- (_Bool)isActionType:(unsigned long long)arg1;
- (id)initWithActionTypeString:(id)arg1;
- (id)initWithActionType:(unsigned long long)arg1;

@end

