//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XAAdvertisement.h"

@class NSObject<XAAdvertisementMockDelegate>;

@interface XAAdvertisementMock : XAAdvertisement
{
    _Bool _playing;
    NSObject<XAAdvertisementMockDelegate> *_delegate;
    CDUnknownBlockType _adLoadHandler;
}

@property _Bool playing; // @synthesize playing=_playing;
@property(copy, nonatomic) CDUnknownBlockType adLoadHandler; // @synthesize adLoadHandler=_adLoadHandler;
@property(retain) NSObject<XAAdvertisementMockDelegate> *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)expansionAudioLoadTimeInMilliseconds;
- (id)baseAudioLoadTimeInMilliseconds;
- (id)imageLoadTimeInMilliseconds;
- (id)totalLoadTimeInMilliseconds;
- (void)onFinishedRecording;
- (void)updateDecibel:(float)arg1;
- (void)onTellMeMore;
- (void)onRecording;
- (void)removeActionByActionType:(unsigned long long)arg1;
- (void)addAction:(id)arg1;
- (void)dismiss:(CDUnknownBlockType)arg1;
- (void)hideAd:(CDUnknownBlockType)arg1;
- (void)displayAsInTileTuner:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (void)displayAsInterstitial:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (void)resumeAudio;
- (void)pauseAudio;
- (void)stopAudio;
- (void)playExpansionAudio;
- (void)finishPrompt;
- (void)playBaseAudio;
- (_Bool)playingAudio;
- (void)cancelLoad;
- (void)onLoaded;
- (_Bool)loaded;

@end

