//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSDate, NSMutableArray, NSMutableDictionary, NSNumber, NSString;

@interface XAUserData : NSObject <NSCopying>
{
    NSString *locationDescription;
    NSMutableArray *keywords;
    NSString *email;
    NSString *firstName;
    NSString *lastName;
    NSString *streetAddress;
    NSString *city;
    NSString *state;
    NSString *zipCode;
    NSString *county;
    NSString *homePhone;
    NSString *mobilePhone;
    NSString *maritalStatus;
    NSString *gender;
    NSString *education;
    NSNumber *children;
    NSString *ethnicity;
    NSString *politics;
    NSMutableDictionary *demographicData;
    NSDate *birthday;
}

@property(retain, nonatomic) NSDate *birthday; // @synthesize birthday;
@property(retain, nonatomic) NSMutableDictionary *demographicData; // @synthesize demographicData;
@property(retain, nonatomic) NSString *politics; // @synthesize politics;
@property(retain, nonatomic) NSString *ethnicity; // @synthesize ethnicity;
@property(retain, nonatomic) NSNumber *children; // @synthesize children;
@property(retain, nonatomic) NSString *education; // @synthesize education;
@property(retain, nonatomic) NSString *gender; // @synthesize gender;
@property(retain, nonatomic) NSString *maritalStatus; // @synthesize maritalStatus;
@property(retain, nonatomic) NSString *mobilePhone; // @synthesize mobilePhone;
@property(retain, nonatomic) NSString *homePhone; // @synthesize homePhone;
@property(retain, nonatomic) NSString *county; // @synthesize county;
@property(retain, nonatomic) NSString *zipCode; // @synthesize zipCode;
@property(retain, nonatomic) NSString *state; // @synthesize state;
@property(retain, nonatomic) NSString *city; // @synthesize city;
@property(retain, nonatomic) NSString *streetAddress; // @synthesize streetAddress;
@property(retain, nonatomic) NSString *lastName; // @synthesize lastName;
@property(retain, nonatomic) NSString *firstName; // @synthesize firstName;
@property(retain, nonatomic) NSString *email; // @synthesize email;
@property(retain, nonatomic) NSMutableArray *keywords; // @synthesize keywords;
@property(retain) NSString *locationDescription; // @synthesize locationDescription;
- (void).cxx_destruct;
- (id)description;
- (id)keywordsAsCommaDelimitedString;
- (void)addKeyword:(id)arg1;
- (void)setBirthdayWithAge:(long long)arg1;
- (void)setBirthdayWithMonth:(long long)arg1 day:(long long)arg2 year:(long long)arg3;
- (void)addDemographicData:(id)arg1 forKey:(id)arg2;
- (void)setLocationWithDescription:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

