//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface XAXMReflectionUtil : NSObject
{
}

+ (void)setValues:(id)arg1 onInstance:(id)arg2;

@end

