//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIAppearance.h"

@class CAGradientLayer, NSString, UIColor;

@interface XKMeterView : UIView <UIAppearance>
{
    UIColor *_trackTintColor;
    UIColor *_progressTintColor;
    struct CGPath *_shape;
    double _progress;
}

+ (id)intersectionPointsOfLineOrientedBy:(double)arg1 withBox:(struct CGRect)arg2;
+ (Class)layerClass;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(nonatomic) struct CGPath *shape; // @synthesize shape=_shape;
@property(retain, nonatomic) UIColor *progressTintColor; // @synthesize progressTintColor=_progressTintColor;
@property(retain, nonatomic) UIColor *trackTintColor; // @synthesize trackTintColor=_trackTintColor;
- (void).cxx_destruct;
- (void)setProgress:(double)arg1 animated:(_Bool)arg2;
- (void)setGradientOrientationAngle:(double)arg1;
- (id)gradientPoints:(double)arg1;
- (double)gradientOrientationAngle;
- (id)gradientLocations:(double)arg1;
- (double)rescaledProgress:(double)arg1;
- (void)updateGradientColors;
- (struct CGRect)shapeBounds;
- (void)didMoveToWindow;
- (void)setup;
- (id)initWithFrame:(struct CGRect)arg1 shape:(struct CGPath *)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
@property(readonly, nonatomic) CAGradientLayer *gradientLayer;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

