//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XVRSpeechRecognitionStrategy.h"

@class NSArray, NSString;

@interface XVRChainedSpeechRecognitionStrategy : NSObject <XVRSpeechRecognitionStrategy>
{
    NSArray *_strategies;
}

@property(retain, nonatomic) NSArray *strategies; // @synthesize strategies=_strategies;
- (void).cxx_destruct;
- (id)execute:(id)arg1 forActions:(id)arg2 withThreshold:(double)arg3 withAdditionalParameters:(id)arg4;
- (id)initWithStrategies:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

