//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate;

@interface XVRSpeechData : NSObject
{
    NSDate *_time;
    id _data;
    long long _type;
}

@property(readonly, nonatomic) long long type; // @synthesize type=_type;
@property(readonly, nonatomic) id data; // @synthesize data=_data;
@property(readonly, nonatomic) NSDate *time; // @synthesize time=_time;
- (void).cxx_destruct;
- (id)initWithData:(id)arg1 type:(long long)arg2 time:(id)arg3;

@end

