//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, XVRSpeechRecognitionResult;

@protocol XVRSpeechRecognitionStrategy <NSObject>
- (XVRSpeechRecognitionResult *)execute:(id)arg1 forActions:(NSArray *)arg2 withThreshold:(double)arg3 withAdditionalParameters:(NSArray *)arg4;
@end

