//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class ADJActivityPackage, NSDictionary, NSNumber;

@protocol ADJAttributionHandler
- (void)getAttribution;
- (void)checkAttribution:(NSDictionary *)arg1;
- (id)initWithActivityHandler:(id <ADJActivityHandler>)arg1 withMaxDelay:(NSNumber *)arg2 withAttributionPackage:(ADJActivityPackage *)arg3;
@end

