//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CSStorage : NSObject
{
    BOOL enabled;
}

@property BOOL enabled; // @synthesize enabled;
- (void)dealloc;
- (void)add:(id)arg1 value:(long long)arg2;
- (void)persist;
- (BOOL)getBool:(id)arg1;
- (void)setBool:(id)arg1:(BOOL)arg2;
- (void)set:(id)arg1:(id)arg2;
- (id)get:(id)arg1;
- (BOOL)has:(id)arg1;
- (void)clear;
- (id)init;

@end

