//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSTimer;

@interface DeviceStatisticsLogger : NSObject
{
    NSTimer *_logTimer;
    int _countDown;
    NSMutableArray *_statistics;
    float _lastBatteryLevel;
}

+ (id)sharedDeviceStatisticsLogger;
+ (void)load;
@property(nonatomic) float lastBatteryLevel; // @synthesize lastBatteryLevel=_lastBatteryLevel;
@property(retain, nonatomic) NSMutableArray *statistics; // @synthesize statistics=_statistics;
@property(nonatomic) int countDown; // @synthesize countDown=_countDown;
@property(retain, nonatomic) NSTimer *logTimer; // @synthesize logTimer=_logTimer;
- (void).cxx_destruct;
- (void)timerFired:(id)arg1;
- (int)randomMinute;
- (unsigned long long)deviceFreeSpace:(id *)arg1;
- (unsigned long long)appSpaceUsage:(id *)arg1;
- (unsigned int)deviceFreeMemory:(id *)arg1;
- (unsigned int)appMemoryUsage:(id *)arg1;
- (float)appCPUUsage:(id *)arg1;
- (void)pause;
- (void)resume;
- (id)init;

@end

