//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FollowData, NSHashTable, NSNumberFormatter, NSString;

@interface FollowModel : NSObject
{
    FollowData *_data;
    NSNumberFormatter *_decimalNumberFormatter;
    id <SPTResolver> _resolver;
    NSHashTable *_observers;
    NSString *_currentUsername;
}

+ (id)userOrArtistURIString:(id)arg1;
+ (id)createSocialGraphRequestPayloadWithFollowData:(id)arg1;
+ (id)parseResponse:(id)arg1 error:(id *)arg2;
+ (void)loadFollowModelForCurrentUsername:(id)arg1 targetArtistURI:(id)arg2 withResolver:(id)arg3 completion:(CDUnknownBlockType)arg4;
@property(retain, nonatomic) NSString *currentUsername; // @synthesize currentUsername=_currentUsername;
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) id <SPTResolver> resolver; // @synthesize resolver=_resolver;
@property(retain, nonatomic) NSNumberFormatter *decimalNumberFormatter; // @synthesize decimalNumberFormatter=_decimalNumberFormatter;
@property(retain, nonatomic) FollowData *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (void)invokeObserversWithError:(id)arg1;
- (void)invokeObserversWithData:(id)arg1;
- (id)broadcastEndpoint;
- (id)followDataFromBroadcast:(id)arg1;
- (void)broadcastUpdatedFollowData:(id)arg1;
- (void)startListeningToFollowStateBroadcasts;
- (void)updateFollowState:(id)arg1;
- (void)toggleFollowDataOptimistically;
- (BOOL)isCurrentUser;
@property(readonly, nonatomic) NSString *followingsFormattedString;
@property(readonly, nonatomic) NSString *followersFormattedString;
- (void)toggleFollowState;
- (void)addObserver:(id)arg1;
- (id)initWithResolver:(id)arg1 currentUsername:(id)arg2;
- (id)initWithResolver:(id)arg1 initialFollowData:(id)arg2 currentUsername:(id)arg3;

@end

