//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IDApplicationDataSource.h"
#import "IDApplicationDelegate.h"
#import "IDTableDelegate.h"

@class IDApplication, IDRhmiFeatureInfoFilter, IDRhmiFeatureSwitcherViewControllerConfiguration, IDRhmiSubmenu, NSSet, NSString;

@interface IDRhmiFeatureSwitcherViewController : NSObject <IDApplicationDataSource, IDApplicationDelegate, IDTableDelegate>
{
    NSSet *_featureInfos;
    IDRhmiFeatureSwitcherViewControllerConfiguration *_configuration;
    int _hmiLanguage;
    IDApplication *_application;
    id _willResignActiveNotificationObserver;
    id _didBecomeActiveNotificationObserver;
}

@property(retain) id didBecomeActiveNotificationObserver; // @synthesize didBecomeActiveNotificationObserver=_didBecomeActiveNotificationObserver;
@property(retain) id willResignActiveNotificationObserver; // @synthesize willResignActiveNotificationObserver=_willResignActiveNotificationObserver;
@property(retain) IDApplication *application; // @synthesize application=_application;
@property int hmiLanguage; // @synthesize hmiLanguage=_hmiLanguage;
@property(retain) IDRhmiFeatureSwitcherViewControllerConfiguration *configuration; // @synthesize configuration=_configuration;
@property(retain) NSSet *featureInfos; // @synthesize featureInfos=_featureInfos;
- (void).cxx_destruct;
- (BOOL)shouldShowSwitcherNotAvailableHint;
- (void)table:(id)arg1 didSelectItemAtIndex:(int)arg2;
- (void)onUpdateLanguage:(id)arg1;
- (id)imageDatabasesForApplication:(id)arg1;
- (id)textDatabasesForApplication:(id)arg1;
- (id)hmiDescriptionForApplication:(id)arg1;
- (id)manifestForApplication:(id)arg1;
- (void)applicationDidStart:(id)arg1;
- (void)applicationRestoreMainHmiState:(id)arg1;
- (void)updateUI;
- (void)update:(id)arg1;
- (void)stopWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)startWithFeatureInfos:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
@property(readonly) IDRhmiFeatureInfoFilter *featureInfosFilter;
@property(readonly) IDRhmiSubmenu *submenu;
- (void)dealloc;
- (id)initWithConfiguration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

