//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IDWidget.h"

@class IDModel, IDView, NSMutableDictionary, NSString, NSTimer;

@interface IDTable : IDWidget
{
    BOOL _targetHmiStateIdDirty;
    BOOL _columnWidthsDirty;
    BOOL _tableCutTypeDirty;
    BOOL _tableDirty;
    BOOL _selectedRowDirty;
    id <IDTableDelegate> _delegate;
    IDView *_targetView;
    IDModel *_tableModel;
    int _actionId;
    int _focusActionId;
    IDModel *_targetModel;
    int _targetHmiStateId;
    NSString *_columnWidthsString;
    unsigned int _tableCutType;
    int _rows;
    int _cols;
    NSMutableDictionary *_cells;
    NSTimer *_timer;
    int _selectedRow;
}

@property BOOL selectedRowDirty; // @synthesize selectedRowDirty=_selectedRowDirty;
@property int selectedRow; // @synthesize selectedRow=_selectedRow;
@property(retain) NSTimer *timer; // @synthesize timer=_timer;
@property BOOL tableDirty; // @synthesize tableDirty=_tableDirty;
@property(retain) NSMutableDictionary *cells; // @synthesize cells=_cells;
@property int cols; // @synthesize cols=_cols;
@property int rows; // @synthesize rows=_rows;
@property BOOL tableCutTypeDirty; // @synthesize tableCutTypeDirty=_tableCutTypeDirty;
@property unsigned int tableCutType; // @synthesize tableCutType=_tableCutType;
@property BOOL columnWidthsDirty; // @synthesize columnWidthsDirty=_columnWidthsDirty;
@property(retain) NSString *columnWidthsString; // @synthesize columnWidthsString=_columnWidthsString;
@property BOOL targetHmiStateIdDirty; // @synthesize targetHmiStateIdDirty=_targetHmiStateIdDirty;
@property int targetHmiStateId; // @synthesize targetHmiStateId=_targetHmiStateId;
@property(readonly) IDModel *targetModel; // @synthesize targetModel=_targetModel;
@property int focusActionId; // @synthesize focusActionId=_focusActionId;
@property int actionId; // @synthesize actionId=_actionId;
@property(readonly, nonatomic) IDModel *tableModel; // @synthesize tableModel=_tableModel;
@property(nonatomic) IDView *targetView; // @synthesize targetView=_targetView;
@property __weak id <IDTableDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setVisible:(BOOL)arg1;
- (void)focus;
- (void)flushTarget;
- (void)flushTableCells:(int)arg1;
- (void)flushTableContent:(int)arg1;
- (void)flush:(int)arg1;
- (void)setCutType:(unsigned int)arg1;
- (void)setColumnWidths:(id)arg1;
- (void)setCell:(id)arg1 atRow:(int)arg2 column:(int)arg3;
- (void)setRowCount:(int)arg1 columnCount:(int)arg2;
- (void)removeAllCells;
- (void)focusRow:(int)arg1;
- (void)hmiDidStopForApplication:(id)arg1;
- (void)hmiDidStartForApplication:(id)arg1;
- (id)initWithWidgetId:(int)arg1;
- (id)initWithWidgetId:(int)arg1 model:(id)arg2 targetModel:(id)arg3 actionId:(int)arg4 focusId:(int)arg5;
- (id)initWithWidgetId:(int)arg1 tableModel:(id)arg2 targetModel:(id)arg3 actionId:(int)arg4 focusId:(int)arg5;
- (void)sendEmptyTable;
- (void)setNeedsFlush;
- (void)rowFocused:(id)arg1;
- (void)rowSelected:(id)arg1;
- (void)flushFromColumn:(int)arg1 countOfColumns:(int)arg2 fromRow:(int)arg3 countOfRows:(int)arg4;
- (void)flushColumns:(id)arg1 fromRow:(int)arg2 countOfRows:(int)arg3;
- (id)columnNumbersNeedsFlushForSpeed:(int)arg1 inRow:(int)arg2;

@end

