//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "InAppPurchaseController.h"
#import "SKPaymentTransactionObserver.h"
#import "SKProductsRequestDelegate.h"
#import "SPTDataLoaderDelegate.h"
#import "SPTProductStateObserver.h"

@class InAppPurchaseModel, NSMutableArray, NSString, NSTimer, SKProductsRequest, SPApHermesController, SPSession, SPTDataLoader, SPTLogCenter, SPTProductStateMonitorController, TrialController;

@interface InAppPurchaseControllerImplementation : NSObject <SKPaymentTransactionObserver, SKProductsRequestDelegate, SPTProductStateObserver, SPTDataLoaderDelegate, InAppPurchaseController>
{
    BOOL _verifyingReceipt;
    BOOL _displayedVerificationError;
    InAppPurchaseModel *_model;
    SKProductsRequest *_productsRequest;
    SPSession *_session;
    SPApHermesController *_hermes;
    id <SPTLocalSettings> _localSettings;
    TrialController *_trialController;
    id <UpsellFeature> _upsellFeature;
    id <SPTProductState> _productState;
    SPTProductStateMonitorController *_productStateMonitorController;
    SPTLogCenter *_logCenter;
    SPTDataLoader *_dataLoader;
    id <SPTHTTPTestManager> _httpTestManager;
    CDUnknownBlockType _purchaseCallback;
    NSMutableArray *_storeProductsCallbacks;
    NSTimer *_verifyRetryTimer;
}

@property(nonatomic) BOOL displayedVerificationError; // @synthesize displayedVerificationError=_displayedVerificationError;
@property(nonatomic, getter=isVerifyingReceipt) BOOL verifyingReceipt; // @synthesize verifyingReceipt=_verifyingReceipt;
@property(retain, nonatomic) NSTimer *verifyRetryTimer; // @synthesize verifyRetryTimer=_verifyRetryTimer;
@property(copy, nonatomic) NSMutableArray *storeProductsCallbacks; // @synthesize storeProductsCallbacks=_storeProductsCallbacks;
@property(copy, nonatomic) CDUnknownBlockType purchaseCallback; // @synthesize purchaseCallback=_purchaseCallback;
@property(retain, nonatomic) id <SPTHTTPTestManager> httpTestManager; // @synthesize httpTestManager=_httpTestManager;
@property(retain, nonatomic) SPTDataLoader *dataLoader; // @synthesize dataLoader=_dataLoader;
@property(retain, nonatomic) SPTLogCenter *logCenter; // @synthesize logCenter=_logCenter;
@property(nonatomic) __weak SPTProductStateMonitorController *productStateMonitorController; // @synthesize productStateMonitorController=_productStateMonitorController;
@property(retain, nonatomic) id <SPTProductState> productState; // @synthesize productState=_productState;
@property(nonatomic) __weak id <UpsellFeature> upsellFeature; // @synthesize upsellFeature=_upsellFeature;
@property(retain, nonatomic) TrialController *trialController; // @synthesize trialController=_trialController;
@property(retain, nonatomic) id <SPTLocalSettings> localSettings; // @synthesize localSettings=_localSettings;
@property(retain, nonatomic) SPApHermesController *hermes; // @synthesize hermes=_hermes;
@property(nonatomic) __weak SPSession *session; // @synthesize session=_session;
@property(retain, nonatomic) SKProductsRequest *productsRequest; // @synthesize productsRequest=_productsRequest;
@property(retain, nonatomic) InAppPurchaseModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
@property(readonly, nonatomic) int currentTransport;
- (void)dataLoader:(id)arg1 didCancelRequest:(id)arg2;
- (void)dataLoader:(id)arg1 didReceiveErrorResponse:(id)arg2;
- (void)dataLoader:(id)arg1 didReceiveSuccessfulResponse:(id)arg2;
- (void)productState:(id)arg1 stateDidChange:(id)arg2;
- (void)logEvent:(id)arg1 source:(id)arg2 context:(id)arg3 userInfo:(id)arg4;
@property(readonly, copy, nonatomic) NSString *clientLoggingSource;
- (void)handleProductAvailability:(BOOL)arg1;
- (void)cleanUpAfterPurchase;
- (void)transactionFailed:(id)arg1;
- (id)reasonFromError:(id)arg1;
- (void)handlePaymentVerification:(id)arg1 error:(id)arg2 showLoading:(BOOL)arg3;
- (void)verifyTransactionReceipt:(id)arg1 showLoading:(BOOL)arg2;
- (void)verifyStoredTransactionReceipt;
- (void)startRetryVerifyReceiptTimer;
- (void)transactionPurchased:(id)arg1;
- (void)handleAvailableProductsResponse:(id)arg1 error:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)attemptPurchaseWithProduct:(id)arg1;
- (void)productsRequest:(id)arg1 didReceiveResponse:(id)arg2;
- (void)fetchInAppPurchaseProductInformationWithCallback:(CDUnknownBlockType)arg1;
- (void)paymentQueue:(id)arg1 updatedTransactions:(id)arg2;
- (void)purchasePremiumProductWithCallback:(CDUnknownBlockType)arg1;
- (void)purchasePremiumProduct;
- (void)loadAvailableProductsWithCallback:(CDUnknownBlockType)arg1;
- (void)handleAvailabilityCheckResponseWithCallback:(CDUnknownBlockType)arg1;
- (void)checkPremiumProductAvailabilityWithCallback:(CDUnknownBlockType)arg1;
- (BOOL)isPremiumProductAvailable;
@property(readonly, nonatomic, getter=isPremiumUser) BOOL premiumUser;
- (id)localizedPremiumProductPrice;
- (void)clearSettings;
- (void)dealloc;
- (id)initWithSession:(id)arg1 hermes:(id)arg2 localSettings:(id)arg3 productState:(id)arg4 productStateMonitorController:(id)arg5 trialController:(id)arg6 upsellFeature:(id)arg7 logCenter:(id)arg8 dataLoader:(id)arg9 httpTestManager:(id)arg10;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

