//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "LoginPLIStatusRequestDelegate.h"

@class LoginPLIRetryPolicy, LoginPLIStatusRequest, NSString, NSURL;

@interface LoginPLIController : NSObject <LoginPLIStatusRequestDelegate>
{
    BOOL _shouldShowPLIInsteadOfSignup;
    BOOL _shouldShowPLIInsteadOfWelcome;
    id <LoginPLIControllerDelegate> _delegate;
    NSURL *_URLForPLI;
    NSURL *_endpointURL;
    LoginPLIStatusRequest *_statusRequest;
    LoginPLIRetryPolicy *_statusRetryPolicy;
}

@property(retain, nonatomic) LoginPLIRetryPolicy *statusRetryPolicy; // @synthesize statusRetryPolicy=_statusRetryPolicy;
@property(retain, nonatomic) LoginPLIStatusRequest *statusRequest; // @synthesize statusRequest=_statusRequest;
@property(copy, nonatomic) NSURL *endpointURL; // @synthesize endpointURL=_endpointURL;
@property(copy, nonatomic) NSURL *URLForPLI; // @synthesize URLForPLI=_URLForPLI;
@property(nonatomic) BOOL shouldShowPLIInsteadOfWelcome; // @synthesize shouldShowPLIInsteadOfWelcome=_shouldShowPLIInsteadOfWelcome;
@property(nonatomic) BOOL shouldShowPLIInsteadOfSignup; // @synthesize shouldShowPLIInsteadOfSignup=_shouldShowPLIInsteadOfSignup;
@property(nonatomic) __weak id <LoginPLIControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)loginPLIStatusRequest:(id)arg1 didFailWithError:(id)arg2;
- (void)loginPLIStatusRequest:(id)arg1 didCompleteWithLoginPLIModel:(id)arg2;
- (void)removeSpotCookie;
- (void)loadSpotCookie;
- (void)saveSpotCookie;
- (void)archiveCurrentState:(id)arg1;
- (void)archiveCurrentState;
- (void)loadArchivedState:(id)arg1;
- (void)loadArchivedState;
- (id)userDefaultsForPersistentState;
- (void)tryFetchingStatus;
- (void)updatePLIStatusFromRemoteService;
- (void)updatePLIStatusFromModel:(id)arg1;
- (void)userDidCompleteLogin;
- (void)userDidSignPLI;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

