//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MPAbstractABTestDesignerMessage.h"

@class NSString;

@interface MPABTestDesignerClearResponseMessage : MPAbstractABTestDesignerMessage
{
}

+ (id)message;
@property(copy, nonatomic) NSString *status;

@end

