//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSMutableArray, NSMutableOrderedSet;

@interface MPVariant : NSObject <NSCoding>
{
    BOOL _running;
    BOOL _finished;
    unsigned int _ID;
    unsigned int _experimentID;
    NSMutableOrderedSet *_actions;
    NSMutableArray *_tweaks;
}

+ (id)variantWithJSONObject:(id)arg1;
@property(retain, nonatomic) NSMutableArray *tweaks; // @synthesize tweaks=_tweaks;
@property(retain, nonatomic) NSMutableOrderedSet *actions; // @synthesize actions=_actions;
@property(readonly, nonatomic) BOOL finished; // @synthesize finished=_finished;
@property(readonly, nonatomic) BOOL running; // @synthesize running=_running;
@property(nonatomic) unsigned int experimentID; // @synthesize experimentID=_experimentID;
@property(nonatomic) unsigned int ID; // @synthesize ID=_ID;
- (void).cxx_destruct;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isEqualToVariant:(id)arg1;
- (void)restart;
- (void)finish;
- (void)stop;
- (void)execute;
- (void)addTweakFromJSONObject:(id)arg1 andExecute:(BOOL)arg2;
- (void)addTweaksFromJSONObject:(id)arg1 andExecute:(BOOL)arg2;
- (void)removeActionWithName:(id)arg1;
- (void)addActionFromJSONObject:(id)arg1 andExecute:(BOOL)arg2;
- (void)addActionsFromJSONObject:(id)arg1 andExecute:(BOOL)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithID:(unsigned int)arg1 experimentID:(unsigned int)arg2 actions:(id)arg3 tweaks:(id)arg4;
- (id)init;

@end

