//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SettingsViewController.h"

#import "SPTGaiaDeviceStateManagerObserver.h"
#import "UITableViewDelegate.h"

@class LoginStateController, NSArray, NSMutableArray, NSString, SPKVObservation, SettingsErrorHeaderView;

@interface RootSettingsViewController : SettingsViewController <SPTGaiaDeviceStateManagerObserver, UITableViewDelegate>
{
    BOOL _isPlayingRemotely;
    SPKVObservation *_errorObservation;
    SettingsErrorHeaderView *_errorHeaderView;
    LoginStateController *_loginStateController;
    NSMutableArray *_settingsSectionsForConnectObserving;
    NSArray *_settingsSectionsForLocalPlayback;
    id <GaiaFeature> _gaia;
    int _disabledSettingsIndex;
}

+ (id)rootSettingsViewControllerWithDictionaryRepresentation:(id)arg1 loginStateController:(id)arg2 gaia:(id)arg3;
@property(nonatomic) int disabledSettingsIndex; // @synthesize disabledSettingsIndex=_disabledSettingsIndex;
@property(nonatomic) BOOL isPlayingRemotely; // @synthesize isPlayingRemotely=_isPlayingRemotely;
@property(nonatomic) __weak id <GaiaFeature> gaia; // @synthesize gaia=_gaia;
@property(retain, nonatomic) NSArray *settingsSectionsForLocalPlayback; // @synthesize settingsSectionsForLocalPlayback=_settingsSectionsForLocalPlayback;
@property(retain, nonatomic) NSMutableArray *settingsSectionsForConnectObserving; // @synthesize settingsSectionsForConnectObserving=_settingsSectionsForConnectObserving;
@property(nonatomic) __weak LoginStateController *loginStateController; // @synthesize loginStateController=_loginStateController;
@property(retain, nonatomic) SettingsErrorHeaderView *errorHeaderView; // @synthesize errorHeaderView=_errorHeaderView;
@property(retain, nonatomic) SPKVObservation *errorObservation; // @synthesize errorObservation=_errorObservation;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 viewForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)rebuildSettingsSections;
- (void)viewWillAppear:(BOOL)arg1;
- (void)lastConnectionErrorChanged;
- (void)loadView;
- (void)deviceStateManager:(id)arg1 activeDeviceDidChange:(id)arg2;
- (id)initWithDictionaryRepresentation:(id)arg1 loginStateController:(id)arg2 gaia:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

