//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SettingsRegistry.h"

@class NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSString;

@interface SettingsRegistryImplementation : NSObject <SettingsRegistry>
{
    NSMutableDictionary *_providers;
    NSMutableDictionary *_rootSections;
    NSMutableDictionary *_rootSectionProviders;
    NSMutableArray *_mutableFeatureSettingsPages;
    NSMutableDictionary *_mutableTitles;
}

@property(retain, nonatomic) NSMutableDictionary *mutableTitles; // @synthesize mutableTitles=_mutableTitles;
@property(retain, nonatomic) NSMutableArray *mutableFeatureSettingsPages; // @synthesize mutableFeatureSettingsPages=_mutableFeatureSettingsPages;
@property(readonly, nonatomic) NSMutableDictionary *rootSectionProviders; // @synthesize rootSectionProviders=_rootSectionProviders;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSDictionary *titles;
@property(readonly, nonatomic) NSMutableDictionary *rootSections;
@property(readonly, nonatomic) NSMutableDictionary *providers;
- (void)registerTitle:(id)arg1 forURI:(id)arg2;
@property(readonly, nonatomic) __weak NSArray *featureSettingsPages;
- (void)registerFeatureSettingsPage:(id)arg1;
- (void)registerSettingsSectionProvider:(id)arg1 withSelector:(SEL)arg2 forURI:(id)arg3;
- (void)registerRootSettingsSectionProvider:(id)arg1 withSelector:(SEL)arg2 forURI:(id)arg3;
- (void)registerRootSettingsURI:(id)arg1 title:(id)arg2 viewControllerClass:(Class)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

