//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTFeature.h"
#import "SettingsFeature.h"

@class NSMutableDictionary, NSString, RootSettingsViewController, SPTAllocationContext, SettingsRegistryImplementation;

@interface SettingsFeatureImplementation : NSObject <SPTFeature, SettingsFeature>
{
    id <BaseFeature> _base;
    id <UpsellFeature> _upsell;
    id <LoginFeature> _login;
    id <GaiaFeature> _gaia;
    NSMutableDictionary *_settingsStructure;
    SettingsRegistryImplementation *_settingsRegistry;
    RootSettingsViewController *_settingsViewController;
}

+ (id)featureDependencies;
+ (id)featureIdentifier;
@property(retain, nonatomic) RootSettingsViewController *settingsViewController; // @synthesize settingsViewController=_settingsViewController;
@property(retain, nonatomic) SettingsRegistryImplementation *settingsRegistry; // @synthesize settingsRegistry=_settingsRegistry;
@property(retain, nonatomic) NSMutableDictionary *settingsStructure; // @synthesize settingsStructure=_settingsStructure;
@property(nonatomic) __weak id <GaiaFeature> gaia; // @synthesize gaia=_gaia;
@property(nonatomic) __weak id <LoginFeature> login; // @synthesize login=_login;
@property(nonatomic) __weak id <UpsellFeature> upsell; // @synthesize upsell=_upsell;
@property(nonatomic) __weak id <BaseFeature> base; // @synthesize base=_base;
- (void).cxx_destruct;
- (id)provideOfflineSettingsSectionWithSettingsViewController:(id)arg1;
- (id)provideUnplayableTracksSettingsWithSettingsViewController:(id)arg1;
- (id)provideGaplessSettingsWithSettingsViewController:(id)arg1;
- (id)provideCellularSyncSettingsWithSettingsViewController:(id)arg1;
- (id)provideSyncQualitySettingsWithSettingsViewController:(id)arg1;
- (id)provideStreamQualitySettingsWithSettingsViewController:(id)arg1;
- (id)provideSettingsRegistry;
- (id)provideSectionViewControllerWithURL:(id)arg1;
- (id)provideSettingsViewControllerPad;
- (id)provideSettingsViewControllerPhone;
- (id)containerInTree:(id)arg1 withURI:(id)arg2;
- (void)unload;
- (void)load;
- (void)configureWithFeatures:(id)arg1;

// Remaining properties
@property(retain, nonatomic) SPTAllocationContext *allocationContext;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

