//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@interface SPArtist : NSObject
{
    struct RefPtr<const sp::ArtistInfo> _cppObject;
}

+ (id)artistWithArtistInfo:(const struct ArtistInfo *)arg1;
+ (BOOL)artistIsBlocked:(id)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
- (const struct ArtistInfo *)artistInfo;
- (unsigned int)hash;
@property(readonly, nonatomic) BOOL isBlocked;
@property(readonly, nonatomic) int popularity;
@property(readonly, nonatomic) NSURL *link;
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic, getter=isLoaded) BOOL loaded;
- (struct ArtistId)id;
- (id)imageLinkOfSize:(int)arg1;
@property(readonly, nonatomic) NSURL *portraitImageLink;

@end

