//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Spotify : NSObject
{
}

+ (id)prefs;
+ (id)metaVC;
+ (void)setupCoreWithAudioDriverController:(id)arg1;
+ (id)createCoreCreateOptions;
+ (void)deleteDeviceID;
+ (id)deviceID;
+ (id)settingsPath;
+ (id)persistentCachePath;
+ (id)volatileCachePath;
+ (id)persistentCacheRoot;
+ (id)volatileCacheRoot;
+ (void)markForBackupExclusion:(id)arg1;
+ (void)migrateCachesFromPath:(id)arg1 persistentPath:(id)arg2 volatilePath:(id)arg3;
+ (id)legacyCachePath;
+ (void)createAndMigratePathsForPersistentCache:(id)arg1 volatileCache:(id)arg2 settings:(id)arg3;
- (id)deviceID;

@end

