//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PageRegistry.h"

@class NSMutableArray, NSString, SPTUserActivityController;

@interface SPPageFactory : NSObject <PageRegistry>
{
    NSMutableArray *_featureRegistrations;
    int _idiom;
    SPTUserActivityController *_userActivityController;
}

+ (id)sharedFactory;
@property(readonly, nonatomic) SPTUserActivityController *userActivityController; // @synthesize userActivityController=_userActivityController;
- (void).cxx_destruct;
- (BOOL)restoreUserActivity:(id)arg1 restorationHandler:(CDUnknownBlockType)arg2;
- (void)updateUserActivity:(id)arg1;
- (void)unregisterFeaturePages;
- (id)pageForURL:(id)arg1;
- (void)registerPageSelector:(SEL)arg1 target:(id)arg2 predicate:(CDUnknownBlockType)arg3;
- (void)registerPageSelector:(SEL)arg1 target:(id)arg2 idiom:(int)arg3 predicate:(CDUnknownBlockType)arg4;
- (id)initWithInterfaceIdiom:(int)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

