//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPPlaylistOfflineSyncStatus : NSObject
{
    BOOL _isCurrentlySyncing;
    int _tracksDone;
    int _tracksLeft;
    int _tracksTotal;
    unsigned int _currentBytesPerSecond;
    float _progress;
    float _byteProgress;
    int _secondsLeft;
}

@property(nonatomic) int secondsLeft; // @synthesize secondsLeft=_secondsLeft;
@property(nonatomic) float byteProgress; // @synthesize byteProgress=_byteProgress;
@property(nonatomic) float progress; // @synthesize progress=_progress;
@property(nonatomic) unsigned int currentBytesPerSecond; // @synthesize currentBytesPerSecond=_currentBytesPerSecond;
@property(nonatomic) BOOL isCurrentlySyncing; // @synthesize isCurrentlySyncing=_isCurrentlySyncing;
@property(nonatomic) int tracksTotal; // @synthesize tracksTotal=_tracksTotal;
@property(nonatomic) int tracksLeft; // @synthesize tracksLeft=_tracksLeft;
@property(nonatomic) int tracksDone; // @synthesize tracksDone=_tracksDone;
- (void)fromPlaylists:(id)arg1;
- (void)fromSyncProgressInfo:(struct SyncProgressInfo *)arg1;

@end

