//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSError;

@protocol SPTApolloDataLoaderDelegate <NSObject>
- (void)apolloDataLoader:(id <SPTApolloDataLoader>)arg1 didEncounterError:(NSError *)arg2 forRequestWithToken:(id <SPTApolloDataLoaderRequestToken>)arg3;
- (void)apolloDataLoader:(id <SPTApolloDataLoader>)arg1 didLoadData:(NSDictionary *)arg2 forRequestWithToken:(id <SPTApolloDataLoaderRequestToken>)arg3;
@end

