//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTAdsBaseViewController.h"

@class SPTImageBlurView, UIButton<SPTNowPlayingBarPlayButton>, UIImageView, UILabel;

@interface SPTAdsBarViewController : SPTAdsBaseViewController
{
    id <SPTAdsViewControllerDelegate> _controlDelegate;
    SPTImageBlurView *_blurImageView;
    UIImageView *_cornerImageView;
    UILabel *_titleView;
    UIButton<SPTNowPlayingBarPlayButton> *_playPauseButton;
}

@property(retain, nonatomic) UIButton<SPTNowPlayingBarPlayButton> *playPauseButton; // @synthesize playPauseButton=_playPauseButton;
@property(retain, nonatomic) UILabel *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) UIImageView *cornerImageView; // @synthesize cornerImageView=_cornerImageView;
@property(retain, nonatomic) SPTImageBlurView *blurImageView; // @synthesize blurImageView=_blurImageView;
@property(nonatomic) __weak id <SPTAdsViewControllerDelegate> controlDelegate; // @synthesize controlDelegate=_controlDelegate;
- (void).cxx_destruct;
- (void)handleTap;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)updatePlayButtonState;
- (void)updateTitle:(id)arg1 image:(id)arg2;
- (void)updateViewConstraints;
- (void)setupView;
- (id)initWithViewModel:(id)arg1;

@end

