//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIImage;

@protocol SPTBMWListScreen <NSObject>
@property(nonatomic) __weak id <SPTBMWListScreenDelegate> delegate;
- (void)screenDidAppear;
- (void)screenDidDisappear;
- (void)rowWasClicked:(int)arg1 inGroup:(int)arg2;
- (NSString *)getTitle;
- (NSString *)getLoadingLabel;
- (int)getTargetScreenForRow:(int)arg1 forGroup:(int)arg2;
- (UIImage *)getImageForRow:(int)arg1 forGroup:(int)arg2 withPreferredSize:(struct CGSize)arg3;
- (NSString *)getStringForLine:(int)arg1 forRow:(int)arg2 forGroup:(int)arg3;
- (int)getItemCountForGroup:(int)arg1;
- (int)getGroupCount;
- (NSString *)getGroupLabelForGroup:(int)arg1;
- (BOOL)canProvideDataImmediately;
@end

