//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

#import "SPSidebarScrollDisabler.h"
#import "SPTBrowsePlaylistChangedResponder.h"
#import "SPTImageLoaderDelegate.h"
#import "SPTThemableView.h"
#import "SPTTouchViewEngineDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UIScrollViewDelegate.h"

@class CAGradientLayer, NSArray, NSString, NSURL, SPTBrowseABTestsManager, SPTBrowseFeaturedPlaylistsRequest, SPTBrowseOverviewHeaderShortcutsView, SPTBrowseParallaxBackground, SPTCollectionView, UILabel, UIView;

@interface SPTBrowseOverviewHeaderView : UICollectionReusableView <UICollectionViewDelegate, UICollectionViewDataSource, SPTImageLoaderDelegate, UIScrollViewDelegate, SPTTouchViewEngineDelegate, SPTBrowsePlaylistChangedResponder, SPSidebarScrollDisabler, SPTThemableView>
{
    BOOL _chartsFeatureEnabled;
    BOOL _spokenWordShortcutEnabled;
    BOOL _hasSetupFeaturedPlaylistModel;
    id <SPTThemableViewLayoutDelegate> _layoutDelegate;
    id <SPTBrowseHeaderDelegate> _delegate;
    id <SPTAudioTouch> _audioTouch;
    SPTBrowseABTestsManager *_browseABTestsManager;
    id <SPTProductState> _productState;
    id <SPTTinkerbellManager> _tinkerbellManager;
    id <SPTTinkerbellStoryRegistry> _tinkerbellStoryRegistry;
    id <SPTTinkerbellItemPresentationController> _tinkerbellItemPresentationController;
    id <SPTImageLoaderFactory> _imageLoaderFactory;
    SPTBrowseFeaturedPlaylistsRequest *_model;
    SPTCollectionView *_collectionView;
    NSURL *_currentPlayingURL;
    UILabel *_featuredPlayListTitle;
    SPTBrowseParallaxBackground *_backgroundView;
    SPTBrowseOverviewHeaderShortcutsView *_shortcutsView;
    UIView *_gradientImage;
    CAGradientLayer *_gradientLayer;
    id <SPTImageLoader> _imageLoader;
}

+ (id)reuseIdentifier;
+ (float)preferredHeightWithFeaturedPlaylistsVisible:(BOOL)arg1;
@property(nonatomic) BOOL hasSetupFeaturedPlaylistModel; // @synthesize hasSetupFeaturedPlaylistModel=_hasSetupFeaturedPlaylistModel;
@property(retain, nonatomic) id <SPTImageLoader> imageLoader; // @synthesize imageLoader=_imageLoader;
@property(retain, nonatomic) CAGradientLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
@property(retain, nonatomic) UIView *gradientImage; // @synthesize gradientImage=_gradientImage;
@property(nonatomic) __weak SPTBrowseOverviewHeaderShortcutsView *shortcutsView; // @synthesize shortcutsView=_shortcutsView;
@property(retain, nonatomic) SPTBrowseParallaxBackground *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UILabel *featuredPlayListTitle; // @synthesize featuredPlayListTitle=_featuredPlayListTitle;
@property(retain, nonatomic) NSURL *currentPlayingURL; // @synthesize currentPlayingURL=_currentPlayingURL;
@property(retain, nonatomic) SPTCollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) __weak SPTBrowseFeaturedPlaylistsRequest *model; // @synthesize model=_model;
@property(retain, nonatomic) id <SPTImageLoaderFactory> imageLoaderFactory; // @synthesize imageLoaderFactory=_imageLoaderFactory;
@property(nonatomic) __weak id <SPTTinkerbellItemPresentationController> tinkerbellItemPresentationController; // @synthesize tinkerbellItemPresentationController=_tinkerbellItemPresentationController;
@property(retain, nonatomic) id <SPTTinkerbellStoryRegistry> tinkerbellStoryRegistry; // @synthesize tinkerbellStoryRegistry=_tinkerbellStoryRegistry;
@property(retain, nonatomic) id <SPTTinkerbellManager> tinkerbellManager; // @synthesize tinkerbellManager=_tinkerbellManager;
@property(retain, nonatomic) id <SPTProductState> productState; // @synthesize productState=_productState;
@property(retain, nonatomic) SPTBrowseABTestsManager *browseABTestsManager; // @synthesize browseABTestsManager=_browseABTestsManager;
@property(retain, nonatomic) id <SPTAudioTouch> audioTouch; // @synthesize audioTouch=_audioTouch;
@property(nonatomic) BOOL spokenWordShortcutEnabled; // @synthesize spokenWordShortcutEnabled=_spokenWordShortcutEnabled;
@property(nonatomic, getter=isChartsFeatureEnabled) BOOL chartsFeatureEnabled; // @synthesize chartsFeatureEnabled=_chartsFeatureEnabled;
@property(nonatomic) __weak id <SPTBrowseHeaderDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <SPTThemableViewLayoutDelegate> layoutDelegate; // @synthesize layoutDelegate=_layoutDelegate;
- (void).cxx_destruct;
- (BOOL)viewEngine:(id)arg1 shouldRecognizeTouch:(id)arg2;
- (void)layoutSubviews;
- (void)imageLoader:(id)arg1 didLoadImage:(id)arg2 forURL:(id)arg3 loadTime:(double)arg4 context:(id)arg5;
- (void)presentFeaturedPlaylistTinkerbellWithAnchorView:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (unsigned int)preferredCellStyle;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (void)handleShortcutForHighlights;
- (void)handleShortcutTouchForSpokenWord;
- (void)handleShortcutTouchForDiscover;
- (void)handleShortcutTouchForNewReleases;
- (void)handleShortcutTouchForToplists;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (BOOL)shouldInterruptSidebarRevealGesture:(id)arg1;
- (void)scrollToCell:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic, getter=isAtInitialPosition) BOOL atInitialPosition;
@property(readonly, nonatomic) NSArray *visibleCells;
- (void)setupShortcuts;
- (void)applyFeaturedPlaylistModel:(id)arg1;
- (void)addParallaxBackground;
- (void)applyThemeLayout;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

