//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SPTThemableView.h"

@class NSString, SPTCollectionProgressBar, UILabel;

@interface SPTCollectionProgressBarBanner : UIView <SPTThemableView>
{
    id <SPTThemableViewLayoutDelegate> _layoutDelegate;
    unsigned int _metricsUse;
    unsigned int _numberOfItems;
    unsigned int _numberOfCompletedItems;
    NSString *_title;
    UILabel *_titleLabel;
    UILabel *_xOfYLabel;
    SPTCollectionProgressBar *_progressBar;
    float _animationDuration;
    float _animationDelay;
}

+ (BOOL)requiresConstraintBasedLayout;
@property(nonatomic) float animationDelay; // @synthesize animationDelay=_animationDelay;
@property(nonatomic) float animationDuration; // @synthesize animationDuration=_animationDuration;
@property(retain, nonatomic) SPTCollectionProgressBar *progressBar; // @synthesize progressBar=_progressBar;
@property(retain, nonatomic) UILabel *xOfYLabel; // @synthesize xOfYLabel=_xOfYLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) unsigned int numberOfCompletedItems; // @synthesize numberOfCompletedItems=_numberOfCompletedItems;
@property(nonatomic) unsigned int numberOfItems; // @synthesize numberOfItems=_numberOfItems;
@property(nonatomic) unsigned int metricsUse; // @synthesize metricsUse=_metricsUse;
@property(nonatomic) __weak id <SPTThemableViewLayoutDelegate> layoutDelegate; // @synthesize layoutDelegate=_layoutDelegate;
- (void).cxx_destruct;
- (void)animateOut;
- (void)animateIn;
- (void)applyThemeLayout;
- (void)layoutSubviews;
- (void)updateConstraints;
- (id)constraintView:(id)arg1 toHeight:(float)arg2;
- (id)constraintView:(id)arg1 toWidth:(float)arg2;
- (id)constraintView:(id)arg1 toTopMargin:(float)arg2 fromSiblingView:(id)arg3;
- (id)constraintView:(id)arg1 toTopMargin:(float)arg2;
- (id)constraintView:(id)arg1 toRightMargin:(float)arg2;
- (id)constraintView:(id)arg1 toLeftMargin:(float)arg2;
- (id)constraintViewToCenterHorizontally:(id)arg1;
- (void)setTitle:(id)arg1 animated:(BOOL)arg2;
- (void)setNumberOfCompletedItems:(unsigned int)arg1 animated:(BOOL)arg2;
- (void)setNumberOfItems:(unsigned int)arg1 animated:(BOOL)arg2;
- (void)updateProgressBarAnimated:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1 numberOfItems:(unsigned int)arg2 title:(id)arg3 metricsUse:(unsigned int)arg4;
- (id)initWithNumberOfItems:(unsigned int)arg1 title:(id)arg2 metricsUse:(unsigned int)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

