//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface SPTChartPrefixIconView : UIView
{
    unsigned int _type;
}

@property(nonatomic) unsigned int type; // @synthesize type=_type;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawIcon;
- (id)initWithType:(unsigned int)arg1;

@end

