//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CrashlyticsDelegate.h"
#import "SPTCrashDetector.h"

@class NSString;

@interface SPTCrashlyticsCrashDetector : NSObject <CrashlyticsDelegate, SPTCrashDetector>
{
    id <SPTCrashDetectorDelegate> _delegate;
    NSString *_coreVersionString;
    unsigned int _packedVersion;
}

@property(readonly, nonatomic) unsigned int packedVersion; // @synthesize packedVersion=_packedVersion;
@property(readonly, copy, nonatomic) NSString *coreVersionString; // @synthesize coreVersionString=_coreVersionString;
@property(nonatomic) __weak id <SPTCrashDetectorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)crashlytics:(id)arg1 didDetectCrashDuringPreviousExecution:(id)arg2;
- (id)crashReportURLForUUID:(id)arg1;
- (void)setValue:(id)arg1 forStateKey:(id)arg2;
- (void)leaveBreadcrumb:(id)arg1;
- (void)userDidLogIn:(id)arg1;
- (void)start;
@property(readonly, nonatomic) NSString *detectorIdentifier;
- (id)initWithFullVersionString:(id)arg1 packedVersion:(unsigned int)arg2 coreVersionString:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

