//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SPTContextMenuView;

@protocol SPTContextMenuViewDelegate <NSObject>
- (void)dismissContextMenuView:(SPTContextMenuView *)arg1 completion:(void (^)(void))arg2;

@optional
- (int)interfaceOrientationForContextMenuView:(SPTContextMenuView *)arg1;
- (BOOL)shouldShowCancelButtonInContextMenuView:(SPTContextMenuView *)arg1;
- (BOOL)contextMenuView:(SPTContextMenuView *)arg1 shouldBeDismissedAfterPerformingAction:(id <SPTContextMenuAction>)arg2;
@end

