//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPForegroundObserverDelegate.h"

@class NSString, SPForegroundObserver, SPTClientEventLogger;

@interface SPTClippyPasteboardController : NSObject <SPForegroundObserverDelegate>
{
    id <SPTLocalSettings> _localSettings;
    id <SPTBannerPresentationManager> _bannerPresentationManager;
    id <SPTBannerPresentationManagerTicket> _bannerTicket;
    SPTClientEventLogger *_clientEventLogger;
    SPForegroundObserver *_foregroundObserver;
}

+ (id)localizedActionButtonTitleForURL:(id)arg1;
+ (id)newBannerItemForURL:(id)arg1;
@property(readonly, nonatomic) SPForegroundObserver *foregroundObserver; // @synthesize foregroundObserver=_foregroundObserver;
@property(retain, nonatomic) SPTClientEventLogger *clientEventLogger; // @synthesize clientEventLogger=_clientEventLogger;
@property(nonatomic) __weak id <SPTBannerPresentationManagerTicket> bannerTicket; // @synthesize bannerTicket=_bannerTicket;
@property(retain, nonatomic) id <SPTBannerPresentationManager> bannerPresentationManager; // @synthesize bannerPresentationManager=_bannerPresentationManager;
@property(retain, nonatomic) id <SPTLocalSettings> localSettings; // @synthesize localSettings=_localSettings;
- (void).cxx_destruct;
- (void)markURLAsPresented:(id)arg1;
- (BOOL)shouldInformUserOfURL:(id)arg1;
- (void)handleURL:(id)arg1;
- (void)checkPasteboard;
- (void)foregroundObserverDidHibernate:(id)arg1;
- (void)foregroundObserverDidAwake:(id)arg1;
- (void)tearDown;
- (void)setUp;
- (void)dealloc;
- (id)initWithLocalSettings:(id)arg1 bannerPresentationManager:(id)arg2 clientEventLogger:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

