//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SPTThemableView.h"

@class NSString, SPTChartPrefixIconView, UILabel;

@interface SPTChartMetadataPrefixView : UIView <SPTThemableView>
{
    id <SPTThemableViewLayoutDelegate> _layoutDelegate;
    SPTChartPrefixIconView *_iconView;
    unsigned int _entryType;
    UILabel *_numberLabel;
}

+ (id)metadataViewWithType:(unsigned int)arg1 positionNumber:(unsigned int)arg2;
@property(retain, nonatomic) UILabel *numberLabel; // @synthesize numberLabel=_numberLabel;
@property(nonatomic) unsigned int entryType; // @synthesize entryType=_entryType;
@property(retain, nonatomic) SPTChartPrefixIconView *iconView; // @synthesize iconView=_iconView;
@property(nonatomic) __weak id <SPTThemableViewLayoutDelegate> layoutDelegate; // @synthesize layoutDelegate=_layoutDelegate;
- (void).cxx_destruct;
- (void)applyThemeLayout;
- (id)initWithViewType:(unsigned int)arg1 positionNumber:(unsigned int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

