//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SPTContextMenuContentViewControllerDelegate.h"
#import "SPTImageLoaderDelegate.h"
#import "SPTNavigationControllerNavigationBarState.h"
#import "SPTThemableViewLayoutDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, NSURL, SPTContextMenuHeaderView, SPTPopoverController, SPTTableView, UIImage, UIView;

@interface SPTContextMenuViewControllerIPad : UIViewController <SPTImageLoaderDelegate, UITableViewDataSource, UITableViewDelegate, SPTThemableViewLayoutDelegate, SPTNavigationControllerNavigationBarState, SPTContextMenuContentViewControllerDelegate>
{
    SPTPopoverController *_currentPopoverController;
    UIView *_containerView;
    SPTTableView *_tableView;
    NSURL *_contextMenuHeaderImageURL;
    UIImage *_contextMenuHeaderImagePlaceholder;
    NSString *_contextMenuTitle;
    NSString *_contextMenuSubtitle;
    NSString *_contextMenuMetadataTitle;
    NSArray *_contextMenuActions;
    SPTContextMenuHeaderView *_headerView;
    id <SPTImageLoader> _imageLoader;
    NSURL *_entityURL;
    NSURL *_trackURL;
}

@property(retain, nonatomic) NSURL *trackURL; // @synthesize trackURL=_trackURL;
@property(retain, nonatomic) NSURL *entityURL; // @synthesize entityURL=_entityURL;
@property(retain, nonatomic) id <SPTImageLoader> imageLoader; // @synthesize imageLoader=_imageLoader;
@property(retain, nonatomic) SPTContextMenuHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) NSArray *contextMenuActions; // @synthesize contextMenuActions=_contextMenuActions;
@property(copy, nonatomic) NSString *contextMenuMetadataTitle; // @synthesize contextMenuMetadataTitle=_contextMenuMetadataTitle;
@property(copy, nonatomic) NSString *contextMenuSubtitle; // @synthesize contextMenuSubtitle=_contextMenuSubtitle;
@property(copy, nonatomic) NSString *contextMenuTitle; // @synthesize contextMenuTitle=_contextMenuTitle;
@property(retain, nonatomic) UIImage *contextMenuHeaderImagePlaceholder; // @synthesize contextMenuHeaderImagePlaceholder=_contextMenuHeaderImagePlaceholder;
@property(retain, nonatomic) NSURL *contextMenuHeaderImageURL; // @synthesize contextMenuHeaderImageURL=_contextMenuHeaderImageURL;
@property(retain, nonatomic) SPTTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak SPTPopoverController *currentPopoverController; // @synthesize currentPopoverController=_currentPopoverController;
- (void).cxx_destruct;
- (unsigned int)preferredNavigationBarState;
- (void)themableViewDidUpdateLayout:(id)arg1;
- (void)imageLoader:(id)arg1 didLoadImage:(id)arg2 forURL:(id)arg3 loadTime:(double)arg4 context:(id)arg5;
- (void)contentViewControllerDidComplete:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)updateSeparatorInsetForCell:(id)arg1 atIndexPath:(id)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewWillLayoutSubviews;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithHeaderImageURL:(id)arg1 headerImagePlaceholder:(id)arg2 title:(id)arg3 subtitle:(id)arg4 metadataTitle:(id)arg5 actions:(id)arg6 entityURL:(id)arg7 trackURL:(id)arg8 imageLoader:(id)arg9 senderView:(id)arg10;
- (id)initWithHeaderImageURL:(id)arg1 headerImagePlaceholder:(id)arg2 title:(id)arg3 subtitle:(id)arg4 metadataTitle:(id)arg5 tasks:(id)arg6 entityURL:(id)arg7 trackURL:(id)arg8 imageLoader:(id)arg9 senderView:(id)arg10;
- (id)initWithHeaderImageURL:(id)arg1 headerImagePlaceholder:(id)arg2 title:(id)arg3 subtitle:(id)arg4 metadataTitle:(id)arg5 entityURL:(id)arg6 trackURL:(id)arg7 imageLoader:(id)arg8 senderView:(id)arg9;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

