//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol SPTDebugActionsRegistry <NSObject>
- (void)addDebugViewControllerWithDescription:(NSString *)arg1 category:(int)arg2 weight:(unsigned int)arg3 viewControllerFactory:(UIViewController * (^)(void))arg4;
- (void)addDebugActionWithDescription:(NSString *)arg1 category:(int)arg2 weight:(unsigned int)arg3 shouldCloseDebugMenu:(BOOL)arg4 action:(void (^)(void))arg5;
@end

