//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol SPTEntityRemoteProviderProtocol <NSObject>
- (PassRefPtr_dc5781f5)lookupTracksWithLinks:(const AsArray_ed8d0598 *)arg1 callback:(const struct function<void (const boost::system::error_code &, base::AsArray<const spotify::uri::SpotifyLink>, base::AsArray<const sp::TrackInfo *>)> *)arg2;
- (PassRefPtr_dc5781f5)lookupAlbumsWithLinks:(const AsArray_ed8d0598 *)arg1 callback:(const struct function<void (const boost::system::error_code &, base::AsArray<const spotify::uri::SpotifyLink>, base::AsArray<const sp::AlbumMetadata *>)> *)arg2;
- (PassRefPtr_dc5781f5)lookupArtistsWithLinks:(const AsArray_ed8d0598 *)arg1 callback:(const struct function<void (const boost::system::error_code &, base::AsArray<const spotify::uri::SpotifyLink>, base::AsArray<const sp::ArtistMetadata *>)> *)arg2;
- (PassRefPtr_dc5781f5)lookupTrackWithLink:(const struct SpotifyLink *)arg1 callback:(const struct function<void (const boost::system::error_code &, const spotify::uri::SpotifyLink &, const sp::TrackInfo *)> *)arg2;
- (PassRefPtr_dc5781f5)lookupAlbumWithLink:(const struct SpotifyLink *)arg1 callback:(const struct function<void (const boost::system::error_code &, const spotify::uri::SpotifyLink &, const sp::AlbumMetadata *)> *)arg2;
- (PassRefPtr_dc5781f5)lookupArtistWithLink:(const struct SpotifyLink *)arg1 callback:(const struct function<void (const boost::system::error_code &, const spotify::uri::SpotifyLink &, const sp::ArtistMetadata *)> *)arg2;
@end

