//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MPVolumeView;

@interface SPTGaiaVolumeButtonController : NSObject
{
    BOOL _stealingVolume;
    id <SPTGaiaVolumeButtonControllerDelegate> _delegate;
    float _initialVolume;
    float _resetVolume;
    MPVolumeView *_volumeView;
}

@property(retain, nonatomic) MPVolumeView *volumeView; // @synthesize volumeView=_volumeView;
@property(nonatomic) float resetVolume; // @synthesize resetVolume=_resetVolume;
@property(nonatomic) float initialVolume; // @synthesize initialVolume=_initialVolume;
@property(nonatomic) __weak id <SPTGaiaVolumeButtonControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic, getter=isStealingVolume) BOOL stealingVolume; // @synthesize stealingVolume=_stealingVolume;
- (void).cxx_destruct;
- (void)outputVolumeChanged;
- (void)stopStealingVolumeButtons;
- (void)startStealingVolumeButtons;
- (void)removeVolumeDependencies;
- (void)setupVolumeDependencies;
- (void)dealloc;
- (id)init;

@end

