//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTIAPProductLoaderService.h"

@class NSMutableArray, NSString;

@interface SPTIAPSpotifyProductLoaderService : NSObject <SPTIAPProductLoaderService>
{
    id <SPTIAPProductLoaderService> _spotifyLoaderService;
    id <SPTIAPItunesProductLoaderService> _itunesLoaderService;
    NSMutableArray *_ongoingRequests;
}

@property(retain, nonatomic) NSMutableArray *ongoingRequests; // @synthesize ongoingRequests=_ongoingRequests;
@property(retain, nonatomic) id <SPTIAPItunesProductLoaderService> itunesLoaderService; // @synthesize itunesLoaderService=_itunesLoaderService;
@property(retain, nonatomic) id <SPTIAPProductLoaderService> spotifyLoaderService; // @synthesize spotifyLoaderService=_spotifyLoaderService;
- (void).cxx_destruct;
- (void)loadProductsWithCallback:(CDUnknownBlockType)arg1;
- (id)initWithSpotifyProductLoaderService:(id)arg1 itunesProductLoaderService:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

