//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL, SPSendTracksRequest, SPUser;

@interface SPTLegacyShareHandler : NSObject
{
    id <SPTLegacyShareHandlerDelegate> _delegate;
    NSURL *_itemURL;
    SPUser *_recipientUser;
    id <SPTResolver> _resolver;
    SPSendTracksRequest *_sendRequest;
    id <SPTOfflineModeState> _offlineModeState;
    NSString *_facebookId;
}

+ (id)shareHandlerWithItemURL:(id)arg1 recipientFacebookId:(id)arg2 resolver:(id)arg3 offlineModeState:(id)arg4;
+ (id)shareHandlerForPostToFeedWithItemURL:(id)arg1 resolver:(id)arg2 offlineModeState:(id)arg3;
+ (id)shareHandlerWithItemURL:(id)arg1 recipientUser:(id)arg2 offlineModeState:(id)arg3;
@property(retain, nonatomic) NSString *facebookId; // @synthesize facebookId=_facebookId;
@property(retain, nonatomic) id <SPTOfflineModeState> offlineModeState; // @synthesize offlineModeState=_offlineModeState;
@property(retain, nonatomic) SPSendTracksRequest *sendRequest; // @synthesize sendRequest=_sendRequest;
@property(retain, nonatomic) id <SPTResolver> resolver; // @synthesize resolver=_resolver;
@property(retain, nonatomic) SPUser *recipientUser; // @synthesize recipientUser=_recipientUser;
@property(retain, nonatomic) NSURL *itemURL; // @synthesize itemURL=_itemURL;
@property(nonatomic) __weak id <SPTLegacyShareHandlerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)invokeDelegateOfflineError;
- (void)invokeDelegateGeneralError;
- (void)postToFeedWithMessage:(id)arg1;
- (id)facebookPayloadWithMessage:(id)arg1;
- (void)sendToFacebookFriendWithMessage:(id)arg1;
- (void)sendToFriendWithMessage:(id)arg1;
- (void)sendWithMessage:(id)arg1;
- (id)initWithItemURL:(id)arg1 recipientUser:(id)arg2 recipientFacebookId:(id)arg3 resolver:(id)arg4 offlineModeState:(id)arg5;

@end

