//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPTLoginUIDispatchController : NSObject
{
}

- (BOOL)ensureForceOfflineIsOff;
- (void)loginFailedWithError:(id)arg1 inContext:(id)arg2;
- (void)loginSucceededInContext:(id)arg1;

@end

