//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface SPTNewMusicTuesdayModel : NSObject
{
    NSArray *_elements;
}

@property(retain, nonatomic) NSArray *elements; // @synthesize elements=_elements;
- (void).cxx_destruct;
- (id)description;

@end

