//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTContentItemChangeNotificationImplementation.h"

#import "SPTExternalContentItem.h"

@class NSArray, NSString, SPPlaylistContainer, SPSession;

@interface SPTPlaylistFolderContentItem : SPTContentItemChangeNotificationImplementation <SPTExternalContentItem>
{
    NSArray *children;
    SPPlaylistContainer *_container;
    SPSession *_session;
    id <SPTImageLoaderFactory> _imageLoaderFactory;
}

@property(retain, nonatomic) id <SPTImageLoaderFactory> imageLoaderFactory; // @synthesize imageLoaderFactory=_imageLoaderFactory;
@property(nonatomic) __weak SPSession *session; // @synthesize session=_session;
@property(retain, nonatomic) SPPlaylistContainer *container; // @synthesize container=_container;
@property(copy, nonatomic) NSArray *children; // @synthesize children;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL shouldPlayParent;
@property(readonly, nonatomic) BOOL isItemContainer;
@property(readonly, nonatomic) BOOL playable;
@property(readonly, copy, nonatomic) NSString *identifier;
@property(readonly, copy, nonatomic) NSString *subTitle;
@property(readonly, copy, nonatomic) NSString *title;
- (id)generateImageWithSize:(struct CGSize)arg1 foregroundColor:(id)arg2 backgroundColor:(id)arg3;
- (id)headerPlaylists;
- (void)updateChildren;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (id)initWithSession:(id)arg1 playlistContainer:(id)arg2 imageLoaderFactory:(id)arg3;

// Remaining properties
@property(readonly, nonatomic) unsigned int childStructureHint;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly, copy, nonatomic) NSArray *headers;
@property(readonly) Class superclass;

@end

