//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTPodcastCollectionModel.h"

@interface SPTPodcastCosmosCollectionModel : NSObject <SPTPodcastCollectionModel>
{
    id <SPTResolver> _resolver;
}

@property(readonly, nonatomic) id <SPTResolver> resolver; // @synthesize resolver=_resolver;
- (void).cxx_destruct;
- (void)performRequest:(id)arg1 withCallback:(CDUnknownBlockType)arg2 withErrorDescription:(id)arg3;
- (void)removeURL:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)addURL:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (id)initWithResolver:(id)arg1;

@end

