//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, SPTPopupDialog, SPTPopupWindow;

@interface SPTPopupManager : NSObject
{
    id <SPTPopupTheme> _theme;
    SPTPopupWindow *_window;
    NSMutableArray *_presentationQueue;
    SPTPopupDialog *_presentedPopup;
}

+ (id)sharedManager;
@property(retain, nonatomic) SPTPopupDialog *presentedPopup; // @synthesize presentedPopup=_presentedPopup;
@property(retain, nonatomic) NSMutableArray *presentationQueue; // @synthesize presentationQueue=_presentationQueue;
@property(retain, nonatomic) SPTPopupWindow *window; // @synthesize window=_window;
@property(retain, nonatomic) id <SPTPopupTheme> theme; // @synthesize theme=_theme;
- (void).cxx_destruct;
- (void)loadWindow;
- (void)dismissPopupDialog:(id)arg1;
- (BOOL)presentPopupDialog:(id)arg1;
- (void)presentNextQueuedPopup;
- (void)didDismissPopup:(id)arg1;
- (void)willDismissPopup:(id)arg1;
- (void)didPresentPopup:(id)arg1;
- (void)willPresentPopup:(id)arg1;
- (BOOL)isPresentingPopup:(id)arg1;
- (BOOL)isPresentingPopup;
- (void)invalidatePopupsDisallowedReason:(id)arg1;
- (void)disallowPopupsWithReason:(id)arg1;
- (BOOL)canDisplayPopupDialogs;
- (id)init;

@end

