//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UILabel;

@interface SPTPopupTextContentController : UIViewController
{
    UILabel *_textLabel;
}

+ (id)contentWithText:(id)arg1;
@property(readonly, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
- (void).cxx_destruct;
- (void)viewDidLoad;
- (void)setupTextLabel;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithText:(id)arg1;

@end

