//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface SPTProfileInvitesViewModelData : NSObject
{
    NSArray *_codes;
}

@property(readonly, nonatomic) NSArray *codes; // @synthesize codes=_codes;
- (void).cxx_destruct;
- (id)initWithInviteCodes:(id)arg1;

@end

