//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SPTShareData;

@interface SPTSendServiceChooserViewModel : NSObject
{
    SPTShareData *_data;
}

@property(readonly, nonatomic) SPTShareData *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (id)itemDescription;
- (void)prepareAttachmentsForMailComposerVC:(id)arg1;
- (id)whatsAppBody;
- (id)messageBody;
- (id)mailBody;
- (id)mailSubject;
- (id)initWithData:(id)arg1;

@end

