//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPViewController.h"

#import "SPForegroundObserverDelegate.h"
#import "SPSessionObserver.h"
#import "SPTImageLoaderDelegate.h"
#import "SPTProductStateObserver.h"

@class NSString, SPForegroundObserver, SPSession, SPTSearchLogger, SPTSearchNavigator, SPTSearchPlayer, SearchViewModel;

@interface SPTSearchViewController : SPViewController <SPForegroundObserverDelegate, SPTImageLoaderDelegate, SPTProductStateObserver, SPSessionObserver>
{
    id <SearchInternalViewControllerDelegate> _delegate;
    SearchViewModel *_viewModel;
    SPTSearchPlayer *_player;
    SPTSearchNavigator *_navigator;
    SPTSearchLogger *_searchLogger;
    id <SPTAudioTouch> _audioTouch;
    id <SPTProductState> _productState;
    SPSession *_session;
    SPForegroundObserver *_foregroundObserver;
    id <SPTImageLoader> _imageLoader;
}

@property(retain, nonatomic) id <SPTImageLoader> imageLoader; // @synthesize imageLoader=_imageLoader;
@property(retain, nonatomic) SPForegroundObserver *foregroundObserver; // @synthesize foregroundObserver=_foregroundObserver;
@property(readonly, nonatomic) __weak SPSession *session; // @synthesize session=_session;
@property(readonly, nonatomic) id <SPTProductState> productState; // @synthesize productState=_productState;
@property(readonly, nonatomic) id <SPTAudioTouch> audioTouch; // @synthesize audioTouch=_audioTouch;
@property(readonly, nonatomic) SPTSearchLogger *searchLogger; // @synthesize searchLogger=_searchLogger;
@property(readonly, nonatomic) SPTSearchNavigator *navigator; // @synthesize navigator=_navigator;
@property(readonly, nonatomic) SPTSearchPlayer *player; // @synthesize player=_player;
@property(readonly, nonatomic) SearchViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) __weak id <SearchInternalViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)restoreUserActivityState:(id)arg1;
- (void)updateUserActivityState:(id)arg1;
- (BOOL)restoreWithObjectRepresentation:(id)arg1;
- (id)objectRepresentation;
- (id)URI;
- (void)sessionLoginModeChanged:(id)arg1;
- (void)imageLoader:(id)arg1 didLoadImage:(id)arg2 forURL:(id)arg3 loadTime:(double)arg4 context:(id)arg5;
- (void)productState:(id)arg1 stateDidChange:(id)arg2;
- (void)foregroundObserverDidHibernate:(id)arg1;
- (void)foregroundObserverDidAwake:(id)arg1;
- (id)viewEventURI;
- (BOOL)automaticallyAdjustsScrollViewInsets;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)performSearchWithString:(id)arg1 delayed:(BOOL)arg2;
- (void)updateViewWithError:(id)arg1 scrollResultsViewToTop:(BOOL)arg2;
- (BOOL)shouldAddBottomContentInsetForNextDatasetLoadingView;
- (BOOL)shouldDisplayLoadMoreResultsAccessibilityView;
- (id)searchResultsView;
- (unsigned int)interfaceType;
- (void)loadImageForCell:(id)arg1 model:(id)arg2 imageSize:(struct CGSize)arg3 indexPath:(id)arg4 embeddedCollectionView:(id)arg5;
- (void)dealloc;
- (id)initWithViewModel:(id)arg1 player:(id)arg2 audioTouch:(id)arg3 productState:(id)arg4 metaViewController:(id)arg5 session:(id)arg6 imageLoader:(id)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

