//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTGenericContentItem.h"

@interface SPTShufflePlayContentItem : SPTGenericContentItem
{
    id <SPTExternalContentItem> _contentItem;
}

@property(nonatomic) __weak id <SPTExternalContentItem> contentItem; // @synthesize contentItem=_contentItem;
- (void).cxx_destruct;
- (id)initWithExternalContentItem:(id)arg1 imageLoaderFactory:(id)arg2;

@end

