//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTSearchResultsDataSource.h"

@class NSString, SPTOfflineManager;

@interface SPTSearchResultsOfflineDataSource : NSObject <SPTSearchResultsDataSource>
{
    id <SPTSearchResultsDataSourceDelegate> _delegate;
    SPTOfflineManager *_offlineManager;
    id <SPTPlaylistProvider> _playlistProvider;
}

+ (id)offlineDataSourceWithOfflineManager:(id)arg1 playlistProvider:(id)arg2;
@property(nonatomic) __weak id <SPTPlaylistProvider> playlistProvider; // @synthesize playlistProvider=_playlistProvider;
@property(nonatomic) __weak SPTOfflineManager *offlineManager; // @synthesize offlineManager=_offlineManager;
@property(nonatomic) __weak id <SPTSearchResultsDataSourceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)hasNextDatasetForRequestParameters:(id)arg1;
- (BOOL)addResultsForRequestParameters:(id)arg1 toBuilder:(id)arg2;
@property(readonly, copy, nonatomic) NSString *dataSourceIdentifier;
- (id)showModelForOfflineShowDictionary:(id)arg1;
- (id)playlistModelForSPPlaylist:(id)arg1;
- (id)albumModelForSPAlbum:(id)arg1 artist:(id)arg2;
- (id)artistModelForSPArtist:(id)arg1;
- (id)trackModelForSPTrack:(id)arg1 album:(id)arg2 artist:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

