//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTTelcoActivationProductActivationRequest.h"

@class SPApHermesController;

@interface SPTTelcoActivationHermesProductActivationRequest : SPTTelcoActivationProductActivationRequest
{
    SPApHermesController *_hermesController;
}

@property(retain, nonatomic) SPApHermesController *hermesController; // @synthesize hermesController=_hermesController;
- (void).cxx_destruct;
- (void)start;
- (id)initWithHermesController:(id)arg1 orderTokenResponseBody:(id)arg2 delegate:(id)arg3;

@end

