//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTTouchGestureRecognizerDelegate.h"
#import "SPTTouchViewEngine.h"
#import "SPTTouchViewEngineNodeObserver.h"

@class NSHashTable, NSMutableDictionary, NSString, NSTimer, SPTTouchAudioEngine, SPTTouchViewAudioSession, UIGestureRecognizer;

@interface SPTTouchViewEngineImplementation : NSObject <SPTTouchViewEngineNodeObserver, SPTTouchViewEngine, SPTTouchGestureRecognizerDelegate>
{
    BOOL _enabled;
    BOOL _touching;
    UIGestureRecognizer *_previewGestureRecognizer;
    UIGestureRecognizer *_edgeScrollGestureRecognizer;
    SPTTouchAudioEngine *_audioEngine;
    id <SPTTouchViewEngineDelegate> _delegate;
    id <SPTTouchViewEngineImplementationDelegate> _internalDelegate;
    NSHashTable *_observers;
    NSMutableDictionary *_effects;
    NSMutableDictionary *_nodes;
    SPTTouchViewAudioSession *_audioSession;
    NSTimer *_willStartTimer;
    struct CGPoint _lastTouchPosition;
}

@property(nonatomic) struct CGPoint lastTouchPosition; // @synthesize lastTouchPosition=_lastTouchPosition;
@property(retain, nonatomic) NSTimer *willStartTimer; // @synthesize willStartTimer=_willStartTimer;
@property(retain, nonatomic) SPTTouchViewAudioSession *audioSession; // @synthesize audioSession=_audioSession;
@property(retain, nonatomic) NSMutableDictionary *nodes; // @synthesize nodes=_nodes;
@property(retain, nonatomic) NSMutableDictionary *effects; // @synthesize effects=_effects;
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(nonatomic, getter=isTouching) BOOL touching; // @synthesize touching=_touching;
@property(nonatomic) __weak id <SPTTouchViewEngineImplementationDelegate> internalDelegate; // @synthesize internalDelegate=_internalDelegate;
@property(nonatomic, getter=isEnabled) BOOL enabled; // @synthesize enabled=_enabled;
@property(nonatomic) __weak id <SPTTouchViewEngineDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) SPTTouchAudioEngine *audioEngine; // @synthesize audioEngine=_audioEngine;
- (void).cxx_destruct;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)previewWithGestureRecognizer:(id)arg1;
- (void)touchGestureRecognizerDidStop:(id)arg1;
- (void)touchGestureRecognizerDidStart:(id)arg1;
- (void)touchGestureRecognizerDidCancel:(id)arg1;
- (void)touchGestureRecognizerWillStart:(id)arg1;
- (void)nodeDidInvalidateView:(id)arg1;
- (void)applicationWillChangeStatusBarOrientationNotification;
- (void)willStartTimerAction:(id)arg1;
- (void)performObserverAction:(CDUnknownBlockType)arg1;
- (void)performEffectAction:(CDUnknownBlockType)arg1;
- (void)unregisterNode:(id)arg1;
- (id)nodeForView:(id)arg1;
- (id)effectForKey:(id)arg1;
- (void)endTouchWithPosition:(struct CGPoint)arg1;
- (void)moveTouchToPosition:(struct CGPoint)arg1;
- (BOOL)startTouchWithPosition:(struct CGPoint)arg1;
- (void)didCancelTouchWithPosition:(struct CGPoint)arg1;
- (void)willStartTouchWithPosition:(struct CGPoint)arg1;
- (unsigned int)maximumNumberOfPreviewsForEffect:(id)arg1;
- (void)registerEffect:(id)arg1 forKey:(id)arg2;
- (void)unregisterView:(id)arg1;
- (BOOL)registerView:(id)arg1 previews:(id)arg2 effect:(id)arg3 name:(id)arg4;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
@property(readonly, nonatomic, getter=isPresentingFullscreenEffect) BOOL presentingFullscreenEffect;
@property(readonly, nonatomic, getter=isPreviewing) BOOL previewing;
@property(readonly, nonatomic) UIGestureRecognizer *edgeScrollGestureRecognizer; // @synthesize edgeScrollGestureRecognizer=_edgeScrollGestureRecognizer;
@property(readonly, nonatomic) UIGestureRecognizer *previewGestureRecognizer; // @synthesize previewGestureRecognizer=_previewGestureRecognizer;
- (void)dealloc;
- (id)initWithAudioEngine:(id)arg1 viewIdentifier:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

