//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTSwipeableTableViewCell.h"

#import "SPTCellImageLoadingContextCompatibleCell.h"
#import "SPTDimensionalTableViewCell.h"
#import "SPTThemableView.h"

@class NSString, SPTBadgeView, UIImage, UIView;

@interface SPTTableViewCell : SPTSwipeableTableViewCell <SPTThemableView, SPTCellImageLoadingContextCompatibleCell, SPTDimensionalTableViewCell>
{
    BOOL _active;
    BOOL _disabled;
    BOOL _interactive;
    id <SPTThemableViewLayoutDelegate> _layoutDelegate;
    UIView *_prefixView;
    unsigned int _imageStyle;
    int _placeholderImageContentMode;
    int _imageContentMode;
    UIImage *_placeholderImage;
    UIImage *_image;
    SPTBadgeView *_imageBadge;
    unsigned int _subtitleStyle;
    UIView *_subtitleAccessoryView;
    int _tableViewThemeStyle;
}

+ (float)preferredHeight;
+ (float)shufflePreferredHeight;
@property(nonatomic) int tableViewThemeStyle; // @synthesize tableViewThemeStyle=_tableViewThemeStyle;
@property(nonatomic, getter=isInteractive) BOOL interactive; // @synthesize interactive=_interactive;
@property(nonatomic, getter=isDisabled) BOOL disabled; // @synthesize disabled=_disabled;
@property(nonatomic, getter=isActive) BOOL active; // @synthesize active=_active;
@property(retain, nonatomic) UIView *subtitleAccessoryView; // @synthesize subtitleAccessoryView=_subtitleAccessoryView;
@property(nonatomic) unsigned int subtitleStyle; // @synthesize subtitleStyle=_subtitleStyle;
@property(retain, nonatomic) SPTBadgeView *imageBadge; // @synthesize imageBadge=_imageBadge;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) UIImage *placeholderImage; // @synthesize placeholderImage=_placeholderImage;
@property(nonatomic) int imageContentMode; // @synthesize imageContentMode=_imageContentMode;
@property(nonatomic) int placeholderImageContentMode; // @synthesize placeholderImageContentMode=_placeholderImageContentMode;
@property(nonatomic) unsigned int imageStyle; // @synthesize imageStyle=_imageStyle;
@property(retain, nonatomic) UIView *prefixView; // @synthesize prefixView=_prefixView;
@property(nonatomic) __weak id <SPTThemableViewLayoutDelegate> layoutDelegate; // @synthesize layoutDelegate=_layoutDelegate;
- (void).cxx_destruct;
- (void)applyThemeLayout;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubviews;
- (float)totalIndentationWidth;
- (float)accessoryViewCellSpace;
- (struct CGRect)frameForAccessoryView;
- (BOOL)hasImage;
@property(copy, nonatomic) NSString *subtitle;
@property(nonatomic) int maximumNumberOfLinesInTitle;
@property(copy, nonatomic) NSString *title;
- (void)setImage:(id)arg1 animated:(BOOL)arg2;
- (void)updateImageContentMode;
- (id)imageToShow;
- (void)prepareForReuse;
- (id)initWithReuseIdentifier:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
@property(nonatomic, getter=isShuffleTrackCell) BOOL shuffleTrackCell;
- (void)populateWithChartViewModel:(id)arg1 index:(int)arg2;
- (void)adaptForSearchEntityCellType:(unsigned int)arg1 hideSeparator:(BOOL)arg2;

// Remaining properties
@property(nonatomic) int accessoryType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

