//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSHashTable, NSString, SPTTouchObjectObserver, UIView;

@interface SPTTouchViewEngineNode : NSObject
{
    NSArray *_previews;
    NSString *_effect;
    NSString *_name;
    id _effectInfo;
    SPTTouchObjectObserver *_viewObserver;
    NSHashTable *_observers;
}

+ (id)nodeWithView:(id)arg1 previews:(id)arg2 effect:(id)arg3;
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(nonatomic) __weak SPTTouchObjectObserver *viewObserver; // @synthesize viewObserver=_viewObserver;
@property(retain, nonatomic) id effectInfo; // @synthesize effectInfo=_effectInfo;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) NSString *effect; // @synthesize effect=_effect;
@property(readonly, nonatomic) NSArray *previews; // @synthesize previews=_previews;
- (void).cxx_destruct;
- (struct CGPoint)convertPointToNodeCoordinateSystem:(struct CGPoint)arg1;
- (struct CGRect)convertRectToNodeCoordinateSystem:(struct CGRect)arg1;
@property(readonly, nonatomic) __weak UIView *view;
- (void)viewInvalidated;
- (void)observeView:(id)arg1;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (id)initWithView:(id)arg1 previews:(id)arg2 effect:(id)arg3;

@end

