//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPTUpsellSettingsPageBuilder : NSObject
{
    id <SPTUpsellPopupManager> _popupManager;
}

@property(retain, nonatomic) id <SPTUpsellPopupManager> popupManager; // @synthesize popupManager=_popupManager;
- (void).cxx_destruct;
- (void)itemizeSettingsPage:(id)arg1;
- (id)initWithPopupManger:(id)arg1;

@end

