//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPVASTCreative.h"

@class NSArray, NSNumber, NSURL;

@interface SPVASTLinearCreative : SPVASTCreative
{
    NSNumber *_duration;
    NSURL *_clickThroughURL;
    NSArray *_clickTrackingURLs;
    NSArray *_mediaFiles;
}

@property(retain, nonatomic) NSArray *mediaFiles; // @synthesize mediaFiles=_mediaFiles;
@property(retain, nonatomic) NSArray *clickTrackingURLs; // @synthesize clickTrackingURLs=_clickTrackingURLs;
@property(retain, nonatomic) NSURL *clickThroughURL; // @synthesize clickThroughURL=_clickThroughURL;
@property(retain, nonatomic) NSNumber *duration; // @synthesize duration=_duration;
- (void).cxx_destruct;
- (id)initWithNode:(id)arg1;

@end

