//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString, NSURL;

@interface SPVASTMediaFile : NSObject
{
    NSString *_identifier;
    int _deliveryType;
    NSString *_mimeType;
    NSURL *_URL;
    NSString *_codec;
    NSNumber *_scalable;
    NSNumber *_maintainAspectRatio;
    struct CGSize _size;
    struct _NSRange _bitrateRange;
}

@property(retain, nonatomic) NSNumber *maintainAspectRatio; // @synthesize maintainAspectRatio=_maintainAspectRatio;
@property(retain, nonatomic) NSNumber *scalable; // @synthesize scalable=_scalable;
@property(nonatomic) struct _NSRange bitrateRange; // @synthesize bitrateRange=_bitrateRange;
@property(retain, nonatomic) NSString *codec; // @synthesize codec=_codec;
@property(retain, nonatomic) NSURL *URL; // @synthesize URL=_URL;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(retain, nonatomic) NSString *mimeType; // @synthesize mimeType=_mimeType;
@property(nonatomic) int deliveryType; // @synthesize deliveryType=_deliveryType;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)description;
- (id)initWithNode:(id)arg1;

@end

