//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSNumber, NSString;

@interface SPVASTAd : NSObject
{
    NSString *_identifier;
    NSNumber *_sequence;
    NSString *_systemVersion;
    NSString *_systemName;
    NSString *_title;
    NSString *_adDescription;
    NSString *_advertiser;
    NSArray *_impressionURLs;
    NSArray *_errorURLs;
    NSArray *_creatives;
    NSArray *_companions;
    NSDictionary *_metadata;
}

@property(retain, nonatomic) NSDictionary *metadata; // @synthesize metadata=_metadata;
@property(retain, nonatomic) NSArray *companions; // @synthesize companions=_companions;
@property(retain, nonatomic) NSArray *creatives; // @synthesize creatives=_creatives;
@property(retain, nonatomic) NSArray *errorURLs; // @synthesize errorURLs=_errorURLs;
@property(retain, nonatomic) NSArray *impressionURLs; // @synthesize impressionURLs=_impressionURLs;
@property(retain, nonatomic) NSString *advertiser; // @synthesize advertiser=_advertiser;
@property(retain, nonatomic) NSString *adDescription; // @synthesize adDescription=_adDescription;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *systemName; // @synthesize systemName=_systemName;
@property(retain, nonatomic) NSString *systemVersion; // @synthesize systemVersion=_systemVersion;
@property(retain, nonatomic) NSNumber *sequence; // @synthesize sequence=_sequence;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)initWithNode:(id)arg1;

@end

