//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UpsellStandardViewController.h"

@interface UpsellShuffleMessageViewController : UpsellStandardViewController
{
    BOOL _dismissSelf;
}

@property(nonatomic, getter=shouldDismissSelf) BOOL dismissSelf; // @synthesize dismissSelf=_dismissSelf;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (id)initWithTitle:(id)arg1 withMessage:(id)arg2 withPrimaryButtonTitle:(id)arg3 withViewEventURI:(id)arg4 withLogCenter:(id)arg5;

@end

